### ISSUE TITLE
PECL

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/parallel#1]
Hi @remicollet, can you start the ball rolling on PECL things please ?

I need to rest now, but I'll do a bunch more testing tomorrow, coverage is at 97%~ which is good enough for me, I can't possibly test all error conditions when it comes to threads because you cannot force them to occur.

Ta, and thanks for help earlier :)

**Comment by remicollet** [comment]
Step #1: http://news.php.net/php.pecl.dev/15746

**Comment by remicollet** [comment]
Step #2 : https://pecl.php.net/package/parallel

**Comment by krakjoe** [comment]
yay, thanks @remicollet ... that was fast :)

**Comment by remicollet** [comment]
@krakjoe only created, nothing released yet (I think we need to wait a "few" days, to get feedback on the ML first).

BTW, which version / state  do you want ?   (0.0.1 is perhaps a bit too "experimental")

**Comment by krakjoe** [comment]
I'm going to totally leave that down to you, whatever you think best is good with me.

**Comment by krakjoe** [comment]
Hi @remicollet 

I don't intend to add any features for the first release, and I'm pretty sure everything is in order now.

So, ready when you are :)

Ta

**Comment by remicollet** [comment]
Going to run the release process now

I think 0.8.0 (beta) is ok (if you think we are close to "stable", btw, there is a large set of number available "before" 1.0.0)

**Comment by remicollet** [comment]
Tag, built, uploaded and announced

**Comment by krakjoe** [comment]
Awesome stuff @remicollet, thanks very much :)
