### ISSUE TITLE
Programmer has no control of object copying

### ISSUE THREAD

**Issue by dktapps** [krakjoe/parallel#100]
When we use singletons, it is a problem when we can't prevent their duplication. With pthreads we could prevent serialization, but with parallel there is no way to prevent a referenced object from being copied and therefore duplicated.

(honestly the object copying is a headache and I'd like to see it gone ...)

**Comment by krakjoe** [comment]
Can you give me a concrete (and simple, self contained) example where this causes a problem ?

**Comment by dktapps** [comment]
In PocketMine-MP it's common for large singleton objects like `Server` to be referenced by objects which should be copyable. It's possible to use serialize/unserialize hooks to control member field unserialization (replace reference with global `Server::getInstance()` in unserialize(), and prevent `Server` from being serialized), but with parallel object copying this is impossible.

Another example: I have an enum implementation using objects which implicitly relies on the uniqueness of enum objects at runtime (we can't prevent people trying to compare the objects with `===`), and this assumption is broken by the possibility of object copying. Unfortunately it's impossible to cater for _or_ prevent this.

**Comment by krakjoe** [comment]
> (honestly the object copying is a headache and I'd like to see it gone ...)

There are only two options, to serialize, and not to serialize, and serialization doesn't make sense, is slow, and causes a host of other problems ...

I don't really know what you expect.

What I expected was some simple (but still, "real world") example code, so I could consider the problem and maybe we can come up with some mechanism to solve the problem.

The solution isn't going to be dropping object support or introducing serialization.

**Comment by krakjoe** [comment]
One possible solution, although not achievable today, would be some integration with a future version of annotations, which there is plenty of time to get into PHP 8 still ...

Maybe there is an interim solution that we could implement using doc-block style annotations ...

What I'd really like is that real world example, I'm not familiar enough with P-MP to know exactly what the problem is from your description and don't really have the time to go digging. I of course could write a simple example (because I can _guess_ what you mean) and come up with a simple solution, but I'm interested in knowing the _whole_ problem before I put any time into it ...

**Comment by dktapps** [comment]
Serialize/unserialize hooks allow us to do things like restoring references that aren't supposed to be duplicated (or preventing serialization to begin with).

```php
final class MyFakeEnum{
    /** @var string */
    private $name;

    private function __construct(string $name){
        $this->name = $name;
    }

    public function name() : string{
        return $this->name;
    }

    public static function THING1() : self{
        static $ret = null;
        return $ret ?? ($ret = new self("THING1"));
    }

    public static function THING2() : self{
        static $ret = null;
        return $ret ?? ($ret = new self("THING2"));
    }

    public static function THING3() : self{
        static $ret = null;
        return $ret ?? ($ret = new self("THING3"));
    }

    public function __sleep(){
        throw new \LogicException("Cannot serialize enum instance");
    }
}

\parallel\run(function(MyFakeEnum $thing){
    var_dump($thing === MyFakeEnum::THING3()); //bool(false) :(
}, [MyFakeEnum::THING3()]);
```

Here we can't prevent the copying of MyFakeEnum objects, and nor can we restore their global references to make object equality work the way it was desired to.

**Comment by aleksandr-yulin** [comment]
Hi, I am trying to implement `PromiseA` based on your library, but I also have a problem controlling the copying of objects.
I have now implemented this with `parallel\Sync` ... but not sure yet what is correct
https://github.com/streamcommon/promise/blob/develop/lib/ExtParallelPromise.php

I also have `PromiseA` based on`ext-swoole` ... and I don’t know how but they don’t copy (clone) objects ... at least i get the same `spl_object_hash`

I hope you add control of object copying in future

**Comment by dktapps** [comment]
@krakjoe about the serialize problem, I did have one idea to solve the internal objects state exporting issue: use the data exported by serialize hooks (e.g. __sleep()), but instead of serializing it, do a recursive copy as if it was a normal array, and then reimport this via __wakeup() in the child thread.

This would allow proper resolution of objects references without having to serialize the entire object from top to bottom.

As far as I understand it, this would work nearly the same as userland object copying already works, except that it would also allow copying internal objects.

Obviously such an approach is not perfect, but maybe it's usable.

I'm considering an approach like this for my pthreads fork currently, because it would allow fixing a giant array of problems including closure serialization (nested inside objects) and more besides (serialize breaks objects that aren't from the current context).

Perhaps it might also be desirable to have some parallel-specialized hooks like `__parallelSleep() : array` and `__parallelWakeup(array $data) : void` in order to resolve problems like the OP.

**Comment by dotfry** [comment]
@dktapps, i'll reread your Enum implementation. This is legit code, for a single thread application, but for multithreaded it is hell. I didn't know language that have threads (without enums) and supports your realisation.

btw, idea with serialisation internal objects is interesting.
(for me, i usially, i have only problems with \DateTime objects)

**Comment by dktapps** [comment]
For posterity (not that I expect this to ever get addressed), the fact that this is actually a problem at all is a testament to what a bad idea implicit object copying was to begin with.

```php
$object = getNonDTOWithLotsOfDependenciesThatMakesNoSenseToCopy();
$object->field = 0;
\parallel\run(function() use ($object){
    //first, let's wait for a while while the entire object is recursively copied - WTF? non-obvious performance issue
    $object->field = 1; //this is an object reference, this should work, right? haha nope
})->value();
var_dump($object->field); //still 0. WTF moment if you didn't scrutinize the docs with a magnifying glass.
```

If we replace `parallel\run` with an average user function, the behaviour is what's expected, because that's how closures are _expected_ to work.

The point I'm driving at is the object copying mechanism suffers from the EXACT same problems as pthreads' serialization mechanism does: it's not obvious what the heck is going on. At the language level you expect that an object reference always refers to the same object, and parallel (and pthreads) breaks this assumption. In pthreads, you were just modifying a freshly unserialized useless object with no connection to the original; in parallel, you're doing the exact same thing, except the object was copied by some magic method instead of serialize, which, by the way, cannot support internal objects (wtf kind of limitation is this? is anyone without Zend internals knowledge actually supposed to think this makes sense?)

It's just propagating the paradigm of bad threading extensions where you have to find out the hard way something just doesn't work the way you expect it to, and then having to work around non-obvious limitations and weird behaviours. Threading is already enough of a headache without trying to paper over limitations with magic.

Transferring objects between threads is better left to userland, where the user has full control over what gets copied, how it gets copied, and can also handle internal objects. In most cases I would just resort to serializing the object explicitly, which, while it might suck, makes the intent and behaviour immediately obvious to the reader. (This is what I was already doing in my experiments before object copying was implemented.)

This issue is the primary reason I ended up sticking with a fork of pthreads for PocketMine-MP instead of moving to parallel with 7.4, because at least pthreads is an evil that I know and understand well enough. parallel makes the situation worse by making more non-obvious behaviour - now PM plugin devs would expect they can use() the Server instance into a task, which not only won't work the way they'll expect it to, but it will also cause a big drag on the CPU due to copying that can't be prevented. (That, or it might just randomly explode if I added a private field containing a DateTime somewhere !!)

If anyone ever decides to do something about this issue, please just scrap automatic object copying. It's an anti-feature.

**Comment by krakjoe** [comment]
The problem isn't with the API, but the way you are using it - You are still thinking in terms of *sharing* objects (because that's what pocketmine and pthreads required) and you should be thinking in terms of *communicating* (their fields or yields).

Yes explicitly sharing objects - which is what you are doing when you use(), pass or return an object - is expensive and complicated. You shouldn't be trying to share lots of state. That's the whole point of CSP, you don't rely on sharing ... you communicate ...

**Comment by dktapps** [comment]
@krakjoe my point is that the automatic copying is not intuitively obvious to anyone who doesn't know about these limitations. The prior days where we had to explicitly serialize in order to communicate objects were better because these semantics were much more obvious, and explicit serialize makes it abundantly clear what the limits are just by reading the code. Now it's possible to have weird behaviour by accident because of limitations and behaviour that only comes into play because of ext-parallel.

**Comment by dktapps** [comment]
FWIW, I'm not asking for the ability to share objects; I know that's impractical. I'm saying that given the API presented, it's _expected_ that this kind of code would share objects, which, because it doesn't, produces WTF moments for programmers. Explicit errors and limitations are better for understandability.

**Comment by TheTechsTech** [comment]
Have you tried https://github.com/opis/closure? It's just for this type of issue, an extra step, but works.

**Comment by dktapps** [comment]
I'm not trying to solve a specific programming issue. My comments here are about unintuitive behaviour which arises from ext-parallel being unable to solve threading limitations imposed by PHP (which is OK, because it's not the fault of ext-parallel), and papering over those limitations by adding unexpected magic behaviour in its place (which IS the fault of ext-parallel). This is the exact same mistake which made pthreads so hard and confusing to use.

Failing obviously is always better than doing something unexpected. My WTF-ometer redlines here just as badly as with pthreads' automatic serialization of non-Threaded objects (and that of many PocketMine plugin developers, who already have a hard time understanding what pthreads is doing to their stuff).

**Comment by capsandiego** [comment]
@techno-express Could you please provide an example of the usage of parallel + opis closure?

**Comment by TheTechsTech** [comment]
The idea is to turn your closure into serialable object, then into base64 string, then on other side decode the MIME, then use Opis to unserialize and run.

It will be simpler to create two functions for it.
```php
use Opis\Closure\SerializableClosure;

/**
 * Serialize closure, then encodes to produce MIME base64 structure.
 *
 * @param callable $closure
 *
 * @return string
 */
function encode($closure): string
{
    if ($closure instanceof \Closure) {
        $encoded = new SerializableClosure($closure);
    }

    return \base64_encode(\Opis\Closure\serialize($encoded));
}


/**
 * Decodes a MIME base64 structure, then unserialize the callable.
 *
 * @param SerializableClosure|string $closure
 *
 * @return callable
 */
function decode(string $closure)
{
    return \Opis\Closure\unserialize(\base64_decode($closure));
}
```

```php
class A 
{
    public $one = 1;
    
    public function getOne()
    {
        return $this->one;
    }
}

class B
{
    public function executeParallel()
    {
		$o = new A();
        $task = function() use ($o)
        {
            echo $o->getOne();
        };
	$encodedTask = encode($task);
        $runtime    = new Runtime();
        $future     = $runtime->run(function($encodedClosure) {
			$runnable = decode($encodedClosure);
			$runnable();		
		}, $encodedTask);
		
        $runtime->close();
    }
}

$b = new B();
$b->executeParallel();
```

**Comment by capsandiego** [comment]
@techno-express Thank you very much for your example but, unfortunately, I can't make it work. 
First thing, in the ```$runtime->run()``` I think we need to pass an array as the second argument, not a string. Anyway, even if I change ```$encodedTask``` to ```[$encodedTask]``` it doesn't work (no errors generated, just it doesn't print anything. FYI/ I test it with PHP -7.4.13 and 8.0.3.

Could you please clarify?

**Comment by TheTechsTech** [comment]
Maybe some general debugging, put inside `try/catch` block with a `print_r($o);`

**Comment by dktapps** [comment]
This is really getting away from the point ...

**Comment by TheTechsTech** [comment]
You right, trying to give a work around besides not using package at all, since of all the limitations.

**Comment by dktapps** [comment]
The problem that I'm talking about here is that limitations are unclear, because of parallel's anti-features masking limitations with unexpected behaviour. I'm not looking for a workaround.

I want the limitations of ext-parallel to be more clear (Zend imposes some limits, which should be clear, instead of trying to paper over them), and the object copying "feature" to be removed, because it has the exact same logical flaws as ext-pthreads' automatic serialization of non-Threaded objects (which was _also_ very unintuitive).

Object copying is no better than serialization (and arguably worse, because it has more limitations).
