### ISSUE TITLE
How to set the name of a thread

### ISSUE THREAD

**Issue by phpth** [krakjoe/parallel#102]
I want to set the name of the thread, which is used to identify the thread execution status information of different tasks in the task management interface, but the api does not set the entry.

**Comment by dotfry** [comment]
I'll use `cli_set_process_title`

**Comment by krakjoe** [comment]
Well, there are two problems here ... firstly and most importantly there isn't a portable way to do this.

Secondly, if we're going to name anything, it should be tasks not threads, since they are the unit of execution.

I think this doesn't really make a lot of sense ...

**Comment by phpth** [comment]
Heartfelt thanks, understand why there are not so many interfaces. Keeping it simple is really friendly for getting started or simple to use, but it may not be suitable for complex applications. So, keep it simple and efficient, and please ensure stability @dotfry @krakjoe
