### ISSUE TITLE
7.4 Memory leaks in Sync

### ISSUE THREAD

**Issue by dotfry** [krakjoe/parallel#103]
I'll switched to php 7.4 RC6 (on Linux 5.3.13-arch1-1 x86_64 GNU/Linux) and getting memory leaks.

Sample code, backtrace and valgrind logs in attachment.

[issue-leaks-74.tar.gz](https://github.com/krakjoe/parallel/files/3892064/issue-leaks-74.tar.gz)

**Comment by avolver** [comment]
Thanks!
