### ISSUE TITLE
phpstrom auto auto-complete

### ISSUE THREAD

**Issue by fengahan** [krakjoe/parallel#105]

**Comment by dktapps** [comment]
description 100

**Comment by WyriHaximus** [comment]
FYI if you upgraded to the latest PHPStorm the stubs are available but disabled by default:
![Screenshot from 2019-11-30 22-39-03](https://user-images.githubusercontent.com/147145/69906341-5cd0ea80-13c2-11ea-80b8-b34ec8620a56.png)

**Comment by fengahan** [comment]
@WyriHaximus Thanks
