### ISSUE TITLE
Windows + PHP 7.4 support

### ISSUE THREAD

**Issue by some-sam** [krakjoe/parallel#107]
I'm unable to get this library working on Windows + PHP 7.4 (VC16).  The PECL repository only has up to PHP 7.3, and with VC15:  https://windows.php.net/downloads/pecl/releases/parallel/1.1.3/

I cannot for the life of me find any instructions on how to build the DLLs manually, so I'm just stuck unless I want to downgrade my PHP.

Any help appreciated!

**Comment by krakjoe** [comment]
7.4 builds will appear with the next release, which will hopefully be soon ish ...

**Comment by some-sam** [comment]
Ok, great news. Meanwhile there's a bug in PHP 7.3 on windows + apache: https://github.com/krakjoe/parallel/issues/108

Hopefully that's fixed by switching to 7.4! I'm very much looking forward to using this library.

**Comment by filecage** [comment]
The PHP 7.4. builds for Windows are available and work perfectly fine. This issue can be closed.
