### ISSUE TITLE
Getting `parallel` to work in PHP + Apache

### ISSUE THREAD

**Issue by some-sam** [krakjoe/parallel#108]
Running the following from command line works fine. Running from apache outputs "STARTING" and then the connection is reset. (It also resets all other apache connections.) I've stripped the code down to bare minimum, and the failure occurs when `new Runtime()` is called.

    register_shutdown_function(function(){
        // this is not executed after the crash in apache.
        echo "SHUTTING DOWN";
        flush();
    });
    
    // destroy any output buffers
    while (ob_get_level()){
        $body = ob_get_contents();
        ob_end_clean();
    }
    // echo "starting" and flush it immediately
    echo "STARTING";
    flush();
    
    // this line appears to crash when run from Apache.
    $runtime = new \parallel\Runtime();
    
    $future = $runtime->run(function(){
        for ($i = 0; $i < 500; $i++)
            echo "*";
    
        return "easy";
    });
    
    for ($i = 0; $i < 500; $i++) {
        echo ".";
    }
    
    printf("\nUsing \\parallel\\Runtime is %s\n", $future->value());
    echo "DONE"; flush();
    die;

Windows 10
PHP: 7.3.12, TS, VC15, x64
parallel: 1.1.3-7.3-ts-vc15-x64
Apache: 2.4.41, TS, VC15, x64

**Comment by jLynx** [comment]
I think this could be similar to mine https://github.com/krakjoe/parallel/issues/113

**Comment by some-sam** [comment]
The same issue occurs in 7.4:

PHP: 7.4.1, VC15, x64
Apache: 2.4.41, VC15, x64
Parallel: php_parallel-1.1.3-7.4-ts-vc15-x64

Works fine in command line, but from Apache it crashes right at `$runtime = new \parallel\Runtime();`

**Comment by applealkoal** [comment]
Yea mine too same thing, Tell me if you find any solution

**Comment by cmb69** [comment]
If this is still an issue with latest parallel, a [stack backtrace](https://bugs.php.net/bugs-generating-backtrace-win32.php) could be helpful.

**Comment by cmb69** [comment]
No feedback for more than two weaks, so I'm closing this ticket.
