### ISSUE TITLE
hi my code hava an error `zend_mm_heap corrupted`

### ISSUE THREAD

**Issue by fengahan** [krakjoe/parallel#109]
`<?php

use parallel\Channel;
use parallel\Runtime;
$sarr=[];
for ($i=0;$i<3;$i++){
    $sarr[$i]=new Runtime();

}
$ev=new \parallel\Events();
$ch=Channel::make("sv",3);
for ($i=0;$i<3;$i++){

   $in= $sarr[$i]->run(function($ch){
        $functions = array("addslashes", "chunk_split", "metaphone", "strip_tags", "md5", "sha1", "strtoupper", "strtolower", "strrev", "strlen", "soundex", "ord");
        $string = "the quick brown fox jumps over the lazy dog";
        for ($i = 0; $i < 4000; $i++) {
            foreach ($functions as $function) {
                call_user_func_array($function, array($string));
            }
        }
        $ch->send(time());
    },[$ch]);
}
for ($i=0;$i<3;$i++){
   echo $ch->recv();
   echo "\r\n";
}`

**Comment by avolver** [comment]
Please provide information about your environment: OS, php version, parallel version or git revision sha.

**Comment by temuri416** [comment]
I can reproduce this error.

Ubuntu 18, PHP 7.2.28.

> $ php --ri parallel
> 
> parallel
> 
> parallel support => enabled
> parallel version => 1.1.4-dev
> 

git commit ID:

> root@threads18:~/install/parallel# git rev-parse HEAD
>  efeaa944025856f995fbbeff189c05a69d42d2be

**Comment by pizzo00** [comment]
When will we get a release with this fix?
Or how can i compile this repo for windows?
Thanks
