### ISSUE TITLE
Getting value of a finished Future

### ISSUE THREAD

**Issue by remicollet** [krakjoe/parallel#11]
Tryingt to write some example, implementing a `-j# `like option

Is it possible to run a $f->value, from the $done array returned by a select ?

See example:

```
<?php
if (!extension_loaded("parallel")) {
	die("parallel extension required\n");
}

$runtime = new \parallel\Runtime();
$tasks = [];
for ($i=1 ; $i < 10 ; ) {

	if (count($tasks) < 4) { // Never launch more than 4 workers
		$workers[$i] = new \parallel\Runtime();
		$tasks[$i] = $workers[$i]->run(function($i){
			$t = rand(1,4);
			sleep($t);
			return "$i done after $t\"\n";
		}, [$i]);
		echo "$i launched\n";
		var_dump($tasks[$i]);
		$i++;

	} else { 				// Wait 1 worker to end
		echo "select: ";
		$done = $err = [];
		if (\parallel\Future::select($tasks, $done, $err)) {
			printf("%d done, %d errored, %d still running\n", count($done), count($err), count($tasks));

			foreach($done as $task) {
				var_dump($task);
				//echo $task->value();
			}

		}
	}
}

// wait all remaining worker
while (\parallel\Future::select($tasks, $done, $err)) {
	printf("%d done, %d errored, %d still running\n", count($done), count($err), count($tasks));
	foreach($done as $task) {
		var_dump($task);
		//echo $task->value();
	}
}
```

Is seems the call to value() hangs...

**Comment by krakjoe** [comment]
Woops, sorry about that ... can you push out a release with that fix please ... after testing, of course :)

**Comment by krakjoe** [comment]
+the next couple of commits ...

**Comment by remicollet** [comment]
Waiting for travis after adding test for this...

**Comment by krakjoe** [comment]
hehe, I also pushed a test ... I thought I'd put bug tests in a different folder ...

**Comment by krakjoe** [comment]
We'll go with your test, mine was crappy ...  I'll work on bringing coverage up another day, little busy at the moment and can't really concentrate fully ...

EDIT: I pushed after your prepare commit ... check what bad things I done there ?

**Comment by remicollet** [comment]
> EDIT: I pushed after your prepare commit ... check what bad things I done there ?

only your test added / reverted
`diff checkout release; git diff develop` is empty (only package.xml)

BTW, 0.8.1 is now Released (and announced)

**Comment by krakjoe** [comment]
cool, ta remi

**Comment by steve-amp** [comment]
@krakjoe 
any idea why i got "Call to undefined method parallel\\Future::select" when i try \parallel\Future::select
