### ISSUE TITLE
Which threading/parallel/concurrency library to use?

### ISSUE THREAD

**Issue by flip111** [krakjoe/parallel#111]
Hi krakjoe,

I saw that there are now two libraries related to threads by you https://github.com/krakjoe/pthreads and this one. I already read https://gist.github.com/krakjoe/6437782 and https://gist.github.com/krakjoe/9384409 But it's unclear to me how the possible solutions of threading compare to each other. On top of that there also seem to be other solutions like https://github.com/amphp/parallel and maybe swoole also provides some things.

I have a use case where i want to use `hash_file` or multiple large files and i like to parallelize this using all my cores. So i would like to detect how many capabilities my CPU has (i know it has support for 8 threads at the same time, using 4 cores ... but i like it to be portable to other systems). And then to start a thread pool of 8 and process all the files.

I can just try to start using a library ... but i'm a bit dazzled about all the possible libraries that there are available. Also when i talk to other people they (still) advice to setup some job server like gearman and use that instead. But my CLI script is just single file and i like to send it to my friend.

I also like async programming with futures/promises/coroutines.

Thank you

**Comment by erik404** [comment]
I believe Parallel is the successor to pthreads.

Quoting Krakjoe from his blogpost about parallel: "and for those people thinking about using pthreads for new code: don't be silly."

https://blog.krakjoe.ninja/2019/02/parallel-php-next-chapter.html

**Comment by dotfry** [comment]
You can use https://github.com/krakjoe/sysconf (if that still works) or just read `/proc/cpuinfo` (on windows you need something to work with WMI) to detect number of cores.

I'll think better use parallel instead of pthreads, but that is only yours desigion.

**Comment by NikoGrano** [comment]
Ref https://github.com/krakjoe/pthreads/issues/938

**Comment by krakjoe** [comment]
Sorry, but this is beyond the scope of issues (it's not a bug).
