### ISSUE TITLE
Can't we instantiate an object from a runtime closure? 

### ISSUE THREAD

**Issue by romainmoyne** [krakjoe/parallel#114]
When I try to do that, I get " Uncaught Error: Class 'service\MyWorker' not found "

So if it's true, we can't instantiate a Guzzle object (in order to build a crawler for instance) when in the runtime closure?

**Comment by dotfry** [comment]
You can do anything in closure, just include your autoloader.

Or use it as bootstrap file (in `Runtime::__construct`)

**Comment by krakjoe** [comment]
Sorry, but this is beyond the scope of issues (it's not a bug).
