### ISSUE TITLE
parallel 1.1.3 + php 7.4.1 / 7.2 = inconsistent

### ISSUE THREAD

**Issue by harryqt** [krakjoe/parallel#116]
Windows 10 (64 bit).

```
C:\tools\php741-zts>php741ts -v
PHP 7.4.1 (cli) (built: Dec 17 2019 19:24:02) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

![cmd_2019-12-23_23-04-59](https://user-images.githubusercontent.com/18257605/71372419-58bb7580-25da-11ea-84e0-f8ca4dec3c3e.png)

```
C:\tools\php72-zts>php72ts -v
PHP 7.2.26 (cli) (built: Dec 17 2019 15:29:10) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```
![cmd_2019-12-23_23-27-23](https://user-images.githubusercontent.com/18257605/71373060-f6fc0b00-25db-11ea-8f40-5e151b8129aa.png)

**Comment by WyriHaximus** [comment]
Not sure wat you're trying to tell us but threads by nature are `inconsistent`/unpredictable as shown by the screenshots you posted.

**Comment by harryqt** [comment]
I'm very new in this, so pardon me if I don't understand it. But shouldn't the output show something like this?

```
.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.*.
Using \parallel\Runtime is easy
```

**Comment by WyriHaximus** [comment]
Ah yes and no. Yes as in threads should echo when the kernel schedules them for execution, which simply said is taking turns. No as in we can't predict how the kernel will schedule so all the outputs above and the example are possible and valid.

**Comment by harryqt** [comment]
Ah. Understood. Thank you.
