### ISSUE TITLE
Why are processes blocking

### ISSUE THREAD

**Issue by aleksandr-yulin** [krakjoe/parallel#117]
Hi, could you explain why the processes block each other?

For example
```php
(new Runtime())->run(function () {
    sleep(3);
    echo 'SECOND' . PHP_EOL;
});

(new Runtime())->run(function () {
    echo 'FIRST' . PHP_EOL;
});
```

And result
```console
$ php example/ext-parallel/test.php 
SECOND
FIRST
```

**Comment by dktapps** [comment]
The `Runtime` destructor automatically shuts down threads, which makes the main thread wait for the child thread to stop. If you save the `Runtime` instances to variables, they'll work as you expect.

**Comment by aleksandr-yulin** [comment]
It works thanks!

**Comment by harryqt** [comment]
> If you save the `Runtime` instances to variables, they'll work as you expect.

@dktapps Thanks it works. But is there other way to solve the issue without saving the instances to variable? I don't want to create variable.

**Comment by dktapps** [comment]
The only solution is to keep references to the Runtimes around, otherwise their destructors will be immediately called (which will try to join the thread).
You might consider using `parallel\run()` instead of creating a dedicated runtime.

**Comment by Dibbyo456** [comment]
> You might consider using `parallel\run()` instead of creating a dedicated runtime.

yeah that works though but the main problem is I can't include auto loader, can I ?
