### ISSUE TITLE
Assertion failed: (zend_gc_refcount(&(ht)->gc) == 1) on PHP 7.4.1

### ISSUE THREAD

**Issue by autaut03** [krakjoe/parallel#119]
Hey there. I'm using [amphp/parallel](https://github.com/amphp/parallel) alongside this extension and trying to run their [example code](https://github.com/amphp/parallel/blob/master/examples/parallel-extension.php) and it doesn't work. The same example code with same dependencies works on PHP 7.3.12. Hence, I'm submitting an issue here. This is an assertion failure I get when getting to [this line of code](https://github.com/amphp/parallel/blob/master/lib/Context/Internal/ParallelHub.php#L59):
```
Assertion failed: (zend_gc_refcount(&(ht)->gc) == 1), function shutdown_executor, file /Users/alexwells/.phpbrew/build/php-7.4.1/Zend/zend_execute_API.c, line 289.
```

Environment:
```
php 7.4.1 zts + parallel
macos
latest amphp/parallel
```

**Comment by dotfry** [comment]
This is same problem as #110.

**Comment by krakjoe** [comment]
If this persists under 8, please open a new issue.

7 support is dropped in develop.
