### ISSUE TITLE
How to build Docker image with parallel using pecl

### ISSUE THREAD

**Issue by Mariyo** [krakjoe/parallel#122]
Hello,

I am facing problem, that I am not able to build Docker image due to ZTS not enabled.

Dockerfile:
```
FROM php:zts
RUN pecl install parallel-beta
CMD tail -f /dev/stdout
```

Error: 
```
checking for ZTS... configure: error: parallel requires ZTS, please use PHP with ZTS enabled
ERROR: `/tmp/pear/temp/parallel/configure --with-php-config=/usr/local/bin/php-config' failed
```

Thank you for any advice

**Comment by rybakit** [comment]
Here is how I do it without pecl: https://github.com/tarantool-php/benchmarks/blob/master/Dockerfile#L35-L37

**Comment by fredericdepuydt** [comment]
If you're OK with an alpine container, try this:

```
FROM php:7.3-zts-alpine

RUN apk update
RUN apk add --no-cache \
        $PHPIZE_DEPS
RUN pecl install parallel \
    && docker-php-ext-enable parallel
```

**Comment by Mariyo** [comment]
Hi,

for sure I am OK with alpine :)

It works now, I can give  a try,

Thank you
