### ISSUE TITLE
Passing ressources (socket, ...) other than basic types int to Runtime-> run(function)

### ISSUE THREAD

**Issue by r2d2r01** [krakjoe/parallel#128]
Hi, I'm in progress migrate from Thread to Parallel\Runtime and have problem to provides externals existing ressources (socket, log, class,..) other than int, string to function executed by Runtime-> run().
I have null values ou incompatibility.
What's the right way of proceed.
Thank's for help
Frederic

`		  
```
  $CXSERVER_VERSION="CXSERVER 1.00.000 20200211";
  //static 
  $_cxsock=null;
  $thread_function` = function ($cxsock) use ($_cxsock,$CXSERVER_VERSION) //int $id, Channel $ch) 
   {
    //echo '$GLOBALS[CXSERVER_VERSION] = '.$GLOBALS["CXSERVER_VERSION"]; //=NULL
      echo ("\n***** function:start=".$CXSERVER_VERSION);//OK;***** function:start=CXSERVER  1.00.000 20200211
    //$buf = socket_read($_cxsock, 2048, PHP_NORMAL_READ);//KO:$_cxsock=null
      $buf = socket_read($cxsock, 2048, PHP_NORMAL_READ);//KO:$_cxsock=null
       echo ("\n RX[".$buf."]");
       echo ("\n***** function:stop");
   };

```        
        $socksvr = socket_create(AF_INET, SOCK_STREAM, SOL_TCP);
        socket_bind($socksvr, $address, $port);
        socket_listen($socksvr, 5);
        $_cxsock = socket_accept($socksvr);
         $args = array();
        //$args[0] = $_cxsock;
        $th = $rt->run($thread_function, $args);
`

**Comment by dotfry** [comment]
https://www.php.net/manual/ru/parallel-runtime.run.php#refsect1-parallel-runtime.run-argv-characteristics

**Comment by r2d2r01** [comment]
Thank's dotfry, i have readen yesterday on night, lot of restricted comportement, more complicated libray than  thread native.
Migration will !  easy thing, it's a complete refund of my code ....
Casting socket to int (oups)...

**Comment by r2d2r01** [comment]
Use other solution
Thank's and bye
