### ISSUE TITLE
zend_mm_heap corrupted in parallel test script

### ISSUE THREAD

**Issue by temuri416** [krakjoe/parallel#129]
**PHP script:**

```php
<?php
$runtimes = [];
$futures = [];

foreach (range(0, 4) as $i) {
    $runtimes[$i] = new \parallel\Runtime();
    $futures[$i] = $runtimes[$i]->run(function() {
        foreach (range(512, random_int(1024, 2048)) as $j) {
            echo ',';
        }

        return true;
    });

}

do {
    echo ".";
} while (count(array_filter($futures, function ($future) {
    return $future->done() === false;
})) > 0);
```

**Output:**

> zend_mm_heap corrupted

**Environment:**

Ubuntu 18, PHP 7.2.28.

> $ php --ri parallel
> 
> parallel
> 
> parallel support => enabled
> parallel version => 1.1.4-dev
> 

**git commit ID:**

> root@threads18:~/install/parallel# git rev-parse HEAD
>  efeaa944025856f995fbbeff189c05a69d42d2be

**Comment by temuri416** [comment]
found the culprit:

> extension=protobuf.so

disabling `protobuf.so` makes it run fine.

**Comment by krakjoe** [comment]
Looks unrelated to parallel.
