### ISSUE TITLE
Bug in literals copying

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/parallel#13]
Bug in copying literals may lead to corrupted heap.

For some reason I wrote this really strange, spotted errors during review ... the nature of this bug means it's somewhere between hard and impossible to write a test for it, it's definitely there though, I see it very clearly with fresh eyes.

**Comment by krakjoe** [comment]
Fixed in 0f84a11fe7a5ed5d9cf6a5b646acd0bcfb19629b

/cc @remicollet  this will want a release after CI ...

**Comment by krakjoe** [comment]
I spotted another bug in copy code ...

**Comment by krakjoe** [comment]
I think we're good to push out a release with these fixes, when you're ready ... Changelog should just be "bugs in copying literals"

**Comment by remicollet** [comment]
release process running
