### ISSUE TITLE
session can't be manipulated in Runtime

### ISSUE THREAD

**Issue by saniel** [krakjoe/parallel#131]
PHP thinks that headers have been already sent, when nothing has been sent to output yet. This makes attempt to manipulate a session to trigger a warning.

Here is very simple code to reproduce the issue:

```php
$worker = new \parallel\Runtime();
$worker->run(function () {
    session_save_path("/tmp");
    ini_set("session.gc_maxlifetime",10000);
});
```

Tested on Ubuntu 18.04, PHP 7.2.7, parallel 1.1.3.

**Comment by krakjoe** [comment]
Backing sessions are many many modules, with varying degrees of preparedness ...

I think there's not much point in making this work, just avoid using what is probably unsafe.
