### ISSUE TITLE
parallel\Runtime\Type\Unavailable on object that is not internal

### ISSUE THREAD

**Issue by CViniciusSDias** [krakjoe/parallel#133]
I have the following code:

```php
foreach ($guestList as $lineNumber => $guest) {
    $runtime = new Runtime();
    $runtime->run(function (Bathroom $bathroom, Channel $cleaningChannel, Guest $guest, int $lineNumber) {
        $number = ($lineNumber % 2) + 1;
        $guest->do($number, $bathroom, $cleaningChannel);
    }, [$bathroom, $cleaningChannel, $guest, $lineNumber]);
}
```

And I'm getting the following error:

> Fatal error: Uncaught TypeError: Argument 1 passed to {closure}() must be an instance of CViniciusSDias\Parallel\Bathroom, instance of parallel\Runtime\Type\Unavailable given in /opt/project/main.php:26

This is my class `Bathroom`:
```php
<?php

namespace CViniciusSDias\Parallel;

class Bathroom
{
    private bool $isDirty = false;

    public function makeItDirty(): void
    {
        $this->isDirty = true;
    }

    public function clean(): void
    {
        $this->isDirty = false;
    }

    public function isDirty(): bool
    {
        return $this->isDirty;
    }
}

```

It only has a `bool`. No internal objects. Why am I getting this error?

**Comment by CViniciusSDias** [comment]
My bad. I was not passing the autoloader.

**Comment by ttodua** [comment]
>  I was not passing the autoloader.

can you tell the "corrected example" in your case? so, what/where the autoloader had to be added? Do you mean such?

`$runtime = new Runtime($pathToClassPhpFile);`

**Comment by TheTechsTech** [comment]
> $runtime = new Runtime($pathToClassPhpFile);

This extension's **documentation/examples** leaves a lot to be desired. In general, **"include/require"** should just be a reference to the `composer` autoloader script. 

$pathToClassPhpFile = 'path/to/vendor/autoload.php';

Make sure `composer.json` have the proper **psr-4** _namespace_ layout of the _classes_.
