### ISSUE TITLE
Cannot Use Parallel with PHP 7.4

### ISSUE THREAD

**Issue by Airy301** [krakjoe/parallel#134]
I just learned about Parallel and tried to work with it but when I installed I got following error

> PHP Startup: Unable to load dynamic library 'php_parallel.dll' 

I followed and downloaded exactly the same DLL as per my PHP Installation

My Current PHP Installation is **PHP 7.4.4 TS VC 15 x64**
I downloaded this https://windows.php.net/downloads/pecl/releases/parallel/1.1.3/php_parallel-1.1.3-7.4-ts-vc15-x64.zip

Extracted php_parallel.dll into PHP Ext directory and pthreadVC2.dll in PHP main directory and also to windows system32 directory (as a side check) and enabled the extension in php.ini extension=php_parallel.dll

But still it is not working. 

Is it because I am running PHP on Ningx? And other question is that can we use Parallel for Webserver Application unlike pThread which was particularly for CLi?

**Comment by harryqt** [comment]
> Is it because I am running PHP on Ningx? And other question is that can we use Parallel for Webserver Application unlike pThread which was particularly for CLi?

Parallel only works in CLI.

**Comment by Synida** [comment]
+1: You need the ZTS version and compile the php from source with this flag on windows: --enable-zts xor with this flag on linux: --enable-maintainer-zts

**Comment by harryqt** [comment]
> compile the php from source with this flag on windows

No need to compile from source on Windows because you can download ZTS version from https://windows.php.net/download

Just need to put `php_parallel.dll` to the `ext` directory and add `pthreadVC2.dll` to the `PATH` which noted on [the docs](https://www.php.net/manual/en/parallel.setup.php).

**Comment by Airy301** [comment]
> > compile the php from source with this flag on windows
> 
> No need to compile from source on Windows because you can download ZTS version from https://windows.php.net/download
> 
> Just need to put `php_parallel.dll` to the `ext` directory and add `pthreadVC2.dll` to the `PATH` which noted on [the docs](https://www.php.net/manual/en/parallel.setup.php).

I tried everything and followed the exact documentations. I think the real problem was I tried it on a Web Application and it only works with CLi version of PHP as mentioned by Dibbyo456.
