### ISSUE TITLE
Issue with imap_open inside of a worker

### ISSUE THREAD

**Issue by inedev** [krakjoe/parallel#142]
Hello,

I am having issues trying to implement an email fetcher thread, that would fetch emails from an imap mailbox.

I have the following fragment inside my worker:
```
$chan = Channel::open("comm.{$workerid}");
while($emaildata = $chan->recv()) {
    if($emaildata) {
    	$imap = imap_open($emaildata["imap_mailbox"], $emaildata["username"], $emaildata["password"],  OP_SECURE );
```
I get the following notice upon imap_open:
```
Warning: imap_open(): Couldn't open stream {imap.yandex.com:993/imap/ssl}
```
When I dump imap_errors() I get this:
```
  string(47) "Can't do secure authentication with this server"
```
`$emaildata` comes OK over the channel - if I dump the mailbox and credentials, they are fine. 

Same `imap_open` line with the same input data and the rest of my email handling code runs fine inside of a funciton run procedurally.

I am running php 7.4.6 (ZTS) that i compiled myself and parallel 1.1.3 on a VirtualBox VM running Ubuntu 18.04.4.

Today I tested this on a real machine running ubuntu 16 to exclude the VM factor and I got the same result.

Any help would be greatly appreciated as I am kind of stuck. Thanks!

**Comment by dotfry** [comment]
`resource` type cannot be transfered via `parallel\Channel`, read https://www.php.net/manual/ru/parallel-runtime.run.php#refsect1-parallel-runtime.run-argv-characteristics

**Comment by krakjoe** [comment]
From the PHP manual:

>  The IMAP extension is not thread-safe; it should not be used with ZTS builds. 

While the above is true, nothing can be done, sorry.
