### ISSUE TITLE
Segfault if php-di attempts to inject a broken or missing dependency

### ISSUE THREAD

**Issue by Radiergummi** [krakjoe/parallel#144]
We use `parallel` from the master branch with PHP 7.4.5 currently. I originally wrote an application layer on top of php-pthreads (which worked pretty well by the way, I must be [one of those 4 people](https://blog.krakjoe.ninja/2019/02/parallel-php-next-chapter.html#:~:text=that%20about%204%20people%20really%20understand)).  
After the deprecation notice and realizing it blocks us from migrating to PHP 7.4, however, I re-built the stack to use parallel and [PHP-DI](https://php-di.org/). This _mostly_ works, but with a caveat: Sometimes, the threads crash without any prior error, `strace` returns nothing useful and we basically have to breakpoint our way through the app to find the offending line.  

We've noticed that if PHP-DI attempts to inject a dependency into a class, and that definition or annotation contains a typo, the application will _reproducibly_ crash. So this seems to be related to either the autoloader or the exception handling inside parallel. I tried to extract this into a separate, minimal reproduction example but couldn't get it to segfault there, so I'm still working on that.  

Is there anyone else having trouble with PHP-DI or `@Inject` annotations and php-parallel?

**Comment by krakjoe** [comment]
Since no reproducing case was ever provided, there's nothing I can do.
