### ISSUE TITLE
How  can I share mysql connections to the runtime

### ISSUE THREAD

**Issue by devqm** [krakjoe/parallel#147]
The channel doesn't seem to work.

**Comment by devqm** [comment]
I want to generate connection pools through parallel in CLI mode

**Comment by WyriHaximus** [comment]
They are resources and as such they can't be shared with threads. You can however open the connection in the thread and let the main thread communicate through a channel with it by proxying queries and results to and from the thread.

**Comment by devqm** [comment]
> They are resources and as such they can't be shared with threads. You can however open the connection in the thread and let the main thread communicate through a channel with it by proxying queries and results to and from the thread.

I think I know how to do it.

**Comment by devqm** [comment]
> They are resources and as such they can't be shared with threads. You can however open the connection in the thread and let the main thread communicate through a channel with it by proxying queries and results to and from the thread.

Thanks!
