### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by srjlewis** [krakjoe/parallel#149]
Hi

Could you do a new release of parallel, as I am finding version 1.1.3 is quite buggy and segfaults a lot.

I am building the latest from github, which works really well, with no crashes.

So it would be great if you could do a new version release of parallel as the current 1.1.3 is not stable on CentOS 8 / PHP 7.4

**Comment by remicollet** [comment]
See #150

**Comment by remicollet** [comment]
1.1.4 is released
