### ISSUE TITLE
Non-blocking Future::select()?

### ISSUE THREAD

**Issue by tux-rampage** [krakjoe/parallel#15]
Is it possible to provide a non-blocking variant of the `Future`'s `select()` method?
I've got a use case for this extension within an event-based loop (ext-uv for example), which would require polling the future state in a non-blocking manner.

By now I'd do a workaround and select with a timeout of `1`. Would `0` work here as well and return immediately? If so, this issue can be closed, since non-blocking is possible.

**Comment by krakjoe** [comment]
> Would `0` work here as well and return immediately?

Yes.

**Comment by tux-rampage** [comment]
Is this worth some Documentation? Do you accept contributions for the docs?

**Comment by krakjoe** [comment]
Sure, it's in the manual, if you ping with a patch on edit, I'll review it ... or else if you have the karma, just do it ... I only got as far as a "skeleton" for docs, it really needs more work ... I hate xml/docbook ...
