### ISSUE TITLE
documentation code example

### ISSUE THREAD

**Issue by paveldvorak5** [krakjoe/parallel#151]
Hi,
I read the documentation but I don't know how to use it.

This is my use case. I need to do a stock exchange script.
I have a main thread that holds the main stock exchange class. I knows about stocks on the exchange and orders them to update. Something like this.

Main thread ticks and update all stock threads.
Exchange -> tick -> update all stock threads with new data

A stock thread holds info about that stock and is running for the duration of the program.
How can I do this? Thanks

**Comment by srjlewis** [comment]
read to user comment on https://www.php.net/manual/en/class.parallel-events.php as has it has a good example of how to use channels and events, as you could use events and channels to send the data ansync to the worker threads.

The other way is to start each stock in a runtime and use a static property within the thread (not in the closure but in a singleton class) which will survive between calls to parallel\Runtime::run ( Closure $task , array $argv ) : ?Future
