### ISSUE TITLE
Channel "readable()" method

### ISSUE THREAD

**Issue by awderh** [krakjoe/parallel#152]
Hi,

I was wondering why a Channel::hasData method isn't available to prevent blocking on a _recv_ call? I understand that there is an _Events_ way of dealing with this, but I don't find it as convenient.

(Apologies if this is a dumb question)

**Comment by awderh** [comment]
I decided to look inside the source code, and it seems like you have a function:
`php_parallel_link_readable` in [`src/link.c`](https://github.com/krakjoe/parallel/blob/develop/src/link.c) line 349

Which is used in [Events::poll](https://github.com/krakjoe/parallel/blob/develop/src/poll.c) line 125.

I was then thinking of adding some code but then I came upon this discussion regarding Go: https://stackoverflow.com/questions/3398490/checking-if-a-channel-has-a-ready-to-read-value-using-go

It seems like they actually discourage this kind of consistent polling....

That being said, I don't see why we can't directly ask a Channel or Future if it's ready to be read. I get that it may not be the best design, but, I think this choice should be left to the programmer. 

@krakjoe If I was to add this feature in myself, would you approve it? I'm thinking of making a new function (Channel::readable), but it may also make sense to extend (via argument) `Future::value()` or `Channel::recv()`. I'd prefer the former.

Also, thank you very much for all your hard work!

**Comment by dotfry** [comment]
Use https://www.php.net/manual/ru/class.parallel-events.php

**Comment by awderh** [comment]
Closing because Events is the "right way" to do things. Cheers
