### ISSUE TITLE
Working with google cloud

### ISSUE THREAD

**Issue by sebe6** [krakjoe/parallel#153]
Hi, I'm currently trying to use parallel to handle some calls to some of the google cloud API
To do so I need to use `namespace`, `setenv()` (for the credentials), `require` (composer autoload) and `use`, so I've put them in the thread function

Unfortunately `namespace Google\Cloud\Samples\Vision;` trigger this error:
`Parse error: syntax error, unexpected 'Google' (T_STRING), expecting \\ (T_NS_SEPARATOR) in C:\wamp64\www\test\test_parallel.php on line 16`

And `use Google\Cloud\Vision\V1\ImageAnnotatorClient;` trigger this one:
`Parse error: syntax error, unexpected 'use' (T_USE) in C:\wamp64\www\test\test_parallel.php on line 24`

Am I doing it wrongly ? Or is it just impossible using parallel ?

**Comment by awderh** [comment]
Can you post your code? This looks like it may be an interpreter syntax error and not an issue with parallel itself.

**Comment by sebe6** [comment]
Yes I'm pretty sure it is, what I meant is that I don't see any way to do it, but I'm still learning multi threading

Here's the code without the useless stuffs

```use parallel\Runtime;
use parallel\Channel;

$url_test = array('url google storage', 'url google storage', 'url google storage');

$thread_function = function (Channel $ch, $k, $url) {
	namespace Google\Cloud\Samples\Vision;
	putenv("GOOGLE_CLOUD_PROJECT=reetags-reactnative");
	putenv("GOOGLE_APPLICATION_CREDENTIALS=reetags-275011-2b9a4e9d9957.json");
	require 'vendor/autoload.php';

	use Google\Cloud\Vision\V1\ImageAnnotatorClient;
	
	$imageAnnotator = new ImageAnnotatorClient();
}

try {
    // channel where the data will be sharead
    $ch = new Channel();
  
    foreach($url_test as $k => $v){
		$run->run($thread_function, $k, $v);
	}
} catch (Error $err) {
    echo "\nError:", $err->getMessage();
} catch (Exception $e) {
    echo "\nException:", $e->getMessage();
}
```

**Comment by awderh** [comment]
**Edit**
Use and namespace statements aren't allowed, I believe. You should package that kind of code in a separate file, and ensure it is available by bootstrap.

Also, you have another issue here, I believe:

`$run->run($thread_function, $k, $v);`

Note docs on [run](https://www.php.net/manual/en/parallel.run.php): it takes _at most_ two arguments, where the _second_ argument is an _array_ of arguments to pass to the _closure_ (i.e., $thread_function) in your case.

(Also, please try formatting the code a bit nicer next time ☺️  - see [this ](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) on block markup)

**Comment by sebe6** [comment]
Oups, I had corrected this one but it seems I did too many Ctrl + Z 😅

Thanks to your guidance I've put everything inside an external file using a function and require, now it works ! 👍 

Since I'll need to save the results I've tried iterate through the `recv()` of the channel I've used, but it seems to end up stuck there since I don't reach the die following it
```
while($rc = $ch->recv()){
	echo $rc;
}
die((time()-$t)); // run duration
```

I know I could just iterate using something like `for($i = 1; $i < count($url_test); $i++)` but I don't find it clean 😕
I don't see anything about it in the doc, is there a best practice to do this ?

(I'm not used to post here and it was late, but after seeing the doc I can manage it :p )
