### ISSUE TITLE
Question: Migrating from pthreads. Worker = ?, Volatile/Thread = ?

### ISSUE THREAD

**Issue by TechnagyDev** [krakjoe/parallel#155]
I just got started with pthreads and finally got things working, but then realized pthreads is on hold and seemingly being replaced by Parallel. So I have stopped all efforts on pthreads and am trying to migrate code over to Parallel.

My working pthreads code is creates a new Worker class to create a MySQL PDO connection, which is then used, as well as a Volatile class which receives an array of data, and within my run() function, a specific process to do something with that array of data.

The PHP script overall then initially loads a very large XML file (200+ MB), and creates a pool for 4 threads (only 4 vCPUs available), and for that pool sends individual arrays of data which it got from the XML file. So relatively straight forward.

I am trying to understand how to replicate this with Parallel.

I don't see anything related to the amount of threads or cores. 

Is a Channel like a Worker from pthreads? What would the pool be? Or is this really needing to be done an entirely different way?

**Comment by awderh** [comment]
Parallel mostly provides a framework for implementing threads. It seems that pThreads provided some tooling as well.

Here, a "Worker" can be considered a "Runtime". You can make a Worker class, and just have it use a `Runtime`

I'd recommend you check out the tests asap, and start doing some basic tests using scratch. It's honestly the best way to learn it. What you'll figure, is that Parallel is using a different "way" of multi-threading/processing, one that involves communication via "messages".

As for tooling, Worker, WorkerPool, etc... You may end up having to create those yourself.

**Comment by TechnagyDev** [comment]
Thank you for your response AWDerh. I appreciate it. I'll do some more digging on this. It makes sense to move to this since pthreads is no longer supported.

**Comment by krakjoe** [comment]
Issues are reserved for bugs.
