### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by devqm** [krakjoe/parallel#156]
Compilation failed in php8

**Comment by Azhovan** [comment]
why compilation in php8? won't be supported in php8 natively?

**Comment by dktapps** [comment]
Not that I know of.

**Comment by paveldvorak5** [comment]
I'd like PHP 8 support too

**Comment by krakjoe** [comment]
Will be included in next release ...

**Comment by tobiastromm** [comment]
@krakjoe, how are you?

PHP 8 is now available for Windows, https://windows.php.net/download/.

Any ideia when parallel will be available here https://windows.php.net/downloads/pecl/releases/parallel/ with PHP 8 support?

Thank You.

**Comment by ghost** [comment]
> 
> 
> Will be included in next release ...

And when will that be?

**Comment by NolikTop** [comment]
> Will be included in next release ...

when next release?

**Comment by samuelgfeller** [comment]
Was it released in the meantime? I couldn't find anything above 7.4

**Comment by walterpadua** [comment]
Was it released in the meantime? I couldn't find anything above 7.4 ²
