### ISSUE TITLE
A very strange behaviour on PHP 7.4 with OpCache enabled

### ISSUE THREAD

**Issue by Encritary** [krakjoe/parallel#157]
That's an error I get inside a Runtime.

```TypeError: Return value of somenamespace\TaskCompleteMessage::done() must be an instance of gc_enable, instance of somenamespace\TaskCompleteMessage returned" (EXCEPTION) in "src/somenamespace/TaskCompleteMessage.php"```

**Comment by krakjoe** [comment]
I cannot investigate without reproducing code.

**Comment by Encritary** [comment]
I don't know how to reproduce it as it's happening randomly and not so often
iirc it doesn't happen on 7.3, only on 7.4

The problem is similar to the one that was in #112

**Comment by krakjoe** [comment]
Support for 7 is dropped, if the issue persists with PHP 8, please open a new issue.
