### ISSUE TITLE
Unable to load library inspite of the dll being inside of ext folder

### ISSUE THREAD

**Issue by slushpuppy** [krakjoe/parallel#158]
Warning: PHP Startup: Unable to load dynamic library 'parallel' (tried: c:\php\ext\parallel (The specified module could not be found.), c:\php\ext\php_parallel.dll (The specified module could not be found.)) in Unknown on line 0

How can I debu8ug this?

**Comment by slushpuppy** [comment]
Using strace:

--- Process 14980 loaded C:\php\libsodium.dll at 00007ff818460000
--- Process 14980 loaded C:\Windows\System32\cryptbase.dll at 00007ff8667b0000
--- Process 14980 loaded C:\php\ext\php_sqlite3.dll at 00007ff858570000
--- Process 14980 loaded C:\php\libsqlite3.dll at 00007fffd9fa0000
--- Process 14980 loaded C:\php\ext\php_tidy.dll at 00007ff8077c0000
--- Process 14980 loaded C:\php\ext\php_xmlrpc.dll at 00007ff819eb0000
--- Process 14980 loaded C:\php\ext\php_xsl.dll at 00007ff80d5e0000
--- Process 14980 loaded C:\php\ext\php_parallel.dll at 00007ff819d90000
--- Process 14980 unloaded DLL at 00007ff819d90000
PHP Warning:  PHP Startup: Unable to load dynamic library 'parallel' (tried: c:\php\ext\parallel (The specified module could not be found.), c:\php\ext\php_parallel.dll (The specified module could not be found.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'parallel' (tried: c:\php\ext\parallel (The specified module could not be found.), c:\php\ext\php_parallel.dll (The specified module could not be found.)) in Unknown on line 0
--- Process 14980 loaded C:\Windows\System32\SHCore.dll at 00007ff867bd0000

C:\php>php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'parallel' (tried: c:\php\ext\parallel (The specified module could not be found.), c:\php\ext\php_parallel.dll (The specified module could not be found.)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'parallel' (tried: c:\php\ext\parallel (The specified module could not be found.), c:\php\ext\php_parallel.dll (The specified module could not be found.)) in Unknown on line 0
PHP 7.4.11 (cli) (built: Sep 29 2020 13:18:06) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by krakjoe** [comment]
The pthreads dll (*not php_pthreads.dll*) also needs to be in PATH.
