### ISSUE TITLE
parallel\run() doesn't work inside an instance method of a class with a property assigned to $this

### ISSUE THREAD

**Issue by adriancuadrado** [krakjoe/parallel#161]
OS: Windows 10 64 bits  
PHP Version:
```
PHP 7.4.12 (cli) (built: Oct 27 2020 17:18:47) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
```
Parallel version: [1.1.4-7.4](https://windows.php.net/downloads/pecl/releases/parallel/1.1.4/php_parallel-1.1.4-7.4-ts-vc15-x64.zip)

I posted this [**in StackOverflow**](https://stackoverflow.com/questions/64784545/why-parallel-run-doesnt-work-inside-an-instance-method-of-a-class-with-a-prop), but since I think it is an actual bug, I repost it here.

Copy and paste:

> This code doesn't work:
> 
> ```php
> <?php
> 
> use parallel\Channel;
> 
> class MyClass {
>     private $x;
>     public function __construct() {
>         $this->x = $this;
>         $f = function () {};
>         $ch = new Channel();
>         parallel\run(function (Channel $ch) {
>             echo "X";
>             $ch->recv();
>             echo "Y";
>         }, [$ch]);
>         echo "A";
>         $ch->send($f);
>         echo "B";
>     }
> }
> 
> new MyClass();
> ```
> 
> More specifically, it prints "AX" but it should print "AXYB". The problem seems to be with `$ch->send($f)`, because as soon as I change it to send anything else (For instance, `$ch->send('Hello')`) it just works. According to [the PHP documentation][1] (see the section _**Closures over Channels**_) there shouldn't be any problems sending closures over channels.
> 
> I made some research and apparently, it only fails to print "AXYB" when I add `$this->x = $this`. If I remove that line and stop assigning `$this` to `$this->x` then it works wonders, but I need to be able to call `parallel\run()` from inside an instance method and when I do the same problem keeps happening. The question is, **Why doesn't this code print the correct output?**
> 
> Any help would be appreciated. Thanks in advance.
> 

  [1]: https://www.php.net/manual/en/class.parallel-channel.php

**Comment by DragK** [comment]
Hi, try `$this->x = clone $this;`. It works for me but it is a workaround. Nevertheless, why you assign reference to self to self property?

**Comment by adriancuadrado** [comment]
@DragK

> Hi, try $this->x = clone $this;. It works for me but it is a workaround. Nevertheless, why you assign reference to self to self property?

I don't, Doctrine does. More specifically, here: https://github.com/doctrine/dbal/blob/32f96b171efc785ea5168ebde9397ee430fca62e/lib/Doctrine/DBAL/Connection.php#L215  
and here: https://github.com/doctrine/dbal/blob/32f96b171efc785ea5168ebde9397ee430fca62e/lib/Doctrine/DBAL/Query/Expression/ExpressionBuilder.php#L39  
It's a circular dependency: In the Connection constructor:
```
$this->_expr = new Query\Expression\ExpressionBuilder($this);
```
And in the ExpressionBuilder constructor:
```
$this->connection = $connection;
```
I can't change the source code of Doctrine, so your solution doesn't work for me 😕
