### ISSUE TITLE
希望增加一个发送指针的方法，可以让线程之间共享指定的变量

### ISSUE THREAD

**Issue by dignfei** [krakjoe/parallel#165]
parallel\Channel::send 发送变量时，会复制2份。比如一个数组占用500M内存，使用一次 parallel\Channel::send后，查看进程占用的内存，发现占用了1500M，太浪费内存了。

希望增加一个方法 parallel\Channel::send2，发送变量时，只发送变量的指针，这样 线程之间就可以同时读写这个变量，不需要拷贝一份，浪费内存，浪费性能

**Comment by tsoftware-org** [comment]
PHP多线程就是鸡肋，要是增加原生多线程功能，还能再战10年

**Comment by sj-i** [comment]
It's by philosophy.

https://www.php.net/manual/ja/philosophy.parallel.php
> Do not communicate by sharing memory; instead, share memory by communicating.
