### ISSUE TITLE
set_exception_handler or set_error_handler is void

### ISSUE THREAD

**Issue by fengahan** [krakjoe/parallel#166]
Why do you have to set set_exception_handler and set_error_handler for each rruntime ->run() to take effect

**Comment by WyriHaximus** [comment]
Because you're running in a different thread that needs it's own error handler as it's a fresh clone of the processes you're spawning it from so you have to set it for each run.

**Comment by fengahan** [comment]
I think this is a bad implementation and I might need to encapsulate /parallel/ Run to get what I want

**Comment by WyriHaximus** [comment]
@fengahan FYI Been putting this together to take care of `set_error_handler` and `signals` for me: https://github.com/WyriHaximus/php-parallel-runtime . Might also be of interest for you. Also how are you using `set_exception_handler`?
