### ISSUE TITLE
Mongodb connection not close

### ISSUE THREAD

**Issue by Blount** [krakjoe/parallel#167]
Hello,
When I open connection in parallel task to a Mongodb Server, this connection seem not close when process ended.
I see in /proc/PID/fd that accumulate file name "socket:[xxxxxx]".
After some execution time, I get this error : "failed to open stream: Too many open files "

Mongodb library has no method to force close connection.
I need to restart the main process to "purge" connections.

**Comment by dercoder** [comment]
The MongoDB Team is working on a solution:
https://github.com/mongodb/mongo-php-library/issues/756
