### ISSUE TITLE
Can't load module with php-fpm 7.4

### ISSUE THREAD

**Issue by gsanon** [krakjoe/parallel#168]
Hi,

I am trying to use Parallel 1.1.4 with php-fpm 7.4 on Ubuntu 20.04.1. I've recompiled php with --enable-maintainer-zts option and then followed your INSTALL.md. Everything looks fine, I restart php-fpm and try your Hello World... doesn't work. I try `php-fpm7.4 -m` to check modules and I get the following warning : 

`[29-Dec-2020 23:23:53] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library '/etc/php7/lib/php/extensions/debug-zts-20190902/parallel.so' (tried: /etc/php7/lib/php/extensions/debug-zts-20190902/parallel.so (/etc/php7/lib/php/extensions/debug-zts-20190902/parallel.so: undefined symbol: core_globals_offset)`

Do you have an idea of what is happening here ?

Thx

**Comment by dotfry** [comment]
parallel works only in cli mode. fpm didnt supported

**Comment by krakjoe** [comment]
> [29-Dec-2020 23:23:53] NOTICE: PHP message: PHP Warning: PHP Startup: Unable to load dynamic library '/etc/php7/lib/php/extensions/debug-zts-20190902/parallel.so' (tried: /etc/php7/lib/php/extensions/debug-zts-20190902/parallel.so (/etc/php7/lib/php/extensions/debug-zts-20190902/parallel.so: undefined symbol: core_globals_offset)

That is a non zts binary trying to load a zts dso.
