### ISSUE TITLE
Maximum execution time of 30 seconds exceeded occured when using parallel.

### ISSUE THREAD

**Issue by anustro** [krakjoe/parallel#171]
I'm trying parallel extension to fetch data from two datasource, but the php-fpm error log record amount information about the execution timeout error. I can ensure that the execution time was less than 1s.

**Comment by anustro** [comment]
PHP version:PHP 7.4.14 (cli) (built: Jan 25 2021 11:43:58) ( ZTS )

**Comment by anustro** [comment]
When error_reporting is set to 0, the error didn't appear.

**Comment by krakjoe** [comment]
Setup your execution time limit in the runtime in the normal way.
