### ISSUE TITLE
Opcache preload?

### ISSUE THREAD

**Issue by smathersDT** [krakjoe/parallel#172]
Was wondering if anyone has got this working with php's new opcache preload feature.

I've been using this (used the older pthreads as well) on production for awhile now with no issues. I decided to try preload and everything blew up. Every time a thread finished a segfault would follow.

Ubuntu 20.04 LTS
PHP 7.4.7
using the latest code you have

**Comment by dktapps** [comment]
I don't think parallel is at fault here. I've also seen a similar problem on my pthreads fork. Does it by any chance look like #146 ?

**Comment by realFlowControl** [comment]
Hey @smathersPersonal,
sorry for taking so long to respond. Can you reproduce this with PHP 8 as well?
In the linked issue #146 I wrote a [comment](https://github.com/krakjoe/parallel/issues/146#issuecomment-2109962949) that I am not able to reproduce with PHP 8.

**Comment by smathersDT** [comment]
Thank anyways, but we can close this out now, I've since moved to multi-process / coroutine methods.
