### ISSUE TITLE
ERR_CONNECTION_RESET

### ISSUE THREAD

**Issue by Mystiik** [krakjoe/parallel#173]
Hi everyone,

I followed the documentation from [php.net](https://www.php.net/manual/en/parallel.setup.php) and [this repo](https://github.com/krakjoe/parallel/blob/develop/INSTALL.md), installed the prebuilt binaries from PECL and launched your README.md php code via WampServer 3.2.4 and php 7.4.3.
This resulted in a ERR_CONNECTION_RESET.
I'm on Windows 10 x64, my wamp has OpCache enabled.

The same page call work well with a basic echo "Hello World"; and doesn't result in a connection reset.

Interessing fact, it works perfectly on CLI.

Thanks in advance for your help.

**Comment by ttodua** [comment]
Have you ever been able to sort it out? same issues here.
https://stackoverflow.com/questions/57800012/how-to-install-new-php-parallel-7-2-on-windows-and-maybe-wampserver/67241103#67241103

**Comment by Mystiik** [comment]
Well, parallel is using multithreading, i read that WAMP isn't compatible with this kind of stuff.
In fact, parallel is built to work on CLI as i understood.
