### ISSUE TITLE
run() should always return a Future

### ISSUE THREAD

**Issue by dktapps** [krakjoe/parallel#174]
Right now it's impossible to check if a task with a void result is done, or to cancel it, because run() returns null if the closure doesn't return anything.

This change:
- allows more functionality
- reduces code complexity in check.c
- makes \parallel\run() static-analysis-friendly

**Comment by krakjoe** [comment]
A task that you *need* to monitor should not be void.

I'm just not seeing the motivation here, and I don't think I will, so closing this.
