### ISSUE TITLE
Execute class methods in parallel

### ISSUE THREAD

**Issue by capsandiego** [krakjoe/parallel#175]
This is not an issue. Just a request for clarifications.
I was trying to execute some class method in a multi-thread fashion with Parallel. 
I am aware of limitations of what we can pass as Closure arguments inside parallel\Run() (i.e. _arguments must not contain internal objects_) what I didn't understand if there is any workaround for this. 
Take this little example which, of course, doesn't work:

```
class A 
{
    public $one = 1;
    
    public function getOne()
    {
        return $this->one;
    }
}


class B
{
    public function executeParallel()
    {
        $task = function($o)
        {
            echo $o->getOne();
        };

        $runtime    = new Runtime();
        $future     = $runtime->run($task, [new A()]);
        $runtime->close();
    }
}

$b = new B();
$b->executeParallel();
```
Even if it's the same class and not two, I can't pass $this into the Closure.
Is there any workaround for this? 
Many thanks!!

**Comment by WyriHaximus** [comment]
This isn't advised as Parallel copies the classes over and doesn't copy any changes back. Instead, you should pass what's needed in the thread and have a worker class that does the execution. Not trying to plug, but have a read through of the readme at https://github.com/reactphp-parallel/worker-pool that describes that pattern. The more you keep your main thread and worker threads clean from ties with each other the better.
