### ISSUE TITLE
Tests base/030 base/037 functional/007 fail or timeout on AWS Linux on 7.3 & 7.4, release & develop branches

### ISSUE THREAD

**Issue by Sarke** [krakjoe/parallel#176]
I've been trying to build this in Docker and it builds fine locally but when I run the build on hub.docker.com it times out mostly or fails on those tests.

https://hub.docker.com/repository/registry-1.docker.io/sarkedev/php-parallel/builds/7597a28c-f39a-485a-8de7-efcf284e4491
https://hub.docker.com/repository/registry-1.docker.io/sarkedev/php-parallel/builds/8c432dca-e856-46f4-b75a-7b6fba0c864b

They use AWS Linux ec2, so I set up my own AWS Linux ec2 and was able to replicate the problem consistently.  The relevant tests are:

```
TEST 28/126 [tests/base/030.phpt]
========DIFF========
005+ 
006+  ** ERROR: process timed out **
========DONE========
```
```
TEST 35/126 [tests/base/037.phpt]
========DIFF========
007+ 
008+  ** ERROR: process timed out **
========DONE========
```
```
TEST 119/126 [tests/functional/007.phpt]
========DIFF========
002+ php: ../nptl/pthread_mutex_lock.c:433: __pthread_mutex_lock_full: Assertion `INTERNAL_SYSCALL_ERRNO (e, __err) != ESRCH || !robust' failed.
003+ Aborted (core dumped)
004+ 
005+ Termsig=6
========DONE========
```

I wonder if it might be that the ec2 instances' are small and the vCPU is throttled, but that's just a guess.

Full build log for the ones run on my instance:

[docker-aws-7.4-release.txt](https://github.com/krakjoe/parallel/files/6099972/docker-aws-7.4-release.txt)
[docker-aws-7.4-develop.txt](https://github.com/krakjoe/parallel/files/6099973/docker-aws-7.4-develop.txt)

**Comment by Sarke** [comment]
Of note is that when building on the alpine image, the tests don't time out but go for 4 hours until they are killed by docker hub.

https://hub.docker.com/repository/registry-1.docker.io/sarkedev/php-parallel/builds/67e95a19-1f07-4e21-a5cd-edc52217a517

**Comment by Sarke** [comment]
Also, it builds fine for 8.0 on the develop branch.

The reason I am guessing a throttle or race condition is because once in a while the tests will pass.  But like I said, just a guess.  I'll launch a faster instance tomorrow to test.

**Comment by Sarke** [comment]
It does test fine on the larger `t3.xlarge`, everything else being the same.

**Comment by krakjoe** [comment]
Support for 7 has been dropped in develop branch.
