### ISSUE TITLE
XAMPP PHP 7.4.11 + parallel

### ISSUE THREAD

**Issue by boomsya** [krakjoe/parallel#177]
hi
I try to run sample parallel code on XAMPP with PHP 7.4.11
But i have some problems. After calling
```
<?php
$runtime = new \parallel\Runtime();
```
Apache crashed:
```
Имя сбойного приложения: httpd.exe, версия: 2.4.46.0, метка времени: 0x5f292f9c
Имя сбойного модуля: php7apache2_4.dll, версия: 7.4.11.0, метка времени: 0x5f733497
Код исключения: 0xc0000005
Смещение ошибки: 0x0000000000002cd6
Идентификатор сбойного процесса: 0x27a8
Время запуска сбойного приложения: 0x01d71a95f69fe0a2
Путь сбойного приложения: C:\xampp\apache\bin\httpd.exe
Путь сбойного модуля: C:\xampp\php\php7apache2_4.dll
Идентификатор отчета: f0f4ca44-0331-4e64-8677-bc223126abf5
```

used parallel: php_parallel-1.1.4-7.4-ts-vc15-x64.zip
used xampp: xampp-windows-x64-7.4.11-0-VC15-installer.exe
php.ini:
```
....
extension=php_parallel.dll
....
```
file `pthreadVC2.dll` copied to `C:\xampp\apache\bin`
file `php_parallel.dll` copied to `C:\xampp\php\ext`

maybe someone known whats wrong?

**Comment by krakjoe** [comment]
The output buffer of apache is likely the cause.

You shouldn't write the output from the background in a webserver, there is no way to make this safe.
