### ISSUE TITLE
ERROR: `/tmp/pear/temp/parallel/configure --with-php-config=/usr/bin/php-config' failed

### ISSUE THREAD

**Issue by chiqui3d** [krakjoe/parallel#178]
Sometimes PHP is incredibly complicated I don't understand why it is not in the core . Based on the installation steps of https://github.com/krakjoe/parallel/blob/develop/INSTALL.md

` sudo pecl install parallel`

checking for ZTS... configure: error: parallel requires ZTS, please use PHP with ZTS enabled
ERROR: `/tmp/pear/temp/parallel/configure --with-php-config=/usr/bin/php-config' failed

**Comment by chiqui3d** [comment]
I see I need ZTS, no idea what that is. What a disappointment. What you have to do to install a simple extension. I'm going to Node.js.

**Comment by dktapps** [comment]
imagine a world where threading in PHP is easy to use and doesn't have lots of weird limitations.

... did you succeed? Yeah, me neither.

Be glad that you stopped here and didn't venture any further. PHP threading is a nightmare.
