### ISSUE TITLE
How to change bootstrap file if previously called?

### ISSUE THREAD

**Issue by harryqt** [krakjoe/parallel#181]
**autoload.php**

```php
class Example {
    public static function ping() {
        return 'pong';
    }
}
```

**autoload2.php**

```php
class Example {
    public static function ping() {
        return 'bong';
    }
}
```

**run.php**

```php
\bootstrap(__DIR__ . '/autoload.php');
\parallel\run(function() {
    var_dump(Example::ping());
});

\parallel\bootstrap(__DIR__ . '/autoload2.php');
\parallel\run(function() {
    var_dump(Example::ping());
});
```

I wants to see `pong` and `bong`
But [functional api](https://www.php.net/manual/en/parallel.bootstrap.php) won't let me do this, is there any way to achieve this without using `Runtime` api?

**Comment by WyriHaximus** [comment]
But why would you want to do that? If you have the composer autoloader available you could use any class you wanted. Not sure what the advantage of having two autoloaders is here

**Comment by dktapps** [comment]
Sounds like an [XY problem](https://xyproblem.info) to me.

**Comment by harryqt** [comment]
Okay, fine. 😅
