### ISSUE TITLE
How to compile the extension for Windows?

### ISSUE THREAD

**Issue by harryqt** [krakjoe/parallel#182]
The [Windows PECL](https://windows.php.net/downloads/pecl/releases/parallel/) directory does not contain the extension for PHP 8.0, so I am trying to compile it from source.

```
configure --disable-all --enable-cli --with-parallel=shared
```

**Log**:
```
......
......
Enabling extension ext\json
Checking for pthread.h ...  <not found>
Checking for pthread.h ...  <not found>
WARNING: parallel not enabled; pthread libraries and headers not found

Enabling extension ext\pcre
Enabling extension ext\reflection
.....
.....
```

As you can see, configure script can not find `pthread.h` 

My question is where to find the required pthreads files and where to put it?

**Comment by TheTechsTech** [comment]
you might want to look at [.appveyor.yml](https://github.com/krakjoe/parallel/blob/develop/.appveyor.yml)

It has a section pointing to https://windows.php.net/downloads/pecl/deps/

**Comment by harryqt** [comment]
Ah perfect. Thank you so much.

````
configure --disable-all --enable-cli --with-parallel=shared --with-extra-libs=C:\php-sdk\phpdev\vs16\x64\pthreads\lib --with-extra-includes=C:\php-sdk\phpdev\vs16\x64\pthreads\include
````
