### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by jkroonza** [krakjoe/parallel#183]
Is there anything in the pipeline?

**Comment by WyriHaximus** [comment]
Yes, Joe has been updating this extension some days ago to be PHP 8 only in the next release.

**Comment by juanantoniomosquera** [comment]
Hello, i installed php 8.0.6 with ZTS and compile parallel... but:

Uncaught Error: Class "parallel\Runtime" not found in ...

**Comment by jkroonza** [comment]
@juanantoniomosquera as per @WyriHaximus PHP 8 support will only be in the next release.

PR at https://github.com/krakjoe/parallel/pull/190 does raise some concern for me regarding backwards compatibility, looks like the next release might be only PHP 8 support, no longer 7.X.  Not ideal ... but not unmanageable.

**Comment by juanantoniomosquera** [comment]
but i tried php 7.* and compiling error: ONLY PHP 8.*, i dont understand... 

question: What version of php do I install for the latest version of parallel?

**Comment by jkroonza** [comment]
1.1.4 works on PHP 7.X, if you want PHP 8 you need master.  What I don't know is if master will work on 7.X, or if there is some fundamental change/difference between the two that prevents a common codebase.

**Comment by juanantoniomosquera** [comment]
I have installed develop, it has been installed well, shouldn't it work with php 8?

**Comment by jkroonza** [comment]
Perhaps you're missing development headers from PHP 8 or something, or it's including also-installed PHP 7 headers.  I don't know.

**Comment by jkroonza** [comment]
Any chance of getting an update on this?  We've got some code that's reliant on this and we're starting to phase out PHP7 otherwise ...

**Comment by krakjoe** [comment]
It's coming #250
