### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by numelion** [krakjoe/parallel#184]
[https://github.com/krakjoe/parallel/blob/develop/INSTALL.md](https://github.com/krakjoe/parallel/blob/develop/INSTALL.md)
`Requirements: PHP 7.2+`

$ php -v
`PHP 7.2.34-18+0~20210223.60+debian9~1.gbpb21322 (cli) (built: Feb 23 2021 16:47:53) ( NTS )`
...
$ ./configure --enable-parallel
`checking PHP version... configure: error: parallel requires PHP 8.0+`

???

**Comment by WyriHaximus** [comment]
In recent weeks the minimum has been raised to `8`+ on the default branch, but that hasn't been released yet. Also looks like you're running the NTS version of PHP, you need ZTS for this extension.
