### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by LinuXperia** [krakjoe/parallel#185]
Hi.

I am getting this Build Errors here on my Ubuntu 20.04 LTS Machine
when trying to compile the Parallel extension together with the PHP source code from github and checked out version 8.0

> php-src/ext/parallel/src/check.c:139:15: error: ‘zend_arg_info’ {aka ‘struct _zend_arg_info’} has no member named ‘pass_by_reference’
>   139 |         if (it->pass_by_reference) {
>       |               ^~
> php-src/ext/parallel/src/check.c:165:15: error: ‘zend_arg_info’ {aka ‘struct _zend_arg_info’} has no member named ‘pass_by_reference’
>   165 |         if (it->pass_by_reference) {

> php-src/ext/parallel/src/scheduler.c:77:5: error: implicit declaration of function ‘zend_disable_function’; did you mean ‘zend_disable_functions’? [-Werror=implicit-function-declaration]
>    77 |     zend_disable_function(ZEND_STRL("setlocale"));
>       |     ^~~~~~~~~~~~~~~~~~~~~
>       |     zend_disable_functions
> 
> php-src/ext/parallel/src/scheduler.c: In function ‘php_parallel_scheduler_push’:
> php-src/ext/parallel/src/scheduler.c:502:68: error: passing argument 1 of ‘zend_get_closure_method_def’ from incompatible pointer type [-Werror=incompatible-pointer-types]
>   502 |     const zend_function    *function = zend_get_closure_method_def(closure);
>       |                                                                    ^~~~~~~
>       |                                                                    |
>       |                                                                    zval * {aka struct _zval_struct *}

`php-src/ext/parallel/src/scheduler.c: In function ‘php_parallel_scheduler_setup’:
php-src/ext/parallel/src/scheduler.c:77:5: warning: implicit declaration of function ‘zend_disable_function’; did you mean ‘zend_disable_functions’? [-Wimplicit-function-declaration]
   77 |     zend_disable_function(ZEND_STRL("setlocale"));
      |     ^~~~~~~~~~~~~~~~~~~~~
      |     zend_disable_functions

php-src/ext/parallel/src/scheduler.c: In function ‘php_parallel_scheduler_push’:
php-src/ext/parallel/src/scheduler.c:502:68: warning: passing argument 1 of ‘zend_get_closure_method_def’ from incompatible pointer type [-Wincompatible-pointer-types]
  502 |     const zend_function    *function = zend_get_closure_method_def(closure);
      |                                                                    ^~~~~~~
      |                                                                    |
      |                                                                    zval * {aka struct _zval_struct *}
In file included from php-src/ext/parallel/src/parallel.h:38,
                 from php-src/ext/parallel/src/scheduler.c:21:
php-src/Zend/zend_closures.h:38:31: note: expected ‘zend_object *’ {aka ‘struct _zend_object *’} but argument is of type ‘zval *’ {aka ‘struct _zval_struct *’}
   38 | ZEND_API const zend_function *zend_get_closure_method_def(zend_object *obj);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~

php-src/ext/parallel/src/copy.c:34:1: warning: missing initializer for field ‘table’ of ‘struct <anonymous>’ [-Wmissing-field-initializers]
   34 | } php_parallel_copy_strings = {PTHREAD_MUTEX_INITIALIZER};
      | ^
php-src/ext/parallel/src/copy.c:33:21: note: ‘table’ declared here
   33 |     HashTable       table;
      |                     ^~~~~

php-src/ext/parallel/src/check.c: In function ‘php_parallel_check_arginfo’:
php-src/ext/parallel/src/check.c:129:44: warning: implicit declaration of function ‘ZEND_TYPE_CODE’; did you mean ‘ZEND_TYPE_CE’? [-Wimplicit-function-declaration]
  129 |         if (ZEND_TYPE_IS_SET(it->type) && (ZEND_TYPE_CODE(it->type) == IS_OBJECT || ZEND_TYPE_IS_CLASS(it->type))) {
      |                                            ^~~~~~~~~~~~~~
      |                                            ZEND_TYPE_CE
php-src/ext/parallel/src/check.c:129:85: warning: implicit declaration of function ‘ZEND_TYPE_IS_CLASS’; did you mean ‘ZEND_TYPE_HAS_CLASS’? [-Wimplicit-function-declaration]
  129 |         if (ZEND_TYPE_IS_SET(it->type) && (ZEND_TYPE_CODE(it->type) == IS_OBJECT || ZEND_TYPE_IS_CLASS(it->type))) {
      |                                                                                     ^~~~~~~~~~~~~~~~~~
      |                                                                                     ZEND_TYPE_HAS_CLASS
php-src/ext/parallel/src/check.c:139:15: error: ‘zend_arg_info’ {aka ‘struct _zend_arg_info’} has no member named ‘pass_by_reference’
  139 |         if (it->pass_by_reference) {
      |               ^~
php-src/ext/parallel/src/check.c:165:15: error: ‘zend_arg_info’ {aka ‘struct _zend_arg_info’} has no member named ‘pass_by_reference’
  165 |         if (it->pass_by_reference) {
      |               ^~

php-src/ext/parallel/src/check.c:538:13: warning: implicit declaration of function ‘ZEND_TYPE_IS_CE’; did you mean ‘ZEND_TYPE_IS_SET’? [-Wimplicit-function-declaration]
  538 |         if (ZEND_TYPE_IS_CE(info->type)) {
      |             ^~~~~~~~~~~~~~~
      |             ZEND_TYPE_IS_SET
`

with the additional config flags "--enable-parallel-coverage --enable-parallel-dev"
the Build Errors are:

`php-src/ext/parallel/src/scheduler.c: In function ‘php_parallel_scheduler_setup’:
php-src/ext/parallel/src/scheduler.c:77:5: error: implicit declaration of function ‘zend_disable_function’; did you mean ‘zend_disable_functions’? [-Werror=implicit-function-declaration]
   77 |     zend_disable_function(ZEND_STRL("setlocale"));
      |     ^~~~~~~~~~~~~~~~~~~~~
      |     zend_disable_functions

php-src/ext/parallel/src/scheduler.c: In function ‘php_parallel_scheduler_push’:
php-src/ext/parallel/src/scheduler.c:502:68: error: passing argument 1 of ‘zend_get_closure_method_def’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  502 |     const zend_function    *function = zend_get_closure_method_def(closure);
      |                                                                    ^~~~~~~
      |                                                                    |
      |                                                                    zval * {aka struct _zval_struct *}
In file included from php-src/ext/parallel/src/parallel.h:38,
                 from php-src/ext/parallel/src/scheduler.c:21:
php-src/Zend/zend_closures.h:38:31: note: expected ‘zend_object *’ {aka ‘struct _zend_object *’} but argument is of type ‘zval *’ {aka ‘struct _zval_struct *’}
   38 | ZEND_API const zend_function *zend_get_closure_method_def(zend_object *obj);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:1366: ext/parallel/src/scheduler.lo] Error 1
make: *** Waiting for unfinished jobs....
php-src/ext/parallel/src/copy.c:34:1: error: missing initializer for field ‘table’ of ‘struct <anonymous>’ [-Werror=missing-field-initializers]
   34 | } php_parallel_copy_strings = {PTHREAD_MUTEX_INITIALIZER};
      | ^
php-src/ext/parallel/src/copy.c:33:21: note: ‘table’ declared here
   33 |     HashTable       table;
      |                     ^~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:1370: ext/parallel/src/copy.lo] Error 1`

**Comment by krakjoe** [comment]
Looks like release branch, use develop branch.

**Comment by LinuXperia** [comment]
Hi Joe.
Thanks for your fast Reply.

> Looks like release branch, use develop branch.

Yes i used release branch.
Checked out now the develop branch of parallel and tryed to compile it again

With the additional configure flags "--enable-parallel-coverage --enable-parallel-dev" it still failed to compile
Without the additional configure flags above i finally got it to compile.

Thank you very much.
Wish you a great Weekend.
Cheers
