### ISSUE TITLE
Running on localhost

### ISSUE THREAD

**Issue by ttodua** [krakjoe/parallel#186]
Tried everything (as described [here](https://stackoverflow.com/questions/57800012/) ) but still it ends with "ERR_CONNECTION_RESET".

Any solutions to make it work on wamp-server? 

(btw, I saw similar [issue here](https://github.com/krakjoe/parallel/issues/173), but it does not have any insights and was closed)

**Comment by harryqt** [comment]
Just a small reminder that Parallel extension only works in PHP CLI.

**Comment by krakjoe** [comment]
This is a configuration issue, not a bug, so closing this.
