### ISSUE TITLE
Example of multiple execution

### ISSUE THREAD

**Issue by ttodua** [krakjoe/parallel#187]
I was unable to find the clear example, how to find the multiple functions in parallel.
For example, 

```
function smth($num){
  echo $num; sleep( rand(1,3) );
}
```

say, i want to execute 10 times (with different $num inputs) in parallel, so each function should not wait another.

With the given example you have on readme and either in php.net's future's manuals, I see only 1 parallel executions and couldnt find how to do with batch functions.
thanks

**Comment by DragK** [comment]
You must pass callback to `\parallel\Runtime:run`. Nothing more. So, you can just write 
```php
for ($i = 0; $i <= 10; $i++) {
 \parallel\Runtime:run(function(int $i): void {
  smth($i);
 }
}
```
Each smth now doesn't has to wait

**Comment by ttodua** [comment]
thanks!
