### ISSUE TITLE
Test FAIL parallel auto globals [tests/base/042.phpt]

### ISSUE THREAD

**Issue by gleb-shchavlev** [krakjoe/parallel#19]
Hello!

FAIL parallel auto globals [tests/base/042.phpt] test fail after:
```
$ make test
```

[php_test_results_20190327_1242.txt](https://github.com/krakjoe/parallel/files/3012516/php_test_results_20190327_1242.txt)

**Comment by krakjoe** [comment]
Your configuration breaks the test, presumably a template based off php.ini-development, which inexplicably does not register ENV:

    variables_order => GPCS => GPCS

I've fixed the test to force an expected variables_order, rest assured, nothing is actually broken ;)
