### ISSUE TITLE
PHP 8 build for Windows?

### ISSUE THREAD

**Issue by ghost** [krakjoe/parallel#192]
At the link provided in the installation document, there's only a version for PHP7.4.x, but not for PHP 8. When there will be one for PHP8?

Br, Miika

**Comment by sclubricants** [comment]
I'm wondering the same. It would be nice to have one to test with even if its not stable yet.

**Comment by ttodua** [comment]
@krakjoe Just didn't want to open a separate topic for this, but can you also comment [in this thread](https://www.reddit.com/r/PHP/comments/no7abs/differences_among_asynchronous_php_libraries/)?

**Comment by nelolka** [comment]
I've compiled it for you
[Download](https://drive.google.com/file/d/1s9GgwJ4SnDZ_nZzXF3ESYK-Z2sDlvUZP/view?usp=sharing)

**Comment by cmb69** [comment]
Building Windows binaries for PECL requires a compatible release; the latest released version is not yet compatible with PHP 8.0, see #201.

**Comment by cmb69** [comment]
I'm closing this per my comment above. If a new parallel version will be released, and no DLLs for PHP 8.0 would be built, please open a new ticket, or ping me.

**Comment by cmb69** [comment]
You can get latest snapshots builds from [AppVeyor](https://ci.appveyor.com/project/krakjoe/parallel), e.g. https://ci.appveyor.com/project/krakjoe/parallel/builds/41409316/job/k7sc57oy6djwtnfj/artifacts. See https://github.com/krakjoe/parallel/blob/develop/.appveyor.yml on how they are built.
