### ISSUE TITLE
Any examples of how to use the functionality for/within classes?

### ISSUE THREAD

**Issue by ttodua** [krakjoe/parallel#193]
I've been trying to do the following:
`
$myClass = MyClass();
\parallel\run( function() use($myClass){  $myClass->RunMyLongTask();  } );`

but it throws:
`Uncaught parallel\Runtime\Error\IllegalVariable: illegal variable (bla\MyClass) named class in static scope of function in..`

neither this worked:
`\parallel\run( function(){  MyClass()->RunMyLongTask();  } );`  (saying it can't find `MyClass`, as that scope cant even see any namespaces from my app at all)

later, found that [references/objects can't be passed](https://www.php.net/manual/en/parallel-runtime.run.php#refsect1-parallel-runtime.run-argv-characteristics) as argument. I am not too deep in the subject, so made me a bit surprised, how that can be, as all other langs (node.js, etc etc) has asynchronous functionalities with full abilities to fire whatever you want.

So, any wat to fire `RunMyLongTask()` with parallel? what is approach in such cases?  

____
(btw, you might offer to use `parallel\run` inside functions itself i.e. inside `RunMyLongTask()` wherever I make curl or whatever, line-by-line, but that is not possible to go into the details of the functions, as that function calls other classes&functions. So, we have to wrap the whole function to be called in async. astounding that this simple thing seems impossible).

**Comment by WyriHaximus** [comment]
Have you tried:

```php
$myClass = MyClass();
\parallel\run(function($myClass){
    $myClass->RunMyLongTask();
}, [$myClass]);
```

**Comment by ttodua** [comment]
> Have you tried:
> 
> ```
> $myClass = MyClass();
> \parallel\run(function($myClass){
>     $myClass->RunMyLongTask();
> }, [$myClass]);
> ```

Thanks for response. I got now: `Fatal error: Uncaught parallel\Runtime\Error\IllegalParameter: illegal parameter (smth\MyClass) passed to task at argument 1 in ...`. So, typically, is this expected? I really wanted to make that work.  Is that because the "specific characteristics" does not comply with docs (described on that link?).  If so, does this mean, it's impossible to work with parallel with methods/calls from classes?

**Comment by WyriHaximus** [comment]
That's how I literally use Parallel all the time. Just release the `new` keyword was missing in that example. But otherwise it should work fine, unless you have any non-userland classes or resources is `MyClass`.

**Comment by ttodua** [comment]
For example, I can't even make this to work.

```
<?php

class Class_1{
	public $parent;

	public function sample1(){
		$args = [$this->parent, 123];
		$func =function($arg1, $arg2){
			var_dump($arg1);
                        //$arg1->sample2($arg2);
			call_user_func( [$arg1, 'sample2'],  $arg2);
		};
		\parallel\run($func, $args);
	}
}


class Class_2{

	public function sample2($num){
		var_dump("hello world from sample2: $num");
	}

}

$class2= new Class_2();

$class1= new Class_1();
$class1->parent=$class2;
$class1->sample1();
```

error :  
`call_user_func() expects parameter 1 to be a valid callback, class 'parallel\Runtime\Type\Unavailable' does not have a method 'sample2' `

(moreover, in some cases,  i tried to dump out the class (using  `var_dump($arg1) `) inside callback, which causes such result: https://i.imgur.com/Aram5mO.png
