### ISSUE TITLE
How i checked if parallel installed?

### ISSUE THREAD

**Issue by juanantoniomosquera** [krakjoe/parallel#194]
I have a problem... parallel was compiled... i follow instructions with php 8.0.6 but... not work

Fatal error: Uncaught Error: Class "parallel\Runtime" not found

how i checked??

**Comment by ziaratban** [comment]
Hi @juanantoniomosquera
You can use the `get_loaded_extensions()` function to check for `parallel` installation.

```php
if(in_array('parallel',get_loaded_extensions())){
   #parallel extension is installed
}
```
But for compilation you have to set two parameters : `--enable-zts` and `--enable-parallel`
And before compiling you have to move the parallel project into the php `ext` source folder.
```
git clone https://github.com/krakjoe/parallel.git
mv -f parallel php-8.0.6/ext/parallel
cd php-8.0.6/ext/parallel
git submodule update --init 

```

**Comment by CViniciusSDias** [comment]
The command `php -m` shows you the installed and enabled extensions.

**Comment by cmb69** [comment]
Looks like this ticket can be closed now.
