### ISSUE TITLE
Docker image with ZTS & parallel for PHP-8

### ISSUE THREAD

**Issue by ttodua** [krakjoe/parallel#195]
Would be nice if you submitted a basic docker image on dockerhub, so we (who use docker) could use that. At this moment, we are struggling to find old articles (which were still written for php 7.x versions) about how to build zts & parallel.  And those articles doesn't work to do same with PHP-8 & apache 2.4 . Have spent a day but still couldnt make it (I mean, I couldnt make apache to work when I install official[ zts images ](https://hub.docker.com/_/php) as zts/apache versions are separated and I couldnt find image where they are together. )

Would be nice if you make a sample dockerfile.

**Comment by maxgalbu** [comment]
I don't think you want to use parallel outside cli... what's the use with apache? You can use docker compose to combine multiple docker images

**Comment by ttodua** [comment]
Thanks for reply. no, why to neglect apache? the extension has typical use-cases in user GUI app too (executing some things in parallel). why not :)
btw, i forgot to close issue, I was able to build custom image ( here is: https://puvox.software/blog/docker-php-8-zts-apache-swoole-parallel/ )
