### ISSUE TITLE
[Future] value() method not working correctly.

### ISSUE THREAD

**Issue by ziaratban** [krakjoe/parallel#196]
Hi.

How i can handle this code?

```php
<?php
$f = \parallel\run(function(){
    1/0;
});
sleep(1);

echo 'OK'.PHP_EOL;

$f->Value();

echo 'Does not run.';
```
**output**
```
OK

Fatal error: Uncaught DivisionByZeroError: Division by zero in test.php:3
Stack trace:
#0 {main}
  thrown in test.php on line 3
```

**Comment by TheTechsTech** [comment]
Why you think it's not working?

The function you executed produce just that error regardless in another thread or process.

What is your expected output, besides division by zero of which you are executing with **`1/0;`**?

**Comment by ziaratban** [comment]
`1/0` runs before `sleep(1)`. it's ok.
`echo 'OK'.PHP_EOL` runs. it's ok.
I think this line (`$f->Value()`) must be returns null and throw error.
`echo 'Does not run.'` not runs but must be run.

In fact i want to use the exception handling in parent thread.

**or my goal**
```php
<?php
$f = \parallel\run(function(){
    return 1/0;
});
sleep(1);

echo 'OK'.PHP_EOL;

if($f->HasError())
    echo "Error > " . $f->GetErrorMessage(); #any php error even syntax
else
    echo "Result > " . $f->Value();

echo 'does run.';
```

**Comment by TheTechsTech** [comment]
You need to read up on **PHP**, **general programming**, and use a **`try/catch`** block.

>if($f->HasError())
    echo "Error > " . $f->GetErrorMessage(); #any php error even syntax

Where are those methods coming from? 
You should look over the tests, after you learn some more, then you will understand how **bad** your example is.

**Comment by ziaratban** [comment]
> You need to read up on PHP, general programming, and use a try/catch block.

No. i want to use the **exception handling in parent thread** for child thread.

> Where are those methods coming from?

Exists in my brain. not exists in real world. this is **just an idea**.

>  You should look over the tests, after you learn some more, then you will understand how bad your example is.

A good example 🙂 :

**a.php**
```php
<?php
#a syntax error
$1a = 1;
```
**b.php**
```php
<?php
$f = \parallel\run(function(){
    #child thread
    require 'a.php';
});

#parent thread
```
How can i get the syntax error (from child thread) in the main thread?

**Comment by TheTechsTech** [comment]
I said, learn how to use **`try{} catch() {}`** blocks, or what they are used for.

**Comment by ziaratban** [comment]
In this case you can not use `try{} catch() {}`.

```php
<?php
$f = \parallel\run(function(){
    #child thread
    require 'a.php';
});

try{
    $f->Value(); #At this line, the PHP interpreter stops.
}
catch(\Exception $e){
    #doesn't run
}
```

**Comment by TheTechsTech** [comment]
You can't catch fatal errors like that, you create an handler first see https://www.php.net/manual/en/function.set-exception-handler.php

Review the tests certain errors not catch-able.

**Comment by ziaratban** [comment]
When we talk about the [`Future`](https://www.php.net/manual/en/class.parallel-future.php) feature, it is expected to provide better services.
You are right and I think I asked my questions badly. 

Thanks.
