### ISSUE TITLE
How this library works in multiple threads?

### ISSUE THREAD

**Issue by ttodua** [krakjoe/parallel#200]
I have looked through the official docs, but I couldn't find some layman descriptions about how this works. For example, when there are 4 total threads available in CPU, and we execute i.e. 99 closures  (with `\\paralel\\run`, and each closure needs more than 2 minute, up to i.e. 5 minutes), in what order they are executed? 

1) how Parallel decides on which thread the closure should be assigned? 

A) Will `parallel`  assign all closure (optimally aligned) over Threads (`T` means Thread-separate core):
Closure_1: T-I  
Closure_2: T-II
Closure_3: T-III
Closure_4: T-IV
Closure_5: T-I
Closure_6: T-II
... 
and so on
____
OR
____
B)  after filling up the 4 threads, it will wait start monitoring the first available (freed-up) thread to execute next closure?
____
OR
____
C) Parallel randomly chooses threads, and it might happen that it throws all executions to i.e. T1 & T3 threads, or whatever.

2) how in code/logic we can find how many threads are used by parallel at this moment, which threads are used or to command it which thread (T1/T2....) it should use?

Thanks in advance, it can be included in DOCS too.

**Comment by maxgalbu** [comment]
I think you're mixing concepts:
- a CPU has cores, not threads
- a process can have as many threads it wants (it's limited by the OS)

If your process calls `\parallel\run` 99 times in sequence, parallel will start 99 threads

If you need more control on how many threads are started, it gets more complicated than using `\parallel\run` and you need either:
- to wait for each thread to finish
- or a \parallel\Channel to communicate with threads and pass jobs or closures to each thread

**Comment by ttodua** [comment]
@maxgalbu  ah, my bad sorry, yes, i meant CORE (when I said "thread").
So, to name that way, as you said, if it fires i.e. 5 threads, and there is 4 Core available, how the threads will be assigned? Will it be  `2-1-1-1` or randomly, like `3-0-2-0` ?

**Comment by maxgalbu** [comment]
Which core handles which thread is not handled by this library, but by the OS: https://en.wikipedia.org/wiki/Thread_(computing)#Scheduling

You can probably assign a thread to a core... but the OS does this surely better than you and me and krakjoe too, I don't think any person would want to reinvent the wheel

**Comment by cmb69** [comment]
It seems this ticket can be closed now.
