### ISSUE TITLE
Why CPU core is same when executing in parallel

### ISSUE THREAD

**Issue by ttodua** [krakjoe/parallel#202]
I have tried the simple test:

```

.. function CpuNumber(){
	return (int) trim(str_ireplace('PSR','', shell_exec('ps -o psr -p '.getmypid() ) ) );
}
.. function ProcessNumber(){
	return  getmypid();
}


$func= function(){
	var_dump( "Cpu:".CpuNumber()  ."  Pid:".ProcessNumber() );
};

$func();
\parallel\run($func);
```

The process numbers are different, but the Core-number are always same. If i execute same with `shell_exec` it successfully executes the new process in new core (random core, depending available cores). 
Any ideas how to force it to execute in another core?  because if it's executed in same core, then it cant be 'truly parallel', but concurrent. Do I miss something?

**Comment by TheTechsTech** [comment]
> Any ideas how to force it to execute in another core? because if it's executed in same core, then it cant be 'truly parallel', but concurrent. Do I miss something?

That is an OS/hardware issue not under your direct control. If you launch/check any other application, you would find same **core** on most processes being executed. Not a **Parallel/PHP** thing, you are mixing two different things, with something concurrent. That deals more with a single thread interleaving code execution points, where the other could block. 

You might get a better understanding of **how extensions are launched and executed** by reading [PHP Internals Book - Learning the PHP lifecycle](https://www.phpinternalsbook.com/php7/extensions_design/php_lifecycle.html)

**Comment by ttodua** [comment]
@techno-express  many thanks for thorough answer. I am reading that source now! tnx.

__
p.s. just to add two words (source seems a bit more complex for layman), so I can't make a workaround to fire functions  with  `parallel` in other cores right?

**Comment by cmb69** [comment]
The parallel extension is about multi*threading*; there is only 1 process involved (unless you create further processes), but possibly multiple threads. The thread core assignment is done by the OS scheduler.

You may want to try (and adapt) the following script to understand what's going on:
````.php
<?php

$func = function (int $no) {
	while (true) printf("%d: %d %d\n", $no, getmypid(), zend_thread_id());
};

\parallel\run($func, [1]);
\parallel\run($func, [2]);
\parallel\run($func, [3]);
````
All 3 threads are supposed to report the same PID, but different thread IDs. And quite likely, the threads will be executed on multiple cores.

**Comment by ttodua** [comment]
@cmb69 thanks for your answer! Actually, by the time I asked (and btw, till date) I was unable to find any good article where I could understand in detail how do php threads/processes work with relation to each other. From your comment as I understand, the php process can be one, but manage things across multiple threads. I'll test out your script. thanks
