### ISSUE TITLE
Memory leak while using Sync or Channel Or Runtime !

### ISSUE THREAD

**Issue by ziaratban** [krakjoe/parallel#209]
Hi
Memory is not cleared when unset the `sync` or close the `channel`.

**`Sync.php`**
```php
$pid = getmypid();

$arr = [];

echo 'Start : '.exec("ps -q $pid -o rss")." KB\n";

    for($i = 0; $i<100000; $i++)
        $arr[] = new Sync($i);

echo 'End : '.exec("ps -q $pid -o rss")." KB\n";

unset($arr);

while(true){
    echo exec("ps -q $pid -o rss")." KB\n";
    sleep(1);
}
```
output
```
Start : 23628 KB
End : 50036 KB
46976 KB
46976 KB
46976 KB
46976 KB
46976 KB
46976 KB
46976 KB
46976 KB
^C
```

**`Channel.php`**
```php
$pid = getmypid();

$arr = [];

echo 'Start : '.exec("ps -q $pid -o rss")." KB\n";

    for($i = 0; $i<100000; $i++){
        $arr[] = $c = new Channel(Channel::Infinite);
        $c->Send($i);
    }

echo 'End : '.exec("ps -q $pid -o rss")." KB\n";

foreach($arr as $ch)
    $ch->Close();

unset($arr);

while(true){
    echo exec("ps -q $pid -o rss")." KB\n";
    sleep(1);
}
```
output
```
Start : 23176 KB
End : 86096 KB
83328 KB
83328 KB
83328 KB
83328 KB
83328 KB
83328 KB
83328 KB
^C
```

The minimum process memory for php is 23M.
It is normal?

**Comment by strictboss** [comment]
Hi!
I also have some memory problems of my script. Script at start after "require('autoload.php')" takes ≈ 8MB.
I have created 400 Runtimes - ≈820 MB.
Every of them got closure with 2 seconds sleep and file_put_contents(..., FILE_APPEND) ≈ 826 MB.
I have collected all returned Futures into array, then wait all of them with $future->value() and killed all Runtimes, unset($futures), unset all variables, but process still takes ≈ 270 MB.
Using docker stats i see, that number of PIDs was 1, then 401, and then still 1.
I used gc_collect_cycles() function to clear meamory, but nothing helps and even after killing Runtimes, clearing all variables - script takes 270 MB of memory VS ≈8MB when start after require 'autoload.php'.

Maybe i do not understand something. Maybe php caches something for future and i can not clear that in code.

Thank you for your answer!

**Comment by ziaratban** [comment]
@krakjoe Can you make it your top priority?
Because my php process stops after a few days.

**Comment by krakjoe** [comment]
No.

Parallel is not being developed currently; It is no longer in my interest to continue to maintain parallel as it is no longer viable for inclusion into core.

Continuing to develop parallel as a third party extension is possible, however, it would need funding, and the level of funding I currently receive does not begin to approach the kind of compensation I require for that ongoing maintenance and development work.

**Comment by ziaratban** [comment]
> 
> 
> No.
> 
> Parallel is not being developed currently; It is no longer in my interest to continue to maintain parallel as it is no longer viable for inclusion into core.
> 
> Continuing to develop parallel as a third party extension is possible, however, it would need funding, and the level of funding I currently receive does not begin to approach the kind of compensation I require for that ongoing maintenance and development work.

Please see your email.(krakjoe@php.net)

**Comment by maxgalbu** [comment]
@krakjoe it would be in the best interest of this project to write something on the project's readme about your thoughts on the project. 
Knowing your ideas on the development of the project could make the difference in choosing to use the library or not.

**Comment by krakjoe** [comment]
Your measurements are wrong, the methodology is not correct.

Please don't open help requests disguised as bug reports, this is not the place to get help with code.
