### ISSUE TITLE
Channels

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/parallel#21]
We need bi-directional communication between threads ... we need channels ...

TODO:
  - [x] select - implemented in Group
  - [x] tests for edges
  - [x] ~~return false~~ throw when send()/recv() on closed
  - [ ] not sure if timeouts make sense on recv()/send()

Started at cf2c909a9e5ba8c8b9590c7eee3cecd31ccd5317

**Comment by WyriHaximus** [comment]
~~So let me get this right, send()/recv() assume both sides of the channel are calling the oppside method to exchange data since the channel is unbuffered? So the calls are blocking?~~ IMHO timeouts make sense on `recv()` so non-blocking communication is possible given there is no way to check if there is something in the buffered channel buffer.

**Comment by dktapps** [comment]
I've never been a fan of false returns on error cases. Just my two cents on 3).

**Comment by krakjoe** [comment]
@dktapps ack, we throw `\parallel\Channel\Closed` when performing operation on closed channel ...

**Comment by beberlei** [comment]
@krakjoe for select, could this be implemented using a "composite" channel?

```php
$select = new \parallel\Channel\Select();
$select->add(\parallel\Channel::make('http'));
$select->add(\parallel\Channel::make('other'));

foreach ($select->recv() as $channel => $data) {
    switch ($channel) {
        case 'http':
              // doo http
        case 'other':
             // handle other
    }
}
```

**Comment by trowski** [comment]
Something compatible with `stream_select` would be needed to be non-blocking.

**Comment by WyriHaximus** [comment]
> Something compatible with `stream_select` would be needed to be non-blocking.

That's what I'm hoping/aiming for. Already have it working for just the run method, but hoping channels will get a non-blocking way to check if there is a message in the buffer.

**Comment by krakjoe** [comment]
> Something compatible with stream_select would be needed to be non-blocking.

> but hoping channels will get a non-blocking way to check if there is a message in the buffer.

The select API's you are used too don't seem to fit here: Normally when you select for read/write, the select call returns when the socket is ready, but we can't do that, if an unbuffered channel is ready to send, we have to send the data while we retain a lock (same for recv - we have to recv immediately), because if we return to user land (having necessarily released the lock) to perform the write/read we are introducing a race condition on the state of the channel - you can't be sure that another thread isn't trying to write/read the channel ...

**Comment by ghost** [comment]
A timeout for `recv` is needed, so at least that we can perform a receive on the channel buffer without blocking the thread for too long. Select API would be very useful, but not possible due to the locking process you described, so at least we should be able to specify a timeout.

**Comment by krakjoe** [comment]
I came up with a select API for Channel and Future, in Events ...

**Comment by krakjoe** [comment]
Closing this in favour of discussing the remaining things in separate issues ...
