### ISSUE TITLE
cannot load extension XAMPP for Windows 8.0.11

### ISSUE THREAD

**Issue by dgiaffredagit** [krakjoe/parallel#222]
I installed xampp on my PC with windows10 , executed all the instruction reported in the php manual but cannot load the extension parallel.
Log error is:
PHP Warning:  PHP Startup: Unable to load dynamic library 'parallel' (tried: D:\\xampp7.4\\php\\ext\\parallel (Impossibile trovare il modulo specificato.), D:\\xampp7.4\\php\\ext\\php_parallel.dll (Impossibile trovare il modulo specificato.)) in Unknown on line 0
Cannot find any other support on the topic in the network
Thanks

**Comment by rahim3070** [comment]
I have face the same error.

**Comment by cmb69** [comment]
Are you using the appropriate variant of the [latest release](https://windows.php.net/downloads/pecl/releases/parallel/1.1.4/)? That needs to match your PHP version, and the architecture (x86/x64).

**Comment by cmb69** [comment]
No feedback for more than two weaks, so I'm closing this ticket.
