### ISSUE TITLE
phpize: command not found

### ISSUE THREAD

**Issue by rahim3070** [krakjoe/parallel#223]
What can I do on Windows 10 ?

**Comment by remicollet** [comment]
Install it

And obviously not enough information about your env.

**Comment by cmb69** [comment]
I need to document phpize builds on Windows, but you can build PECL extensions "in-tree", what is [already documented](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2#building_pecl_extensions).

However, I suggest to download a [pre-built binary package](https://windows.php.net/downloads/pecl/releases/parallel/).

**Comment by cmb69** [comment]
I'm closing this per my comment above. Discussion may continue in #222.

**Comment by cmb69** [comment]
FTR: there is now [some documentation about phpize builds on Windows](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2#building_pecl_extensions_with_phpize) available.
