### ISSUE TITLE
Differentiate between return void and return value in parallel closures

### ISSUE THREAD

**Issue by beberlei** [krakjoe/parallel#23]
```php
<?php
$channel = parallel\Channel::make('http');
$runtime = new \parallel\Runtime();

$runtime->run(function ($string) {
    if (!$string) {
        return;
    }

    $channel = \parallel\Channel::open('http');
    $channel->send(strlen($string));
});
```

Throws the error: `Uncaught Error: return on line 2 of entry point ignored by caller, caller must retain reference to Future`.

I think this should only happen if `return <value>` is used, notably `return null; return 0; return $value;`

Not sure if its possible to detect this but maybe the rules for the exception could be:

- don't throw exception if there are 0 return statements
- don't throw exception if there are $n return statements and all of them return a value
- don't throw exception if there are $n return statements and none of them return a value
- throw exception if there are $n return statements returning a value and $m returning no value.

This is a convenience that affects channel based code more than the "standard" use-case returning futures. In case of a channel used for communication, the return value becomes uninteresting to the caller.

**Comment by krakjoe** [comment]
The problem here is that you can't tell the difference (in opcodes) between `return;` and `return null;` ...

The only option we have then is to treat those two the same, which means a future could never have a (constant) `null` value ...

**Comment by krakjoe** [comment]
I got a better idea ...

d670d64eb36cb3e6ad81954af57d87db5f840a54

You can use `\parallel\Runtime::yield(false);` to return control without rescheduling the current task ...
