### ISSUE TITLE
ZEND_TYPE_HAS_CLASS php 8.1

### ISSUE THREAD

**Issue by mrkh995** [krakjoe/parallel#230]
/usr/bin/php: symbol lookup error: /usr/local/php81/lib/php/extensions/debug-zts-20210902/parallel.so: undefined symbol: ZEND_TYPE_HAS_CLASS

**Comment by mrkh995** [comment]
https://raw.githubusercontent.com/php/php-src/PHP-8.1/UPGRADING.INTERNALS

1. Internal API changes --> h

**Comment by cmb69** [comment]
PR #226 is supposed to fix that. Can you please check that?
