### ISSUE TITLE
Answer in issue #217 not working, plz help

### ISSUE THREAD

**Issue by dividerbeam** [krakjoe/parallel#232]
Answer in issue #217 not working, you closed  issue #231 early

**Comment by dividerbeam** [comment]
i add in events.c

ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(php_parallel_events_count_arginfo, 0, 0, IS_LONG, 0)
ZEND_END_ARG_INFO()
and
PHP_ME(Events, count,       php_parallel_events_count_arginfo, ZEND_ACC_PUBLIC)

but command "make" return errors: 


![image](https://user-images.githubusercontent.com/52495131/158802343-63f9d400-56fa-4a14-9224-65c2b264b85e.png)

**Comment by krakjoe** [comment]
Fixed in develop.
