### ISSUE TITLE
Fail "make test"

### ISSUE THREAD

**Issue by dividerbeam** [krakjoe/parallel#233]
`root@vc:/usr/src/parallel# make test

Build complete.
Don't forget to run 'make test'.

=====================================================================
PHP         : /usr/local/bin/php
PHP_SAPI    :
Warning: parallel\Channel::__toString() implemented without string return type in Unknown on line 0
cli
PHP_VERSION : 8.2.0-dev
ZEND_VERSION: 4.2.0-dev
PHP_OS      : Linux - Linux vc 5.13.19-3-pve #1 SMP PVE 5.13.19-7 (Thu, 20 Jan 2022 16:37:56 +0100) x86_64
INI actual  : /usr/src/parallel/tmp-php.ini
More .INIs  :
---------------------------------------------------------------------
PHP         : /usr/local/bin/php-cgi
PHP_SAPI    : cgi-fcgi
PHP_VERSION : 8.2.0-dev
ZEND_VERSION: 4.2.0-dev
PHP_OS      : Linux - Linux vc 5.13.19-3-pve #1 SMP PVE 5.13.19-7 (Thu, 20 Jan 2022 16:37:56 +0100) x86_64
INI actual  : /usr/src/parallel/tmp-php.ini
More .INIs  :
Warning: parallel\Channel::__toString() implemented without string return type in Unknown on line 0

---------------------------------------------------------------------
---------------------------------------------------------------------
PHP         : /usr/local/bin/phpdbg
PHP_SAPI    : phpdbg
PHP_VERSION : 8.2.0-dev
ZEND_VERSION: 4.2.0-dev
PHP_OS      : Linux - Linux vc 5.13.19-3-pve #1 SMP PVE 5.13.19-7 (Thu, 20 Jan 2022 16:37:56 +0100) x86_64
INI actual  : /usr/src/parallel/tmp-php.ini
More .INIs  :
Warning: parallel\Channel::__toString() implemented without string return type in Unknown on line 0

---------------------------------------------------------------------
CWD         : /usr/src/parallel
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2022-03-18 10:56:06
=====================================================================
FAIL Check basic parallel operation [tests/base/001.phpt]
FAIL Check parallel global scope [tests/base/002.phpt]
FAIL Check parallel return values [tests/base/003.phpt]
FAIL Check parallel closed [tests/base/004.phpt]
FAIL Check parallel ini [tests/base/005.phpt]
FAIL ZEND_DECLARE_CLASS [tests/base/008.phpt]
FAIL ZEND_DECLARE_ANON_CLASS [tests/base/009.phpt]
FAIL ZEND_DECLARE_INHERITED_CLASS [tests/base/010.phpt]
`

and all more tests are FAIL, help plz

![image](https://user-images.githubusercontent.com/52495131/158993079-867bc877-b714-485c-9e47-60f9d5d00edb.png)

**Comment by cmb69** [comment]
> PHP_VERSION : 8.2.0-dev

Without some fixes, the latest development version of parallel is not yet compatible with PHP 8.1, so it makes no sense to try with PHP 8.2.0-dev.

**Comment by dividerbeam** [comment]
> 

do i need 8.0.0 version?

**Comment by cmb69** [comment]
Yeah, PHP 8.0 should be supported already.
