### ISSUE TITLE
A potential race condition between waiting and notifying

### ISSUE THREAD

**Issue by ryancaicse** [krakjoe/parallel#234]
Hi, in the below code, it is possible for the thread to signal first (Line 271) and, later, the thread goes to the waiting site (Line 201) forever without signal notified anymore.

https://github.com/krakjoe/parallel/blob/360c667b7632a639a983f17c5d97b92cbe4f7c95/src/link.c#L247-L275

https://github.com/krakjoe/parallel/blob/360c667b7632a639a983f17c5d97b92cbe4f7c95/src/link.c#L174-L206

**Comment by ryancaicse** [comment]
@krakjoe  Could you take a look? Many thanks.

**Comment by krakjoe** [comment]
Racing does not look possible to me. 

These are unbuffered routines, and wait releases/reacquires the mutex atomically.

When the recv caller enters into recv, it will block until there is a writer waiting while the channel has not been closed. It then performs the copy while the sending side retains the mutex and signals the sender to continue.
