### ISSUE TITLE
Runtime error in PHP 8.1 (suggested fix provided)

### ISSUE THREAD

**Issue by steffstuff** [krakjoe/parallel#235]
In PHP 8.1, ZEND_TYPE_HAS_CLASS() has been renamed to ZEND_TYPE_IS_COMPLEX()

Produces runtime-error:
php: symbol lookup error: /usr/local/lib/php/extensions/no-debug-zts-20210902/parallel.so: undefined symbol: ZEND_TYPE_HAS_CLASS

Replacing ZEND_TYPE_HAS_CLASS with ZEND_TYPE_IS_COMPLEX in src/check.c solves the issue.

**Comment by cmb69** [comment]
There is already PR #226 which would fix this (and more PHP 8.1 related issues).
