### ISSUE TITLE
Not compatible with PHP 8.2

### ISSUE THREAD

**Issue by darkphase** [krakjoe/parallel#236]
Not Compiling on Windows giving;
scheduler.c(226): warning C4047: '=': 'HashTable *' differs in levels of indirection from 'HashTable **'

Both code tree are from git master

**Comment by cmb69** [comment]
Which version of parallel and which version of PHP did you use?

**Comment by darkphase** [comment]
They both are from latest code tree of respective git repos...
PHP  https://github.com/php/php-src **branch:master**
Parallel  https://github.com/krakjoe/parallel **branch:develop**

**Comment by cmb69** [comment]
Oh, that would basically be PHP 8.2; however, even PHP 8.1 is not properly supported yet (see e.g. #215).

**Comment by krakjoe** [comment]
Fixed in develop.
