### ISSUE TITLE
Unable to load module even if its in right directory

### ISSUE THREAD

**Issue by ElStefanos** [krakjoe/parallel#239]
> `PHP Warning:  PHP Startup: Unable to load dynamic library 'parallel' (tried: D:\Programs\ProgramFiles\xampp\php\ext\parallel (The specified module could not be found), D:\Programs\ProgramFiles\xampp\php\ext\php_parallel.dll (The specified module could not be found)) in Unknown on line 0
> 
> Warning: PHP Startup: Unable to load dynamic library 'parallel' (tried: D:\Programs\ProgramFiles\xampp\php\ext\parallel (The specified module could not be found), D:\Programs\ProgramFiles\xampp\php\ext\php_parallel.dll (The specified module could not be found)) in Unknown on line 0`

These are my paths:

`D:\Programs\ProgramFiles\xampp\php`
`D:\Programs\ProgramFiles\xampp\php\pthreadVC2`

Both in user and system variables.

Php version:

`PHP 8.1.1 (cli) (built: Dec 15 2021 10:31:43) (ZTS Visual C++ 2019 x64)`

extension_dir is set to right directory.

What did I do wrong? 
I followed the official PHP documentation.

Even saw some people copying the pthread to system32.

If this is because I'm using wrong parallel version can you please leave the link to the right one?

This is what I downloaded `php_parallel-0.8.1-7.1-ts-vc14-x64`

**Comment by ElStefanos** [comment]
Downgraded to php 7.4 no result

**Comment by ElStefanos** [comment]
Reinstalled php again. No errors now.
This is the version i installed.

`PHP 7.4.30 (cli) (built: Jun  7 2022 16:24:55) ( ZTS Visual C++ 2017 x64 )`

This is the link.
 https://windows.php.net/downloads/releases/php-7.4.30-Win32-vc15-x64.zip

**Comment by cmb69** [comment]
Yeah, you always need the extension DLL to be build against the appropriate PHP version (major and minor version must match; revision is irrelevant). So if you have PHP 8.1.1, you would need an ext/parallel build for 8.1. ext/parallel isn't compatible with PHP 8.1 yet.
