### ISSUE TITLE
Pass environment/context variables to runtime

### ISSUE THREAD

**Issue by beberlei** [krakjoe/parallel#24]
When you want to pass on environment information from the main thread to the parallel runtime, then this is currently only possible as arguments to `run()`. 

What if we could pass environment/context variables to the runtime? This would help for instrumentation (my use case) but in general any thing where the parent needs to pass more high level data.

```php
$parallel = new \parallel\Runtime();
$parallel->addEnvironment('FOO', 'BAR');
$parallel->run(function () { var_dump($_SERVER['FOO']); });
// string(3) "BAR"
```

Current workaround is `putenv()` with all its problems :-)

**Comment by krakjoe** [comment]
I can't see any advantage in that. 

In addition, I see one very big disadvantage: We definitely do not want to encourage people to think of the environment as per thread, it is not per thread it is per process. In exposing methods to manipulate the environment of a specific thread, we are communicating that each thread has it's own environment ... it really doesn't, nor can we give it it's own environment ....
