### ISSUE TITLE
Need to talk

### ISSUE THREAD

**Issue by ClosetGeek-Git** [krakjoe/parallel#241]
@krakjoe I've been playing with your extensions for over a decade, and rarely in PHP userspace. How do we get a hold of the core PHP team? I'm actually getting frustrated with how things are going. I was a script kid playing with sockets in PHP 3 and things have gone so far since then. You've already proven that PHP can handle threads. Twice now. This whole HTTP/FCGI thing is getting old. I was doing chats using Macromedia Flash 5 with XML sockets on PHP 4. Why do we always wind up in this same hole?

**Comment by ClosetMonkey** [comment]
Is it corporate pressure? Really.

**Comment by cmb69** [comment]
What are you talking about? If you want to make a proposal to include support for multithreading in php-src, do it at https://github.com/php/php-src/issues.

**Comment by ClosetMonkey** [comment]
Are you suggesting that will mater? call header() after an echo() and PHP will shit because it might break a 30 year old cgi script somewhere.

**Comment by ClosetMonkey** [comment]
Heres something cool and simple - make the master FCGI socket within php-cgi available to userspace once a script is executing.

**Comment by ClosetMonkey** [comment]
Theres so many ways that people can break things with that, yet there are frameworks that have been stretching PHP steams into all sorts of areas, such as amphp and ReactPHP.

**Comment by cmb69** [comment]
> Are you suggesting that will mater?

It certainly matters more than posting confusing issues to this repo.

**Comment by ClosetMonkey** [comment]
I'm looking for @krakjoe . And this isn't confusing. People have been hitting this ceiling for years now.

**Comment by cmb69** [comment]
See https://github.com/krakjoe/parallel/issues/201#issuecomment-892442141.

**Comment by ClosetMonkey** [comment]
A "thread" is something subjective once talking about fibers and coroutines. Both are useless without some sort of core event mechanism. You end up with a very fine grained procedure that can't do much more than run in it's own loop until it's done.

**Comment by ClosetMonkey** [comment]
eventfd for example, and it can get even lower than that. It's not that it can't be done. I'm not a hater.

**Comment by ClosetMonkey** [comment]
There are those who have the knowledge to do this. "How" isn't an issue. It's already been proven that it can be coded, maintained, and then have a crowd try to adopt it just to see that it can't go anywhere because of lack of support from the core team.

**Comment by ClosetMonkey** [comment]
I don't have an issue with @krakjoe . I have an issue with the greater PHP team and he has their ear. We are facing Web3 yet if you did a mass delete of "cgi" in the the PHP core it would leave it broken. We all know it's more than that.

**Comment by ClosetMonkey** [comment]
Facebook already had to fork because of this, and I'm pretty sure that Fibers came from the presence that Tecent created with Swoole Coroutines.

**Comment by ClosetMonkey** [comment]
`php_stream *stream  = php_stream_sock_open_from_socket(fcgi_fd, 1);` is all it would take to pass the fcgi socket into userspace. That one line of code could change the entire path of PHP.

**Comment by ClosetMonkey** [comment]
And that's not voodoo. FCGI is a very simple protocol. High schoolers can work with it, and not the type that win awards

**Comment by maxymajzr** [comment]
@ClosetMonkey wow, I never thought I'd read something like this, it's as if you read my mind and wrote what I always thought. When @krakjoe first published pthreads, I tried to reach out to the PHP core team but it was a moot effort - I'm not blaming them at all, but it's like you said - we have the how. We have capable maintainers. We have everything from the "let's execute this" part. I want this too. I need it. I don't want to use multiple languages in order to achieve simple parallel number calculation, and then get into "how the f**k do I deploy all of this and maintain it later" if I can use PHP to achieve it.

What needs to be done to have cool things in PHP core? Swoole exists. Hacklang exists with its generics. This extension exists with parallel execution. Heck, pthreads existed since what, 2012?

**Comment by ClosetMonkey** [comment]
@maxymajzr I'm not sure of your background but this isn't new with the PHP Team. Members long ago tried to maintain a GTK-PHP at the core level but they to got drowned out because of their INSANE desire to remain a CGI. This was something close to 20 years ago. Imagine if it would be now. It's  fu**** ing insanity, and not new insanity.

**Comment by ClosetMonkey** [comment]
Their own community can lift them into new places such as @krakjoe . They do the work for free, submit the code, and then crickets

**Comment by ClosetMonkey** [comment]
Meanwhile our more knowledgeable clients are like "wait what do you mean that's not possible"

**Comment by ClosetMonkey** [comment]
Once upon a time great men did great things by pounding stones against other stone and created an awesome thing they called "wheel". But it seems they don't want to put their down clubs and stone an concede other tools are available.

**Comment by ClosetMonkey** [comment]
And I'll be very insensitive when other might not be. How many man hours (im thinking in the tens of millions) are they disrupting and working against by refusing to listen.  People bank their livelihood and more and more often it's "that's not possible" and then "wait what...???"

**Comment by ClosetMonkey** [comment]
I'm not trolling. These are issues great enough to move so much. YouTube started as PHP. Yahoo Webmail Started as PHP. Like WT* is going on. FB. It's not a small list that switched because of deft ears. Maybe all they know is pounding sticks into stones and they wont let go.

**Comment by ClosetMonkey** [comment]
I'm from a time where I know that PHP written in Pearl. We do still exist.

**Comment by ClosetMonkey** [comment]
Death will come to me someday, but I'm hopping - maybe - i"ll be immortal. But I'm not young.

**Comment by ClosetMonkey** [comment]
I'll put myself out there, I'm a very old and unmovable mountain, who remembers when PHP was Pearl. And I remember the rumors of lawsuits, and saw the change. And as I saw the change, thanks Zend, PHP became into a nice C framework. But also, there are those who are either dishonest or gagged by court order.

**Comment by ClosetMonkey** [comment]
Because really, they are doing BAD AS* FUC*NG THINGS with JIT. But can't leave CGI. So stuck, so stateless. And so mum..

**Comment by ClosetMonkey** [comment]
Are they so gagged they cant give a nod?

**Comment by ClosetMonkey** [comment]
I think, and I can say very little because of lawsuit, that PHP is stuck. Just like their "history" page contradicts web archives. Thy are dead ducks from lawsuits they can even mention.

**Comment by ClosetMonkey** [comment]
so @cmb69 are you still willing to champion?

**Comment by ClosetMonkey** [comment]
@cmb69 meet me

**Comment by ClosetMonkey** [comment]
The platform I'm working on is a true datachannel, but such a thing can't possibly exist. No. It must xyz by CGI standards.

**Comment by ClosetMonkey** [comment]
Meet me

**Comment by ClosetMonkey** [comment]
Any fuc**ing one of you

**Comment by ClosetMonkey** [comment]
I dont really care

**Comment by ClosetMonkey** [comment]
Just like @krakjoe it wont ever matter

**Comment by ClosetMonkey** [comment]
I'm looking at your commits @cmb69  I think my blatter is about ti scream on you. Your pissed on and done NIgg@

**Comment by ClosetMonkey** [comment]
Fu*k CGI. This is is so retarded. And no I wont submit a PR. They're a dead duck. Stuck in CGI. TELL ME FUC8ING OTHERWISE

**Comment by ClosetMonkey** [comment]
I'm done/ Honestly. The best to all of your. Keep your CGI

**Comment by ClosetMonkey** [comment]
Maybe I"m not done. Fuck PHP. Trust me that will be something,
