### ISSUE TITLE
undefined symbol: ZEND_TYPE_HAS_CLASS

### ISSUE THREAD

**Issue by ahmeteminkocal** [krakjoe/parallel#242]
php: symbol lookup error: /opt/php/php8/lib/php/extensions/no-debug-zts-20210902/parallel.so: undefined symbol: ZEND_TYPE_HAS_CLASS
I constantly get this error. What could be the reason?
Currently Php 8.1.6 is installed.

**Comment by cmb69** [comment]
Duplicate of #235.
