### ISSUE TITLE
Can't spawn more than two threads & memory leak

### ISSUE THREAD

**Issue by ahmeteminkocal** [krakjoe/parallel#243]
Hello,
I cannot spawn more than 2 Threads. What could be the issue? I am using Php 8.1.6.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/10382507/187546641-2edeff88-a740-4df5-8b69-46a8f743c4ed.png">
<img width="302" alt="image" src="https://user-images.githubusercontent.com/10382507/187546736-999ab449-ee5c-42ce-919f-b9b5041023e4.png">

Edit 1:
Found the issue. When I use future it can't spawn more than two for some reason. How can I increase this limit?
<img width="210" alt="image" src="https://user-images.githubusercontent.com/10382507/187546996-bac8c85f-f62e-4450-84d3-09c8403efc17.png">

Edit 2:
Now it doesn't work again. So the previous result was totaly concidental.

Edit 3:
So looks like I need to send them to a different future. 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/10382507/187550264-59f18e12-d4a3-42ea-b4ca-2ffb54b01d90.png">
This way I can spawn as many threads as I want. But I can do that ONLY IF I define new Runtime(); each loop. If I use the same Runtime() it would stuck again.
Doing that this way also causes memory leaks. 1k threads costs around a gigabyte of ram. And there is no way to clear them out.

Edit 4:
I thought killing runtime would fix the memory leak. But doing so will result in zend heap error.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/10382507/187551877-384e13a9-d0ac-4c32-96f6-e185385bc418.png">
<img width="285" alt="image" src="https://user-images.githubusercontent.com/10382507/187551923-9c7a7071-1eb0-4ad1-ad73-4db92844ad57.png">

Edit 5:
It does kill some of the threads and it does resolve the memory leak problem. But it gives that error after some time.
If you disable zend memory using "export USE_ZEND_ALLOC=0", it gives out segmentation fault instead.

<img width="183" alt="image" src="https://user-images.githubusercontent.com/10382507/187552748-d2d24558-e638-4f2e-bda2-46e4f8812872.png">

**Comment by ghost** [comment]
I'm using this and spawning like 40 threads, each with their own future...  worked fine in php8.1.8, php8.2-rc and php8.3-dev
`<?php

namespace RPurinton\Transliterate;

require_once(__DIR__."/ConfigLoader.php");

class ThreadManager Extends ConfigLoader
{
        private $threads = null;
        private $functions = null;
        private $futures = null;

        function __construct()
        {
                parent::__construct();
                if($this->config["transliterate"]["StartDiscord"])
                {
                        $key = "DiscordClient";
                        $this->threads[$key] = new \parallel\Runtime(__DIR__ . "/DiscordClient.php");
                        $this->functions[$key] = function () { new DiscordClient; };
                        $this->futures[$key] = $this->threads[$key]->run($this->functions[$key]);
                }
                for($id=0;$id<$this->config["transliterate"]["InboxHandlers"];$id++)
                {
                        $key = "InboxHandler$id";
                        $this->threads[$key] = new \parallel\Runtime(__DIR__ . "/InboxHandler.php");
                        $this->functions[$key] = function () { new InboxHandler; };
                        $this->futures[$key] = $this->threads[$key]->run($this->functions[$key]);
                }
                for($id=0;$id<$this->config["transliterate"]["TranslateHandlers"];$id++)
                {
                        $key = "TranslateHandler$id";
                        $this->threads[$key] = new \parallel\Runtime(__DIR__ . "/TranslateHandler.php");
                        $this->functions[$key] = function () { new TranslateHandler; };
                        $this->futures[$key] = $this->threads[$key]->run($this->functions[$key]);
                }
                for($id=0;$id<$this->config["transliterate"]["GlueHandlers"];$id++)
                {
                        $key = "GlueHandler$id";
                        $this->threads[$key] = new \parallel\Runtime(__DIR__ . "/GlueHandler.php");
                        $this->functions[$key] = function () { new GlueHandler; };
                        $this->futures[$key] = $this->threads[$key]->run($this->functions[$key]);
                }
                while(true)
                {
                        sleep(5);
                        foreach($this->futures as $key => $future) if($future->done()) $this->futures[$key] = $this->threads[$key]->run($this->functions[$key]);
                }
        }

        function __destruct()
        {
                foreach($this->threads as $thread) $thread->kill();
        }
}
`

**Comment by ElStefanos** [comment]
This is how I did it.

```
                $future_id = 1;
                foreach ($job as $key => $value) {
                    $stamp = '[NOTIFICATION]['.strtoupper(date('D, d M Y H:i:s')).'] ';
                    
                    print("\033[34m".$stamp."Started ". $task .":".$key." with future future_".$future_id."\033[0m\n");
                    
                    $agv = array($value);
                    ${'future_'.$future_id} = ${$task}->run(function($path){
                        $stamp_error = '[ERROR]['.strtoupper(date('D, d M Y H:i:s')).'] ';
                        include 'directoryMap.php';
                        if (file_exists($path)) {
                            include_once $path;
                        } else {
                            print("\033[31m".$stamp_error."Could not start the thread... File does not exist in ". $path."\n exiting thread... \n\033[0m");
                            exit();
                        }
                    },$agv);
                    $future_id++;
                }
```

I have multi dimensional array but what you need is `$future_id` outside foreach loop. and `$future_id++` inside it. Name your future with `${'future_'.$future_id}`.


Here I have 3 never ending loops because I need this script to listen on few ports. Also having commandline and working web GUI.

![image_2022-09-29_210644342](https://user-images.githubusercontent.com/46761434/193120637-20ed832e-5b1c-4b2c-9d24-ff2dedf766ff.png)

As you can see here I am able to use CLI while also listening on ports.

![image_2022-09-29_211139958](https://user-images.githubusercontent.com/46761434/193121563-daf76b92-cbb0-4dc9-be07-bbb13ab8b1bd.png)

**Comment by cmb69** [comment]
> I am using Php 8.1.6.

AFAIK parallel is not yet compatible with PHP 8.1 ([it won't compile](https://github.com/krakjoe/parallel/issues/215) in the first place). Are you using a patched version?

**Comment by krakjoe** [comment]
The segfault isn't nice, but it's a result of using kill() ...

kill should be used as a last resort when you are forcing a shutdown of your program and don't care about the consequences.

Otherwise I don't think there's a bug here ... if I'm wrong about that and you can distill it to a reproducible case, please open another ticket.
