### ISSUE TITLE
PHP Warning:  parallel\Channel::__toString() implemented without string return type in Unknown on line 0

### ISSUE THREAD

**Issue by ghost** [krakjoe/parallel#244]
PHP Warning:  parallel\Channel::__toString() implemented without string return type in Unknown on line 0
PHP 8.3.0-dev (cli) (built: Sep 19 2022 23:07:45) (ZTS)
Copyright (c) The PHP Group
Zend Engine v4.3.0-dev, Copyright (c) Zend Technologies

**Comment by krakjoe** [comment]
Fixed in develop.
