### ISSUE TITLE
Drop Future::value(int $timeout) in favour of Events ?

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/parallel#26]
With the addition of Events API, I managed to drop a couple of methods from Future since it replaced Future::select.

I'd like to go further and drop the timeout variation of value from Future: It would be better to have fewer methods on Future, and it would be better to keep working with timeouts in Events only.

It's obviously a(nother) nasty BC break, but I care less about that right now than sticking to the mantra of having succinct API ...

Can anyone think of a use case that really requires a timeout on value that could not be supported by using the Events API ?

**Comment by krakjoe** [comment]
Since I hear no objections, I went ahead and removed the timeout variation ...

**Comment by WyriHaximus** [comment]
> Since I hear no objections, I went ahead and removed the timeout variation ...

Finally had some time and fun with events this morning and the `parallel\Events:setTimeout` is very useful for my use case. So no objections from my
