### ISSUE TITLE
Does parallel take advantage of multiple CPU cores?

### ISSUE THREAD

**Issue by ben833** [krakjoe/parallel#262]
My use case is to run a heartbeater with a long running queue-consumer script. This is more of a general question, though. Will parallel take advantage of extra CPU cores on the machine? Is there any way to tell it to run on another core, or tell it to run on the same core as the main PHP program?

Also, the github contributors page says that this should be run on PHP version >= 8, but the php.net documentation says that it can be run on PHP version >= 7.2. Which one is correct?

**Comment by cmb69** [comment]
> Will parallel take advantage of extra CPU cores on the machine?

That's up to the operating system; parallel supports multiple threads.



> Also, the github contributors page says that this should be run on PHP version >= 8, but the php.net documentation says that it can be run on PHP version >= 7.2.

The first version of parallel which had been released (0.8.0) required PHP ≥ 7.2.0. As of parallel 1.2.0, only PHP ≥ 8.0.0 is supported (the PHP manual should be updated in this regard).

**Comment by cmb69** [comment]
[Documentation has been updated](https://github.com/php/doc-en/commit/965de54e33dc648d8670403757b05282d8487be7).

**Comment by ben833** [comment]
Thank you!
