### ISSUE TITLE
PHP 8.1 or 8.2 releases for Windows

### ISSUE THREAD

**Issue by GajowyJ** [krakjoe/parallel#263]
Hi!
Could you please inform me if a release of parallel 1.2.1 for Windows users is available? On the official PECL download page (? - https://windows.php.net/downloads/pecl/releases/parallel/) it ends on 1.1.4 and PHP 7.4.

KR,
Gajowy

**Comment by cmb69** [comment]
See https://windows.php.net/#news-2022-10-17-1. You can download parallel 1.2.1 builds from https://github.com/krakjoe/parallel/actions/runs/3350381484, for now.

**Comment by Deus-nsf** [comment]
> 

I'm sorry to say that the builds generated for PHP 8.0 and 8.1 aren't available anymore, and I don't know how to compile them on a windows environment

![image](https://user-images.githubusercontent.com/13644590/232537780-cb943930-87af-44d5-acef-450eabe5770d.png)
