### ISSUE TITLE
Parallel version supporting PHP 8 for Windows?

### ISSUE THREAD

**Issue by moving-bits** [krakjoe/parallel#264]
I'm looking for a binary version of parallel supporting PHP 8 on Windows.

Parallel version 1.2 seems to support PHP 8, but binaries are not available for download on https://windows.php.net/downloads/pecl/releases/parallel/ yet.

I've seen the file offered for download in https://github.com/krakjoe/parallel/issues/201#issuecomment-863370854 (thanks @nelolka for providing it), but after integrating it PHP throws errors on startup, something like "Procedure entry point zend_parse_arg_bool_slow@@16 not found in php_parallel.dll" (manually translated). pthreadVC2.dll (taken from latest parallel 1.4 binary) is located in c:\windows\system32, which is covered by PATH env var.

Any ideas on how to get this running on Windows with PHP 8.1 / 8.2? Thanks.

**Comment by cmb69** [comment]
> Parallel version 1.2 seems to support PHP 8, but binaries are not available for download on https://windows.php.net/downloads/pecl/releases/parallel/ yet.

See https://windows.php.net/#news-2022-10-17-1.

> Any ideas on how to get this running on Windows with PHP 8.1 / 8.2?

You can use a build from https://github.com/cmb69/php-ftw/actions/runs/3971488657. There are variants like PECL had, and the pthread dependency is included.

**Comment by moving-bits** [comment]
> > Any ideas on how to get this running on Windows with PHP 8.1 / 8.2?
> 
> You can use a build from [cmb69/php-ftw/actions/runs/3971488657](https://github.com/cmb69/php-ftw/actions/runs/3971488657). There are variants like PECL had, and the pthread dependency is included.

Thanks @cmb69 for the pointer. But AFAICS this is for a lib called "uopz", not "parallel". I've checked all 130 runs, but did not find any build for "parallel". Have I missed something?

**Comment by cmb69** [comment]
> But AFAICS this is for a lib called "uopz", not "parallel".

Oops, sorry, I've mixed that up. I gave parallel a try: https://github.com/cmb69/php-ftw/actions/runs/3981017658. The 8.2 x86 build failed; I need to look at that. The others may be fine (not tested yet), but you need to manually download pthreads 2.11.0 from https://windows.php.net/downloads/pecl/deps/ (choose x64 or x86 as desired). IIRC, the PECL builds used pthreads 2.9.1.

**Comment by moving-bits** [comment]
@cmb69 
Did a quick test in my scenario (creating 20+ parts from a Musescore source file, taking advantage of today's multi core CPU) - works like a charm!
Thanks for taking the time to create the build for me. ❤️

**Comment by guilleCore1** [comment]
Hello, can you tell me how to configure to get parallel/pthreads working in php8 windows?

Thank you.

**Comment by nelolka** [comment]
in php 8 you don't need it, just use fibers

**Comment by nelolka** [comment]
@guilleCore1 
in php 8 you don't need it, just use fibers

**Comment by guilleCore1** [comment]
> @guilleCore1 in php 8 you don't need it, just use fibers

Hello,

The problem I have is that fiber has to wait for the process to finish to continue, I need it to execute the function and continue with the code.

**Comment by moving-bits** [comment]
> Hello, can you tell me how to configure to get parallel/pthreads working in php8 windows?

### Prerequisites / configuring PHP to support "parallel":

1. check if your PHP extension folder is configured correctly. On my system the following line is in `php.ini`:
  ```
  extension_dir = "c:/program files/php/ext"
  ```
2. Store `php_parallel.dll` in the configured extension folder
3. `pthreadVC2.dll` is located in `c:/windows/system32` folder on my system.
4. To let PHP know that you want to use parallel, put the following line into your php.ini and restart your webserver:
  ```
  extension=parallel
  ```

### Programming for "parallel":

Have a look at the [manual page for parallel](https://www.php.net/manual/de/parallel.run.php), at the example contributed by Thierry Kauffmann.

**Comment by guilleCore1** [comment]
> > Hello, can you tell me how to configure to get parallel/pthreads working in php8 windows?
> 
> ### Prerequisites / configuring PHP to support "parallel":
> 1. check if your PHP extension folder is configured correctly. On my system the following line is in `php.ini`:
> 
> ```
> extension_dir = "c:/program files/php/ext"
> ```
> 
> 2. Store `php_parallel.dll` in the configured extension folder
> 3. `pthreadVC2.dll` is located in `c:/windows/system32` folder on my system.
> 4. To let PHP know that you want to use parallel, put the following line into your php.ini and restart your webserver:
> 
> ```
> extension=parallel
> ```
> 
> ### Programming for "parallel":
> Have a look at the [manual page for parallel](https://www.php.net/manual/de/parallel.run.php), at the example contributed by Thierry Kauffmann.

Hello,
How do I download php_parallel.dll and pthreadVC2.dll from https://github.com/cmb69/php-ftw/actions/runs/3981017658/jobs/6824472159 or from where I have to download the files?

Thanks.

**Comment by moving-bits** [comment]
> Hello, How do I download php_parallel.dll and pthreadVC2.dll from [cmb69/php-ftw/actions/runs/3981017658/jobs/6824472159](https://github.com/cmb69/php-ftw/actions/runs/3981017658/jobs/6824472159) or from where I have to download the files?

I had used the link provided by @cmb69 with the link above, but the artifacts are expired meanwhile, so you may want to contact @cmb69 if he can rerun the task for you.

**Comment by guilleCore1** [comment]
@cmb69 , Please, can you relaunch the jobs to be able to download the artifacts? Thank you very much.
