### ISSUE TITLE
Can't Sync coexist with multiple instances?

### ISSUE THREAD

**Issue by allanghub** [krakjoe/parallel#268]
&lt;?php
$a = new \parallel\Sync;
$b = new \parallel\Sync;
?&gt;
Running the above program using parallel v1.1.4 under PHP 7.2 under Windows will report the following error:
Issue Signature:
Problem Event Name: APPCRASH
Application name: php.exe
Application Version: 7.2.11.0
Application timestamp: 5bbd5ec5
Fault module name: KERNELBASE.dll
Fault module version: 6.1.7601.17514
Fault module timestamp: 4ce7c78c
Exception code: c0000005
Abnormal offset: 000000000000a49d
OS version: 6.1.7601.2.1.0.274.10
Locale ID: 2052
Other information 1: 0cd3
Other information 2: 0cd3b3f224093b52830d0a6de9e8f983
Additional information 3: ce87
Other information 4: ce8768ba3907e6208b330167174cfc24

Can't Sync coexist with multiple instances?

**Comment by realFlowControl** [comment]
Hey @allanghub,

I do not have a windows machine to test this, on Linux this seem to not be an issue.
#205 seems related but got fixed, also there is a test creating multiple `\parallel\Sync` objects. Do you have a stack trace for me to see there the crash is happening?

**Comment by realFlowControl** [comment]
And I just see, that you are using PHP 7.2, `parallel` is meant to be used with PHP >= 8.0. Even if `parallel` might compile on PHP 7 it is not supported.

**Comment by cmb69** [comment]
> […] , `parallel` is meant to be used with PHP >= 8.0.

To clarify for others, this is about parallel >= 1.2.0. So go and upgrade! :)
