### ISSUE TITLE
Incorrect bootstrapping on PHP 8.1 and 8.2

### ISSUE THREAD

**Issue by CViniciusSDias** [krakjoe/parallel#269]
The bootstrap parameter doesn't seem to be being handled correctly.

If you use composer's autoload file, for example, you will receive **every** parameter in your closure as if it was an instace of `ComposerAutoloaderInit`.

Here is a reproduceable example: https://github.com/CViniciusSDias/parallel-error

PS.: If I change my `Dockerfile` from `FROM php:8.2-zts` to `FROM php:8.0-zts`, it works. With 8.1 I have the same error as with 8.2.

I included the vendor folder just to make it more complete, but feel free to delete it and run `composer dump`. That should not matter.

When you run `error.php`, you would expect to see "value" and "Main" as the output, but the actual output is as following:

> Fatal error: Uncaught TypeError: {closure}(): Argument #1 ($test) must be of type ParallelError\Test, ComposerAutoloaderInitca4473ffb2bf0736baa71dd698e7fe03 given in /app/error.php:11
Stack trace:
#0 [internal function]: {closure}(Object(ComposerAutoloaderInitca4473ffb2bf0736baa71dd698e7fe03))
#1 {main}
  thrown in /app/error.php on line 11

Let me know if any further detail is necessary.

**Comment by krakjoe** [comment]
Fixed in 0fe4bb8259b163737d122e018ca72d251f12c2ce
