### ISSUE TITLE
Channels send/recv with timeout ?

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/parallel#27]
In #21 I said that I wanted recv/send to have a timeout parameter ... I changed my mind, I think.

In go, timeouts are only handled by select {}, and in parallel they can be handled by Events in the same sort of way ... it seems superfluous to have API's that do the same thing ...

Can anyone think of a use case that could not be implemented with Events ?

/cc @everyone #26

**Comment by krakjoe** [comment]
Since I hear no arguments in favor, we're going to deal with timeouts in the event loop only ...

**Comment by derekbsnider** [comment]
Do you have an example of how to use events in place of a timeout on Channel::recv?

For example, if I'd like to have some code that runs through a collection of Channels, and checks them for input, I don't want the loop to hang on a Channel that has no input available, I want it to be able to move on to the next channel.
