### ISSUE TITLE
Windows binaries unavailable for 1.2.0 and 1.2.1

### ISSUE THREAD

**Issue by Deus-nsf** [krakjoe/parallel#271]
I just can't find them anywhere, is there a kind soul to build them?
This: https://windows.php.net/downloads/pecl/releases/parallel/ stops at 1.1.4

**Comment by ElCapitanSponge** [comment]
Any updates on the resolution of this issue? Would be great to be able to use parallel in php 8 on windows

**Comment by krakjoe** [comment]
@cmb69 :wave: what is the current state of windows builds, I have no idea what is going on ?

**Comment by cmb69** [comment]
The extension builds for Windows are catered to by https://github.com/php/php-windows-builder, and DLLs are avaiable from https://pecl.php.net/package/parallel.
