### ISSUE TITLE
On exit()  in Future cancelled()  and done() wont give true, but value() give  Segmentation fault

### ISSUE THREAD

**Issue by webrobot1** [krakjoe/parallel#278]
This code

```
<?php
use parallel\{Channel, Runtime, Future, Events, Events\Event, Events\Input};

$runtime = 	new Runtime();
$future = $runtime ->run
(
	function() 
	{
		exit();
	}
);



echo $future->done().'|';
echo $future->cancelled().'|';
#echo $future->value().'|';


exit('can work more');
```

I cant check what Future is exit status but if i will get value()  script will force exit. But if will not check exit - it can work more.

How i can check the exit status or how dint exit main thread if get Future value what execute exit

**Comment by realFlowControl** [comment]
Hey @webrobot1,

do not call `exit` in the thread closure. If you want to return a result from that thread, use `return $value;` instead. This `$value` will be returned by your call to `$future->value()`.

Hope I could help

**Comment by webrobot1** [comment]
> Hey @webrobot1,
> 
> do not call `exit` in the thread closure. If you want to return a result from that thread, use `return $value;` instead. This `$value` will be returned by your call to `$future->value()`.
> 
> Hope I could help

this exit can create automaticly, like some Exception or fatal error via code will execute.
exit it si only as example

**Comment by realFlowControl** [comment]
Regarding Exceptions and Fatals: the `value()` method will [rethrow `\Throwable` uncaught in the task](https://www.php.net/manual/de/parallel-future.value.php). So in order to guard against that, you need to wrap the `value()` call in a try/catch block:

```php
try {
    echo $future->value().'|';
} catch (Throwable $e) {
    var_dump($e);
}
```

**Comment by webrobot1** [comment]
> Regarding Exceptions and Fatals: the `value()` method will [rethrow `\Throwable` uncaught in the task](https://www.php.net/manual/de/parallel-future.value.php). So in order to guard against that, you need to wrap the `value()` call in a try/catch block:
> 
> ```
> try {
>     echo $future->value().'|';
> } catch (Throwable $e) {
>     var_dump($e);
> }
> ```

but fatal error or syntaxis error cant be catch

**Comment by webrobot1** [comment]
> value()

as i say - if parallel thread wil get fatal error (like a exit status in my example)  the main thread (owner)  cant get ->value() - if it try "Segmentation Fault"  will happen and it cant be catch as an your example

**Comment by realFlowControl** [comment]
Hey @webrobot1,

if your `catch`-block is typed with `\Throwable` (like in my example) it will also catch a `FatalError` like a "Call to undefined function ...". Btw.: I just tried and wrapping the call to `value()` in a try/catch block will catch a `\parallel\Future\Error\Foreign` exception that is being thrown when calling `exit()` in a task.

Hope this helps
