### ISSUE TITLE
How can I use parallel on Windows?

### ISSUE THREAD

**Issue by nicollassilva** [krakjoe/parallel#280]
Sorry if this is the thousandth time you've answered this, but actually reading all the issues I still have doubts about how to correctly install the extension for Windows.

I'm using **PHP 8.1.22 ZTS** and **Windows 10**, how do I install this on my machine?

Thanks for your response.

**Comment by Jeangowhy** [comment]
How to build paralle on Windows? How to solve pthread dependence?

**Comment by jasonccs** [comment]
How can I use parallel on Windows? #280

**Comment by krakjoe** [comment]
Sorry but this is not a bug, so closing this.

**Comment by cmb69** [comment]
Just for the record: Windows DLLs are available via https://pecl.php.net/package/parallel. How to install the extension is explained on https://www.php.net/manual/en/parallel.setup.php.
