### ISSUE TITLE
Arguments of tasks in parallel runtime

### ISSUE THREAD

**Issue by antoniogweb** [krakjoe/parallel#282]
In the documentation it's written that the arguments of a task can't contain internal objects. 

By internal objects do they mean instances of classes defined in the php core (such as DateTime)?

Are classes defined in a PHP extension considered as internal classes/objects?

There is a way to bypass this problem? For example is it possible to pass data from the main program to the parallel task using a channel?

Thanks!

**Comment by realFlowControl** [comment]
Hey there 👋 

> In the documentation it's written that the arguments of a task can't contain internal objects.

Correct, there is also bit [more detail here](https://www.php.net/manual/en/parallel-runtime.run.php#refsect1-parallel-runtime.run-object-characteristics). 

> By internal objects do they mean instances of classes defined in the php core (such as DateTime)?

Yes, `DateTime` is such a class.

> There is a way to bypass this problem? [..]

Not using a channel, but you could serialize the object and unserialize. In case of a `DateTime` you could not pass in the `DateTime` instance, but whatever you have called the constructor with and create the `DateTime` instance in the thread.

Hope this helps a bit.

**Comment by krakjoe** [comment]
I'm going to assume the question being answered that this issue is resolved.

**Comment by antoniogweb** [comment]
Hi, yes it is solved. Thanks!
Antonio

Il giorno sab 18 mag 2024 alle ore 19:38 Joe Watkins <
***@***.***> ha scritto:
