### ISSUE TITLE
Solution for fix "fatal error: 'ext/standard/php_mt_rand.h' file not found"

### ISSUE THREAD

**Issue by vovkapoc** [krakjoe/parallel#286]
In newer php version in compilation process parallel I see error:
```
/tmp/parallel-1.2.1/src/poll.c:23:10: fatal error: 'ext/standard/php_mt_rand.h' file not found
#include "ext/standard/php_mt_rand.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [src/poll.lo] Error 1
```

For fix this error replace string **ext/standard/php_mt_rand.h** to **ext/random/php_random.h** in file **src/poll.c**

After this modification parallel successfully compiled in any latest php versions! :-)

_**P.S. Developer, please fix this error for newer php versions!**_

**Comment by akotulu** [comment]
[PHP RFC: Random Extension 5.x](https://wiki.php.net/rfc/rng_extension) changes. Particular file was moved to different directory.

Change `src/poll.c` line
```
#include "ext/standard/php_mt_rand.h"
```
to
```
#include "ext/random/php_random.h"
```
