### ISSUE TITLE
Further life of this repository.

### ISSUE THREAD

**Issue by proilyxa** [krakjoe/parallel#290]
Further life of this repository.

Good afternoon It can be seen that tickets are still being created here, and some are even sending PRs. I don't mean to be rude, I did a little research on the twitter of the main developer of this package and it seems to me that he is no longer with us. Thanks to him for creating this extension!

Perhaps there are those who are ready to take on the further development of this project? It would be great to continue working with multi-threaded PHP!

**Comment by krakjoe** [comment]
I'm alive.

I cannot manage much more at the moment, I have granted @realFlowControl permissions to maintain in my absence.

Sorry it took so long.

**Comment by proilyxa** [comment]
@krakjoe Wow, I'm so glad you're okay! I wish you a lot of strength and good mood! The PHP community thanks you!

**Comment by SmetDenis** [comment]
@krakjoe That's great news! You've made my day!
Happy to know you are okay 😊

**Comment by krakjoe** [comment]
I've had a pretty good day working on parallel, solved a couple of ancient problems ...

I haven't written tests for most of it yet, they will come over the next week, and if I don't get too it, @realFlowControl can pick it up when he comes back from holiday and a release can follow shortly after that.

Now that other active contributors are involved I think we can close this as resolved.

Thanks for all kind words and actions from all directions :)
