### ISSUE TITLE
GitHub workflow depends on Docker Hub

### ISSUE THREAD

**Issue by flavioheleno** [krakjoe/parallel#297]
As seen in #293, #294, #295 and #296, the CI relies on docker images that should be available on https://hub.docker.com/u/parallelphp, which has not been updated for the past 2 years.

> #4 [parallel-release-8.0 internal] load metadata for docker.io/parallelphp/php-release-8.0:8.0.30
> #4 ERROR: docker.io/parallelphp/php-release-8.0:8.0.30: not found
failed to solve: parallelphp/php-release-8.0:8.0.30: docker.io/parallelphp/php-> release-8.0:8.0.30: not found

If accepted, I'd be more than happy to work on a PR to replace Docker Hub with GitHub Container Registry with automated pipeline to build and store the base images (`php-*`) and to replace accordingly on the workflow as to fix the current broken status.

**Comment by realFlowControl** [comment]
Hey @flavioheleno 👋 

I just recently got [permissions granted to maintain](https://github.com/krakjoe/parallel/issues/290#issuecomment-2105063545), though I do not have permission to push to https://hub.docker.com/u/parallelphp. I would totally be fine with moving the images to the GitHub Container Registry. In an ideal world a GitHub Action should build an push the images 😉 

That said (and if you like), you could start with a PR that creates the PHP 8.3 container and pushes them to the GHCR and uses them to run the tests on PHP 8.3 in GitHub Actions. If we have this, we could start migrating PHP 8.0 - 8.2 and setup a PHP-8.4 (current master) job as well.

What do you think?

**Comment by flavioheleno** [comment]
Hi @realFlowControl :)

it sounds like a great starting point, I'm gonna start working on it

**Comment by flavioheleno** [comment]
hey @realFlowControl two points I've bumped on while working on this:
1. I cannot just build and test PHP 8.3 without breaking everything else as the test relies on [docker/parallel.dockerfile](docker/parallel.dockerfile) and it points to either docker hub or ghcr, so I think the best way out is to also build PHP 8.0, 8.1 and 8.2, what do you think?
2. While fixing the previous point, I've found out that PHP 8.2.0RC5 is no longer available on [php.net/distributions](https://www.php.net/distributions), so I updated it to PHP 8.2.0 as to keep things as close to what they are right now without too much fuss, what do you think?

Ideally, once I'm done with this, I can go back to #293, #294, #295 and #296 and update accordingly.

**Comment by realFlowControl** [comment]
Let's try it 👍
