### ISSUE TITLE
Do you have a binary package for Windows PHP 8.2, version 8.3

### ISSUE THREAD

**Issue by jasonccs** [krakjoe/parallel#301]
Do you have a binary package for Windows PHP 8.2, version 8.3

**Comment by paulgao** [comment]
+1

**Comment by jasonccs** [comment]
这是来自QQ邮箱的假期自动回复邮件！
    您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，第一时间给您回复。

**Comment by testAccountDeltas** [comment]
Hello 
https://github.com/testAccountDeltas/build-PHP8-parallel/tree/main/php_parallel.dll

**Comment by realFlowControl** [comment]
Hey there,

Windows binaries are [distributed via PECL](https://pecl.php.net/package/parallel).
It takes a while (few hours) till PECL picks up and creates the DLLs after a new release was uploaded, but expect it to be there.
