### ISSUE TITLE
FrankenPHP: mutex not unlocked in `zend_bailout` case

### ISSUE THREAD

**Issue by realFlowControl** [krakjoe/parallel#313]
`parallel` replaces the `sapi_module.ub_write` function with a simple function that locks a mutex, calls whatever was in that function pointer before and upon return unlocks the mutex again. This hanging/freezing happens in the following situation:
- a thread does `echo`/`printf`/`...`
- parallel locks a mutex and calls `frankenphp_ub_write()`
- `go_ub_write()` returns an error for a closed connection (this is an assumption)
- FrankenPHP calls into `php_handle_aborted_connection()` https://github.com/dunglas/frankenphp/blob/ebdb2656b6d8af3e0e8aa96359b02dba013ab88c/frankenphp.c#L509
- `ignore_user_abort` is set to `false` (default) which will lead to a call to `zend_bailout()` in https://github.com/php/php-src/blob/70861c82df7ff944090a771cc40698d2cd7bd164/main/main.c#L2591
- the call will never return and the mutex wont be unlocked

The mutex around `echo`/`printf` is necessary to make them atomic from a PHP user land perspective. I'll have a look if I can detect a `zend_bailout()` somehow and release the mutex `parallel` holds.

Relates to:
- https://github.com/dunglas/frankenphp/issues/858#issuecomment-2175825212
- https://github.com/krakjoe/parallel/issues/308

**Comment by dunglas** [comment]
Thanks, I'll try to hack Static PHP CLI to see if this fixes this issue this afternoon.

**Comment by realFlowControl** [comment]
PR #314 will unlock the mutex in `RSHUTDOWN` and seems to solve the problem

**Comment by dunglas** [comment]
ok, let me know when there is a branch ready with all needed patches and I'll give it a try.

**Comment by realFlowControl** [comment]
You can try the `florian/deadlock-in-echo` branch from #314
