### ISSUE TITLE
Class names (Event class) conflict with pecl event extension

### ISSUE THREAD

**Issue by mesny** [krakjoe/parallel#320]
Hi, there is an class name conflict, between parallel and event extensions.

`/usr/bin/ld: ext/parallel/src/.libs/event.o: in function 'zim_Event___construct':
/img/phpsrc/php-8.3.10/ext/parallel/src/event.c:67: multiple definition of 'zim_Event___construct'; ext/event/php8/classes/.libs/event.o:/img/phpsrc/php-8.3.10/ext/event/php8/classes/event.c:218: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:150: libphp.la] Error 1
`

Used this configure command:
`./configure --disable-session --disable-cgi --disable-phpdbg \
  --enable-zts --enable-fpm --enable-sockets --enable-mysqlnd --enable-mbstring --enable-pcntl --enable-embed=shared \
  --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-shmop --enable-parallel \
  --with-zlib --with-zip --with-xsl --with-ffi --enable-phar --enable-soap \
  --with-curl --with-mysqli --with-openssl --with-sodium \
  --with-ldap --with-sqlite3 --with-pdo_mysql --with-pdo_sqlite \
  --enable-igbinary --enable-ds --with-amqp --with-gearman \
  --with-event-core --with-event-extra --with-event-openssl --enable-event-sockets \
  --enable-memcached --enable-memcached-json --enable-memcached-igbinary --disable-memcached-session
`

I am not aware of any reason to not use the event extension in ZTS builds (libevent supports pthreads).
I wondered is there any workaround for that?

Thanks very much for your work.

**Comment by cmb69** [comment]
The class names better should be soft-namespaced, like e.g.

https://github.com/krakjoe/parallel/blob/87e71d3c7b5a906bc4023d924c8cd36ab934e206/src/event.c#L85

**Comment by realFlowControl** [comment]
Hey @mesny,
#321 should fix that problem, I could not try it out yet, but I am slightly optimistic 😉 
I'll give it a try later and merge in case it actually fixes the problem.

**Comment by mesny** [comment]
Much appreciated!
