### ISSUE TITLE
Reusing cached Runtimes created by `\parallel\run` leads to inconsistent behaviours

### ISSUE THREAD

**Issue by pielonet** [krakjoe/parallel#322]
Hi,

I am facing an issue which I think is linked to the Runtime caching mechanism of php/parallel : 

The documentation for `\parallel\run` says : 

> If a \parallel\Runtime internally created and cached by a previous call to parallel\run() is idle, it will be used to execute the task. If no \parallel\Runtime is idle parallel will create and cache a \parallel\Runtime. 

A few days ago one of my scripts failed.

The first ten executions of `\parallel\run` - in  a row - went OK since ten new Runtimes had been created.
The eleventh execution failed with the following error : 

```
Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example10/Utils.php on line 4
```
What I understand is that the 11Th execution was using a cached Runtime which had kept the variables, Class and function scope it had gained in its first run. This lead to an error : Class "Utils" could not be declared twice.

As a workaround, I created each Runtime anew (using `new \parallel\Runtime();`) instead of using `\parallel\run`. This gave me the assurance that each new Runtime had a "fresh and clean" variable, functions and Class scope... And the error disappeared.

Kind regards,
Thierry

**Comment by pielonet** [comment]
The documentation for the functional API says : 

>  The functional API provides less control in exchange for the ability to make decisions for the programmer:
> 
>    all executing runtimes are bootstrapped identically

So I think the issue I faced is the expected behaviour. Am I right ?

Kind regards,
Thierry

**Comment by realFlowControl** [comment]
Hey @pielonet,

I tried to reproduce, but was not able so far. Can you make a small reproducer that shows this problem?

I can see the error you have seen when using `require()` instead of `require_once()`, but from what I see, you used `require_once()`. Another thing: you could try using the [`\parallel\bootstrap()` function](https://www.php.net/manual/de/parallel.bootstrap.php) and have this bootstrap some PHP code for you like this: 

```diff
+ \parallel\bootstrap('Utils.php');
  // Launch controller in a parallel thread
  $controller = \parallel\run(
      function(Channel $controller_channel, Channel $queue_channel, array $config): array {
-         require_once "Utils.php";
```

Does this help?

**Comment by pielonet** [comment]
@realFlowControl You're right the error only appeared when I was using `require "Utils.php"` instead of `require_once "Utils.php"`. I did that modification to fix the issue.

So when using `require "Utils.php"`, here is a reproducer of the problem : https://github.com/pielonet/concurrency/blob/main/tutorial/example43-issue322/main.php

Here is the error message I get : As you can see the first ten runs are OK (there are ten "*" and ten "#" in a row).
On the 11th invocation of `\parallel\run`, through to 20th the error occurs.
The Pool class limits the number of parallel threads to ten so I guess parallel starts reusing cached Runtimes from the 10th run on and complains about Class Utils being already created.

```
**********##########**********PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4

Fatal error: Cannot declare class Utils, because the name is already in use in /app/tutorial/example43-issue322/Utils.php on line 4
PHP Fatal error:  Uncaught parallel\Future\Error\Killed: cannot retrieve value in /app/tutorial/example43-issue322/singleQueue.php:158
Stack trace:
#0 /app/tutorial/example43-issue322/singleQueue.php(158): parallel\Future->value()
#1 /app/tutorial/example43-issue322/main.php(15): require('/app/tutorial/e...')
#2 [internal function]: {closure}(Array)
#3 {main}
  thrown in /app/tutorial/example43-issue322/singleQueue.php on line 158

Fatal error: Uncaught parallel\Future\Error\Killed: cannot retrieve value in /app/tutorial/example43-issue322/singleQueue.php:158
Stack trace:
#0 /app/tutorial/example43-issue322/singleQueue.php(158): parallel\Future->value()
#1 /app/tutorial/example43-issue322/main.php(15): require('/app/tutorial/e...')
#2 [internal function]: {closure}(Array)
#3 {main}
  thrown in /app/tutorial/example43-issue322/singleQueue.php on line 158
```

**Comment by realFlowControl** [comment]
Thanks @pielonet, got it. So yeah, this is expected, as `ext-parallel` will leave this thread in whatever state the last thread left it. So this example here:
```php
<?php
$fun = function() {
    if (!array_key_exists('counter', $GLOBALS)) {
        $GLOBALS['counter'] = 0;
    }
    $GLOBALS['counter']++;
    echo "counter is at " . $GLOBALS['counter'] . PHP_EOL;
};

for ($i = 0; $i < 100; $i++) {
    \parallel\run($fun);
}
```
Will do exactly what you think it does 😉 

```
counter is at 1
counter is at 1
counter is at 2
counter is at 3
counter is at 1
counter is at 2
counter is at 4
counter is at 2
counter is at 3
counter is at 1
counter is at 5
counter is at 3
counter is at 2
counter is at 1
counter is at 4
counter is at 6
counter is at 5
counter is at 4
counter is at 3
counter is at 1
counter is at 7
counter is at 2
counter is at 5
counter is at 4
counter is at 6
counter is at 8
counter is at 2
counter is at 1
counter is at 5
counter is at 7
counter is at 3
counter is at 6
counter is at 9
counter is at 1
counter is at 8
counter is at 3
counter is at 6
counter is at 7
counter is at 4
counter is at 4
counter is at 7
counter is at 8
counter is at 9
counter is at 2
counter is at 10
...
```

So yeah, I might need to put in some love to the docs to state these kind of side effects. It is also this way if you use a `new \parallel\Runtime()` like this:
```php
<?php
$fun = function() {
    if (!array_key_exists('counter', $GLOBALS)) {
        $GLOBALS['counter'] = 0;
    }
    $GLOBALS['counter']++;
    echo "counter is at " . $GLOBALS['counter'] . PHP_EOL;
};

$runtime = new \parallel\Runtime();

for ($i = 0; $i < 100; $i++) {
    $runtime->run($fun);
}
```
Which will result in this output:
```
counter is at 1
counter is at 2
counter is at 3
counter is at 4
counter is at 5
counter is at 6
counter is at 7
counter is at 8
counter is at 9
counter is at 10
counter is at 11
counter is at 12
counter is at 13
counter is at 14
counter is at 15
counter is at 16
...
```

I tend to see this as a docs issue and try to make it more clear there. Thanks for reporting!

**Comment by pielonet** [comment]
Thanks for the explanation.
I finally modified the Pool class to create a new Runtime for every single task run. This might not be optimal but this works.
