### ISSUE TITLE
segfault when loading parallel module with dl function

### ISSUE THREAD

**Issue by Djackg** [krakjoe/parallel#323]
Hi,

when i'll try to use parallel module as dynamically loaded with dl function i'm getting segmentation fault.
There is no problem, when extension is loaded on startup via ini file, 

In sandbox module there wasn`t problem with dl function

How to reproduce:  Hello world with dl

**Comment by cmb69** [comment]
See https://github.com/php/php-src/issues/9196. TL;DR: don't use `dl()` at all.

**Comment by realFlowControl** [comment]
Hey @Djackg,

> See [php/php-src#9196](https://github.com/php/php-src/issues/9196). TL;DR: don't use `dl()` at all.

This!

Nevertheless I'd like to understand why you `dl()` instead of load via INI.

Kind regards 
Florian
