### ISSUE TITLE
Support the "select" statement

### ISSUE THREAD

**Issue by pielonet** [krakjoe/parallel#324]
Hi,

Receiving from channels is always blocking.
I wonder how you manage to receive from the first available channel as it is done in Go with the "select" statement : see https://go.dev/tour/concurrency/5

Kind regards,

**Comment by realFlowControl** [comment]
Hey @pielonet,

I am not 100% I understand the problem. Can you write me a small reproducer and add comments of the behaviour you are missing or observing? AFAIK you should be able to use [`\parallel\Events::addChannel()`](https://www.php.net/manual/de/parallel-events.addchannel.php) to read non-blocking via an EventLoop from a channel.

**Comment by realFlowControl** [comment]
@pielonet I was digging into https://github.com/krakjoe/parallel/issues/218 and I think you might be looking into something like that. Problem is though that `\parallel\Events::poll()` is a busy wait under the hood. From a PHP userland perspective this should be what you do, that `poll()` is busy waiting is an implementation problem that I might need to spend some time on.

**Comment by realFlowControl** [comment]
Something like this should be what you are looking for:
- create a buffered `Channel`
- spawn multiple threads that all write to that `Channel`
- have the main loop "busy-wait" using `poll()` on data on that `Channel`
- once there is an event (the channel becomes readable), the `poll()` method will return a `\parallel\Event` instance


```php
<?php

$channel = new \parallel\Channel(1000);

for ($i = 0; $i <= 10; $i++) {
    \parallel\run(
        function(\parallel\Channel $channel, int $worker){
            while (true) {
               $sleep = rand(10000,99999);
                usleep($sleep);
                echo "Sending ... $sleep from worker $worker".PHP_EOL;
                $channel->send("Worker $worker sleeped for $sleep microseconds");
            }
        },
        [$channel, $i]
    );
}

$events = new \parallel\Events();
$events->addChannel($channel);
$events->setBlocking(true);

while ($event = $events->poll()) {
    $data = $event->value;
    echo $data.PHP_EOL;
    $events->addChannel($channel);
}
```

**Comment by pielonet** [comment]
Hi @realFlowControl ,

Thank you for you support. I eventually figured it out after many efforts.

Here is the code that reproduces exactly what https://go.dev/tour/concurrency/5 does :

```php
<?php
/**
 * Fibonacci
 * Mimics the Go "select" statement with event-loop
 * Variant with blocking loop and $events->poll()
 * 
 * Adapted from https://go.dev/tour/concurrency/5
 */

use \parallel\{Channel,Events,Events\Event,Events\Input};

function fibonacci (Channel $channel, Channel $quit) {
    $x = 0;
    $y = 1;

    $events = new Events();
    $events->addChannel($channel);
    $events->addChannel($quit);
    $input = new Input();
    $input->add('fibonacci', $x);
    $events->setInput($input);
    $events->setBlocking(true);

    while ($event = $events->poll()) {
        switch ($event->source) {
            case 'fibonacci':
                if ($event->type == Event\Type::Write) {
                    $c = $x;
                    $x = $y;
                    $y += $c;

                    // Channel and Input got removed, add them again
                    $events->addChannel($channel);
                    $input->add('fibonacci', $x);
                    $events->setInput($input);
                }
                break;

            case 'quit':
                echo "quit\n";
                return;
        }
    }

}

$channel = Channel::make('fibonacci', 1);
$quit = Channel::make('quit');

\parallel\run(function (Channel $channel, Channel $quit) {
    for ($i=0; $i < 10; $i++) {
        $e = $channel->recv();
        echo "$e\n";
    }
    $quit->send(0);
}, [$channel, $quit]);

fibonacci($channel, $quit);
```

I created 3 variants that can be found here : 
- Variant with blocking loop and foreach : https://github.com/pielonet/concurrency/blob/main/tutorial/examples/102/main.php
- Variant with non-blocking loop and poll() : https://github.com/pielonet/concurrency/blob/main/tutorial/examples/102bis/main.php
- Variant with blocking loop and poll() : https://github.com/pielonet/concurrency/blob/main/tutorial/examples/102ter/main.php
