### ISSUE TITLE
In-tree building parallel may produces wrong `php-config`  (empty PHP_VERSION)

### ISSUE THREAD

**Issue by crazywhalecc** [krakjoe/parallel#333]
https://github.com/krakjoe/parallel/blob/853798dffbbd78e394588c271ec7df9997e0476a/config.m4#L17

After copying parallel to `php-src/ext/parallel/` dir and build PHP, we will get `php-config` script with empty PHP_VERSION variable.

It seems that `PHP_VERSION=$($PHP_CONFIG --vernum)` returns an empty value in in-tree build mode, because there is no `php-config` at this time. This will cause the code to become `PHP_VERSION=`, and finally the PHP version recorded in `config.status` after `configure` is completed is empty.

Perhaps we can change the variable name (such as `PARALLEL_PHP_VERSION`), or consider the `$PHP_VERSION` variable that already exists in in-tree build.

**Comment by cmb69** [comment]
Maybe:
````
if [ -n "$PHP_VERSION" ]; then PHP_VERSION=$($PHP_CONFIG --vernum); fi
````

**Comment by realFlowControl** [comment]
Hey @crazywhalecc 👋 

would you mind trying your in-tree build with the changes from #334?
I tried locally already and it looked good so far, if you can confirm this PR solving your problem I'd merge.

Thanks for reaching out 🎉

**Comment by crazywhalecc** [comment]
@realFlowControl It looks good to me, thanks for your quick action!
