### ISSUE TITLE
What do the Future|Runtime errors extend

### ISSUE THREAD

**Issue by WyriHaximus** [krakjoe/parallel#36]
Do they extend `\Error` or `\Exception`. Been trying to figure that out while reading `ext-parallel`/`php` C code but I'm not entire sure what the difference is `zend_ce_error_exception` and `zend_ce_exception` and `zend_ce_error`. My guess is that `zend_ce_throwable` maps to `\Throwable`, `zend_ce_error` to `\Error`. But I'm unsure about `zend_ce_error_exception` since it mentions both `error` and `exception`.

**Comment by krakjoe** [comment]
It was already the case that all sub namespaced errors extend from \parallel\Error, but for some reason \parallel\Error extends ErrorException not Error, this is just a mistake and has been rectified in the above commit.

Just an oversight, sorry about that ...

**Comment by WyriHaximus** [comment]
TIL there is a `ErrorException`. Thanks for the clarification! Been working on getting `ext-parallel` [stubs into PHPStorm](https://github.com/JetBrains/phpstorm-stubs/pull/594) and this had me puzzled. Might open more issues with questions.

**Comment by dktapps** [comment]
@WyriHaximus you'd likely make better progress by auto-generating the baseline stuff. Maybe [this](https://github.com/pmmp/extension-stub-generator) might be useful to you.

**Comment by WyriHaximus** [comment]
@dktapps cool thanks :+1:
