### ISSUE TITLE
Constant values of Events\Event\Type

### ISSUE THREAD

**Issue by WyriHaximus** [krakjoe/parallel#37]
So I'm working on [PHPStorm stubs](https://github.com/JetBrains/phpstorm-stubs/pull/594) for this extension. Now neither can I find nor get the values from my docker image with `ext-parallel` in it for those constants. (Will look into that later.) I did find the following header file: https://github.com/krakjoe/parallel/blob/cee25ecef92904bbaeebbfff3fb098fb3d755473/src/event.h

So I'm assuming that the values for the constants are even though the enum only specifies the first:

```php
final class Type
{
    public const Read = 1;
    public const Write = 2;
    public const Close = 3;
    public const Cancel = 4;
    public const Kill = 5;
    public const Error = 6;
}
```

Is that correct?

**Comment by krakjoe** [comment]
Yes, but their values are an implementation detail that you cannot rely on, you can only rely on their name and meaning.

**Comment by WyriHaximus** [comment]
Ok so internal to `ext-parallel` only. I'll change them to `null` on the stub. Thanks again :+1:
