### ISSUE TITLE
Channel Roles ?

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/parallel#38]
In go, a routine can enforce which side of a channel a routine should access, and it will throw errors when a channel accepted for recv is used for sending and vice versa ...

We could do this for tasks (I've done it already) ... it would work like this ...

```php
$runtime->run(function(Channel\Read $channel) {
    $channel->send(false); // exception
}, [$channel])

$runtime->run(function(Channel\Write $channel)) {
    $channel->recv(); // exception
}, [$channel]);
```

Channel implements Channel\Read and Channel\Write, so you could use those types on any function parameter and it would pass, but specifically only for tasks, we can enforce the role.

It gets awkward because closures that we transmit over channels cannot have the same behaviour as tasks ... to overcome this, we could add a Channel::role allowing the caller to determine the role (instead of the callee) ...

Another option is to drop the magic "cast" for tasks and just have Channel::role which returns a Channel\Read or Channel\Write ...

Essentially, this is the cost of this feature:

https://github.com/krakjoe/parallel/blob/248558497a6c64a24d1fef863abe82b2fa5acc57/src/scheduler.c#L205-L220

It means every time we push a param onto the stack of a runtime, we have to travel that path ... that's not a particularly slow path, so it's quite a cheap check to make ...

Is there any interest in this, or is it too magical ?

**Comment by WyriHaximus** [comment]
This would be nice to have for me to be honest. Will experiment with it and get back to this issue :+1:

**Comment by krakjoe** [comment]
I broke the build at some point in the last couple of days ... I rebased on develop if you want to try having a play ...

Just to give my opinion on this ... I think the ability to choose a side is valuable, and the magic cast behaviour is cool and seems useful. But, magic is bad, and I would really like if the behaviour was the same everywhere, and we can't do the magic for normal closures/functions, so I think I'm leaning toward having a method to fetch an object representing one side of a channel - the callee can still decide which side of the channel to accept,. but then the caller has to take additional actions and I don't really want to add more methods, if I can help it ...

So no clear thoughts at all, I'm very open to listening to what other people think ...

**Comment by ghost** [comment]
Personally I prefer the method. This way the caller decides the role of the channel, it's not magic (it's straight forward and clear) and there's no additional check for every stack push needed (even though it may be cheap, it should be an one time cost).
