### ISSUE TITLE
Functional API

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/parallel#39]
When writing real world code, you find yourself doing new Runtime at awkward times, like [this](https://gist.github.com/krakjoe/0ee02b887288720d9b785c9f947f3a0a#file-crawler-php-L165).

Actually deciding what runtime object to use is a decision that can be made internally, so that we may just have:

```php
\parallel\run(function() {
    echo "Hello Parallel\n";
});
```

I expect, that will become idiomatic parallel code ...

We will *add* the following API:

  - \parallel\bootstrap
  - \parallel\run

_Note: all other API's remain unchanged._

\parallel\bootstrap(string)
----------------------------------

Shall use the provided file for bootstrapping runtimes created via \parallel\run.

Only needs to be called once per process.

\parallel\run(Closure $task, array $argv = [])
------------------------------------------

Shall schedule task for execution in an available runtime, maintained by parallel.

parallel shall create a runtime where there is none available for execution (without limit).

Note: because runtimes have a thread local scope, so do available runtimes. This means parallel\run will only be able to use runtimes that were created by the current thread with \parallel\run.

**Comment by dktapps** [comment]
I'm not really sure what the point of the aliases are. They don't seem to provide any benefit vs the original statics.

what is the expected behaviour of defining a bootstrap after there are already runtimes alive?

**Comment by dktapps** [comment]
another thing to note is that it's possible to import functions and this may result in some confusing looking code (PhpStorm does this for me automatically):

```
use function parallel\run;

run(function(){});
```
perhaps it might be preferable to box these inside static classes?

**Comment by WyriHaximus** [comment]
How would you control the number of runtimes active? Is there a way to set a max or does it keeps spawning everything you call `run`?

**Comment by krakjoe** [comment]
> I'm not really sure what the point of the aliases are. They don't seem to provide any benefit vs the original statics.

You're not going to keep typing \parallel\run, you're probably going to use an alias like 

```php
use function \parallel\run [as go :)];
```

Channel methods can't be imported, and really make and open are functions that should have been in the Channel namespace but I don't want to move them.

I'm not so bothered about these, but I'm not sure why you think it strange ... should we drop them then ?

> How would you control the number of runtimes active? Is there a way to set a max or does it keeps spawning everything you call run?

You don't, you call \parallel\run and it will use a runtime previously created by \parallel\run if one is available, or it will create a new runtime if none are available. This means you don't have to care about creating runtimes or maintaining a list, let parallel schedule the task, and below parallel the os will schedule the thread. The guarantee that parallel\run provides is that the task will start to execute in parallel as soon as your hardware will allow, and that's all you need care about.

There will still be times when you want to use Runtime directly, so I'm not removing it.

> what is the expected behaviour of defining a bootstrap after there are already runtimes alive?

\parallel\bootstrap is only used for runtimes creates by \parallel\run, and shall only effect subsequent calls to \parallel\run, having no effect on previously created runtimes.

**Comment by dktapps** [comment]
I think the functional make() and open() are going to be confusing. It's not obvious from their names or namespace what they do. Personally I would jump to the Channel:: static methods.

**Comment by krakjoe** [comment]
ack, we'll drop 'em ...

**Comment by krakjoe** [comment]
@dktapps I think I'll restrict bootstrap to once per process, I think in the vast majority of cases, this will suffice, and ensures you don't have to keep calling \parallel\bootstrap depending on context ... in addition, moving forwards, I hope that the pool of threads can be process wide and not thread local, there's no technical reason we can't share the threads, I'm quite sure anyway, but need to conduct a review before I try that. When the pool of threads is process wide, it will not be reasonable to bootstrap them differently really.

What do you think of having bootstrap per process and throwing an exception if one tries to set it again ?

We don't have too, we can check that the perspective runtime is bootstrapped as is currently required, but it seems messy to me ...

**Comment by dktapps** [comment]
That sounds reasonable enough to me.

**Comment by krakjoe** [comment]
ack, commited that ... so now you can only call once per process, and if there are runtimes executing it must not be set - in reality this means that you should call it before \parallel\run, once ... nice and simple ...

**Comment by krakjoe** [comment]
okay, done with this now ... thanks for input ...

**Comment by WyriHaximus** [comment]
> > How would you control the number of runtimes active? Is there a way to set a max or does it keeps spawning everything you call run?
> 
> You don't, you call \parallel\run and it will use a runtime previously created by \parallel\run if one is available, or it will create a new runtime if none are available. This means you don't have to care about creating runtimes or maintaining a list, let parallel schedule the task, and below parallel the os will schedule the thread. The guarantee that parallel\run provides is that the task will start to execute in parallel as soon as your hardware will allow, and that's all you need care about.
> 
> There will still be times when you want to use Runtime directly, so I'm not removing it.
> 

Ok cool so essentially sugar around the OOP API. Really like that, while I myself don't have a usecase directly for that I'm pretty sure it will come in handy along the way 👍

**Comment by dktapps** [comment]
It's awesome for quickly scripting things. It makes threading things in quick scripts effortless.
