### ISSUE TITLE
\parallel\Runtime\Class\Unavailable unusable

### ISSUE THREAD

**Issue by dktapps** [krakjoe/parallel#40]
```php
use parallel\Runtime\Class\Unavailable;

$thing = null;
if($thing instanceof Unavailable){
    var_dump("hi");
}else{
    var_dump("nope");
}
```
```
Parse error: syntax error, unexpected 'Class' (T_CLASS), expecting identifier (T_STRING) or '{'
```
It seems PHP isn't a fan of `Class` in the class FQN.

**Comment by krakjoe** [comment]
Can you think of a case where you would need to reference the name of that class in code ? Typically, it will just cause your code to throw a type error at some point, right ? You're not going to be hinting for it, or otherwise referencing it in code ... I think ?

**Comment by dktapps** [comment]
The problem manifested when I generated IDE stubs for the extension. It has trouble with them because `Class` isn't allowed in a class FQN, so the stub syntax becomes invalid. It's possible to delete such entries, but it's not hugely convenient.
