### ISSUE TITLE
A way to get thread ID

### ISSUE THREAD

**Issue by dktapps** [krakjoe/parallel#44]
[`zend_thread_id()`](https://www.php.net/manual/en/function.zend-thread-id.php) isn't available unless PHP was compiled in debug mode, so it isn't suitable for most practical use cases.

It would be nice to have API similar to pthreads' `Thread::getCurrentThreadId()` (and perhaps `Thread->getThreadId()`).

**Comment by krakjoe** [comment]
I'm not very keen on this ... the reason is that it's easy enough to give your threads (or tasks) an identity that's meaningful to the application. The only identity we can provide is casting pthread_t to long, which isn't really giving you a meaningful value, the value displayed in gdb/htop/top/ps is the LWP id (system tid), and you can only get that by performing a syscall in the thread you want to identify, and if we want to identify any thread that way, we have to make that syscall on entry to *every* thread ...

**Comment by krakjoe** [comment]
Are you silent because you're convinced by my words, or silent because unconvinced ? :)

**Comment by dktapps** [comment]
I forgot to follow up to the notification.

I agree that it's easy to provide a user-defined thread ID, but since nothing is truly global it's a little tricky to make them unique without going full randomized. In addition I'd find system IDs useful for things like gdb debugging.

I won't be too upset if you don't want this.

**Comment by krakjoe** [comment]
So, I've been working on a sync primitive for a while (a-la golang's sync package) ... you gave me a good reason to [finish it today](https://github.com/krakjoe/parallel/commit/75d541fc76488a21fccc56dda3df6630c92569c0) ...

golangs sync package is a little too low level for my liking, and for the average programmer's liking probably ...

pthreads users will recognize some the API, and already know how to use it, but for the sake of others reading: Sync encapsulates mutex, conditions, and semaphores ...

```php
<?php
$sync = new \parallel\Sync(1); /* may only contain scalars */

/*
 Shall return a unique human readable identity string
 Note: Does not need to be called in a synchronized block
*/
$getUniqueIdentity = function() use ($sync) {
    return $sync(function() use($sync) {
       $id = 
          $sync->get();

       $sync->set($id+1); /* poor mans atomic increment ... we are poor */

       return sprintf("0x%X", $id * 4096); /* or just return the int */
    });
};

while (@$i++<10) {
    \parallel\run(function() use($getUniqueIdentity){
        var_dump($getUniqueIdentity());
    });
}
?>
```

Documentation will be updated before the next release, probably tomorrow, release Monday ...

PS. I may provide something like golangs atomic package, under the same sort of umbrella as parallel\sync ... I'm considering whether it's really useful/worth it ...

**Comment by krakjoe** [comment]
I'm going to close this now ...

**Comment by dktapps** [comment]
Atomics would certainly be nice. It's the one big thing I've really felt is missing from parallel. We can do unbuffered channels but it's not quite the same.

**Comment by webloft** [comment]
On Unix and In PHP >= 7.4 with FFI enabled, you can do this inside a thread (and love):

```php
$ffi = \FFI::cdef('long syscall(long number, ...);');
$threadId = $ffi->syscall(186);
```

You may need to find out the right syscall, which is defined in syscall.h, unistd_64.h but on most kernel it should be 186 for 64bit and 224 for 32bit systems. Don't know how to call on Windows, but it should be similiar with a specific DLL like this:

```php
// untested
$ffi = \FFI::cdef('DWORD GetCurrentThreadId();', 'Kernel32.dll');
$threadId = $ffi->GetCurrentThreadId();
```
