### ISSUE TITLE
Crash on `new Channel()`

### ISSUE THREAD

**Issue by dktapps** [krakjoe/parallel#45]
```php
$channel = new Channel();
```
causes a segfault.

This was auto-completed for me by an IDE using stubs I generated from the extension. It would probably be wise to mark the `Channel` constructor as private so this problem can't occur.

**Comment by krakjoe** [comment]
Ah, I'm not sure that solves the problem for you, does it, or will it still try to generate the same code ? Is the same true of Future ?

**Comment by dktapps** [comment]
I imagine it would do the same thing. For generation purposes I think it would be best to mark it with ZEND_ACC_PRIVATE.

**Comment by dktapps** [comment]
the stub in question for posterity: https://gist.github.com/dktapps/ccb2dc0eaec279d98fa112121da6a9c0

ofc in any cases where a constructor is entirely missing, it's assumed to be public with 0 args.

**Comment by krakjoe** [comment]
Let me think about it, it's a bit odd for Future and Channel to have different behaviours ...

**Comment by krakjoe** [comment]
When you set the constructor private, the engine will output an exception saying you made an illegal call from the current context, which doesn't communicate that the constructor must not be used from any context. In the case of future, we have to throw a custom exception to set the state of the future when it's incorrectly used.

I think exceptions being meaningful is more important than their being compatible with code generation in IDE's ... so I'm going to leave it as it is with custom exceptions ... sorry if that's awkward ...
