### ISSUE TITLE
request: Polyfill wrapper

### ISSUE THREAD

**Issue by nachoparker** [krakjoe/parallel#57]
In the same way that `pthreads` has the option for polyfill (https://github.com/krakjoe/pthreads#polyfill) it would be great to have this available for `parallel`.

As of today it is not easy to find a ZTS interpreter unless you build it yourself, so this would allow for a graceful, future proof transition where the code might be already there whenever ZTS becomes widely available.

Thanks

**Comment by landall** [comment]
why don't you install it with yum of CentOS?
the executable command is zts-php, not php.

**Comment by krakjoe** [comment]
Sorry, I don't have the time and don't intend to do this.
