### ISSUE TITLE
parallel\Atomic

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/parallel#58]
I mentioned in #44 that I was considering introducing a parallel\Atomic class. I wanted to get some feedback on whether we think this is a good idea ...

parallel\Sync will allow you to execute code exclusively and get/set are atomic, however it lacks a math interface, and adding one doesn't make a lot of sense imo (what would it mean to perform math on a string !?).

Note 1: There are differences in msvc and gcc/clang atomic API's that mean some functions don't really make sense, in particular atomic compare exchange in gcc/clang will return bool and in msvc will return the initial value of the target. It's Monday < 8am, but right now I can't think of a way to cover up that difference, it would seem you want the boolean return to tell you if the operation suceeded, returning the original value makes no sense to me right now ... in case not clear, I'm not that familiar with msvc, I'm just going by what the docs say, if anyone knows anything, holla ...

Note 2: If we were to have an atomic class, it will likely only be for atomic ints - we can't have atomic arrays or objects, and an atomic string doesn't make a whole lot of sense (and is covered by parallel\sync) ...

Note 3: okay, I overstretched myself with 3, but I might think of something later on ...

Any words on the subject are welcome, I know @dktapps expressed that he felt atomics were "something missing", is anyone else missing them ? does anyone else think it's a terrible idea (too low level for php, or any other reason) ?

**Comment by krakjoe** [comment]
Note 3: the way that do_operation is implemented for objects in zend means that we can't have a magical math interface that supports operators and covers up the difference between (for example) fetch sub and sub fetch, so the interface would have to have a bunch of methods, and the user would have to have a clue what they are doing ...

Note 4: msvc's atomic API's don't allow the programmer to choose memory order/model, so we wouldn't be able to allow the programmer to choose either, and would have to ensure that every method is implemented as it's implemented in msvc, I dunno how much work that is ...

**Comment by krakjoe** [comment]
Here's something else to think about:

```php
<?php
use \parallel\Sync as Atomic;

$atomic = new Atomic(1);

$atomicCompareExchange = function(Atomic $atomic, int $expected, int $desired) : bool {
    return $atomic(function() use($atomic, $expected, $desired) {
        if ($atomic->get() == $expected) {
            $atomic->set($desired);
            return true;
        }
        return false;
    });
};

var_dump($atomicCompareExchange($atomic, 1, 2), $atomic); # true
var_dump($atomicCompareExchange($atomic, 1, 3), $atomic); # false
var_dump($atomicCompareExchange($atomic, 2, 1), $atomic); # true
?>
```

Obviously, this is not as efficient as using atomics at the level of C, however, it is simple, and code that can be JIT'd ...

The question is, how much are atomics going to be used, and is it really worth introducing the additional complexity at the level of the extension to satisfy those use cases which could be satisfied in userland  ?

**Comment by dotfry** [comment]
Looks interesting, but as I see in code, it allow use only primitives in `\parallel\Sync::__construct`. Is it possible to Sync objects too?

**Comment by krakjoe** [comment]
There's not a strong use case for that, worse, I think it would lead you down the wrong path.

**Comment by dotfry** [comment]
I'll think that `\parallel\Sync` has potential. Really useful for indicators or counters for me. Adding object and\or arrays this will add a few more cases, but managing such data with Atomic will look not clear.

Do I need to call `notify` \ `wait`, or `__call` enough to modify atomic and notify all other threads?

**Comment by krakjoe** [comment]
You should only notify if other threads may be waiting, and you should only ever wait *for* something ...

Both wait/notify should be called synchronized (via Sync::__invoke):

```php
<?php
$sync = new \parallel\Sync;

\parallel\run(function() use($sync) {
    $sync(function() use($sync) {
        while ($sync->get() != 42) {
            $sync->wait();
        }

        echo "Sync value is 42\n";
    });
});

usleep(mt_rand(100, 1000000));

$sync(function() use($sync) {
    $sync->set(42);
    $sync->notify();
});
?>
```

A nice tool for detecting errors in usage of primitives is drd, a tool built into valgrind. If you run the code above through drd (valgrind --tool=drd php thing.php), no errors will be detected, if you misuse the primitives thus:

```php
<?php
$sync = new \parallel\Sync;

\parallel\run(function() use($sync) {
    $sync(function() use($sync) {
        while ($sync->get() != 42) {
            $sync->wait();
        }

        echo "Sync value is 42\n";
    });
});

usleep(mt_rand(100, 1000000));

$sync->set(42);
$sync->notify();
?>
```

drd should show something like:

```
Probably a race condition: condition variable 0xa092688 has been signaled but the associated mutex 0xa092660 is not locked by the signalling thread.
```
Note that the error message says "probably", that's because the specification allows for signal/broadcast without a locked mutex, but when it's appropriate to do that is complex, so stick to the basic rules ...

The Sync primitive is a last resort, and intended for very low level programming, you should do everything you can to avoid using it, and it's proper use depends on knowledge of the underlying primitives - that I have to explain how to use it, or how not to use it, tells me you probably shouldn't be using it, at least not until you've learned about the underlying primitives :)

I say this, because documenting the usage of mutex, conditions, and the implementation of semaphores is outside of the scope of the PHP manual - there will never be a walkthrough for the \parallel\Sync primitive in PHP, it's intended audience shouldn't need one ... although the manual can be expanded a little, it will never tell you everything you need to know ...

**Comment by dktapps** [comment]
for what it's worth, I found the behaviour of wait and notify in pthreads very confusing because it is not clearly documented, and because the behaviour without a lock isn't consistent across platforms. For the sake of parallel I would recommend enforcing the rule that they may only be used when a lock has been obtained, and throwing an exception when they are used outside of a synchronised block (provided there's some reasonable way to do that).

**Comment by krakjoe** [comment]
> For the sake of parallel I would recommend enforcing the rule ...

That would mean the programmer is not able to notify without synchronization, which the specification allows for a reason.

So, that doesn't seem like a good idea ...

The best course of action is almost always to notify only when synchronized, but we can't make it exceptional to use primitives as per the specification, it would reduce their usability for those people who do know how to use them ... hopefully the only people using them know what they are doing ...

Atomic counters and such may be implemented without using conditions, that should be the main use case for sync ...

**Comment by krakjoe** [comment]
Oh, I've just had an idea ... what if Sync::__construct had a second parameter `bool $strict = true`, so that by default, you get your exception on invalid use, but the advanced programmer is not prohibited from using them as per the specification ?

**Comment by dktapps** [comment]
I think an opt-in behaviour for this seems reasonable.
