### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Sarke** [krakjoe/parallel#6]
Not really an issue, just wanted to share I made a docker image in case anyone wanted to play with it.

https://hub.docker.com/r/sarkedev/php-parallel

Thanks again!

**Comment by peter279k** [comment]
It's not an issue, but we can mention this environment with Docker build on the `README` :+1: .

**Comment by krakjoe** [comment]
I don't object to adding a docker section to the readme, however, that current dockerfile creates a snapshot build, and there doesn't seem to be a way to run the latest release ...

If you are willing to setup a versioned docker image with the latest release, and a snapshot, and prepare a PR for the readme, I'd be happy to merge it.

**Comment by krakjoe** [comment]
If you find the time for this, open another issue :)
