### ISSUE TITLE
Copy needs a context

### ISSUE THREAD

**Issue by krakjoe** [krakjoe/parallel#64]
When parallel copies vars, it does so without a context, this means that if an array contains a reference to itself, overflow will result. I knew about this, and it didn't seem so urgent, however, since I added support for closure binding, this shortcoming can easily lead to overflow.

We must copy with a context, so that if a var is already copied for any particular context, it is not reduplicated, but subsequent copies refer to the already copied var.

I'll add a simple test case to reproduce the issue when I've got time to work on the solution.

Brought to my attention by: https://github.com/humbug/box/pull/429

**Comment by theofidry** [comment]
Any update on this? I would like to know if I can except it in a near future or if it's likely gonna wait another couple of month (it's mostly for myself to plan with some refactoring on Infection)

**Comment by krakjoe** [comment]
It's hard to tell the difference between the near future, and a couple of months :)

I'm just not actually sure, it could be this weekend, or next, or in 5 ... it's going to take a whole weekend, that's for sure ...

**Comment by krakjoe** [comment]
@realFlowControl I wrote the context stuff, but haven't done any tests, could you find some time to write some tests please? essentially anything with recursion ... I may find time, but it will likely be quicker if you do it ...

sorry about breaking CI ...

I think there's probably a few issues you can prune, and you are probably more familiar with what they are at this point than me ...

In case I didn't say it yet, thanks for all the effort :)

**Comment by realFlowControl** [comment]
I'm on a vacation with my family till Friday, but I'll I can pick up after my return.

> In case I didn't say it yet, thanks for all the effort :)

❤️

**Comment by krakjoe** [comment]
Enjoy your rest, I might get to it before then :)
