### ISSUE TITLE
7.4 support

### ISSUE THREAD

**Issue by remicollet** [krakjoe/parallel#67]
Build is broken with 7.4.0alpha1

**Comment by krakjoe** [comment]
Fixed in cd2f74a75d0c72e26604625ca2327848bb8c5436

I just missed the alpha1 tagging ...

**Comment by remicollet** [comment]
@krakjoe please review b2bba95b70e387bb8c42d756f364c2a882e65064

**Comment by remicollet** [comment]
Sorry for the noise... bad project

**Comment by krakjoe** [comment]
no worries :)
