### ISSUE TITLE
segfault on runtime copy

### ISSUE THREAD

**Issue by dktapps** [krakjoe/parallel#69]
```php
$runtime = new Runtime();
\parallel\run(function() use($runtime){
    $runtime->run(function(){ echo "hi\n"; });
});
```
I accidentally copied an object which contained a Runtime and it crashed. This is the minimum test case I could produce.

**Comment by dktapps** [comment]
I may mention it might be desirable to share a reference to `Runtime`s to be able to do things like thread-safe loggers simply.

**Comment by krakjoe** [comment]
Why would you need a Runtime to be shared exactly ? I can think of a few nice ways to have a logging thread without sharing a reference to a runtime ...

Sharing runtimes complicates things, and I need extremely good justification to implement that ...
