### ISSUE TITLE
parallel\Runtime\Type\Unavailable

### ISSUE THREAD

**Issue by feamsr00** [krakjoe/parallel#73]
Forgive the "dump" but I'm getting exasperated here without documentation (seems it wont be the last time...).

What are the conditions that would cause runtime::run() to strip out and replace passed objects, as it doesn't happen _consistently to 100% of objects_. Sometimes `parallel\Runtime\Error\IllegalParameter` is thrown. Occasionally (and only somewhat reasonably) `[parallel\Runtime\Error\IllegalFunction] illegal function type (internal)` is thrown. But sometimes, just maybe certain classes (albeit internal ones) generate no error what so ever and show up fully instanced inside the thread. (Directory, et al).

What are the *rules* for all this?

(Is is possible to have ether better exception messages or a known list of failure conditions for these too?)

**Comment by dktapps** [comment]
this is exactly the kind of confusion I was concerned about with regards to only copying user objects...

to the best of my knowledge the rules on this or that any class that is either internal or extending internal class may not be copied. only "pure" user objects are copyable. the exception to this rule is parallel's own built-in objects are copyable where it makes sense.

**Comment by krakjoe** [comment]
This is documented [here](https://www.php.net/manual/en/parallel-runtime.run.php#refsect1-parallel-runtime.run-argv-characteristics) and [here](https://www.php.net/manual/en/parallel-runtime.run.php#refsect1-parallel-runtime.run-object-characteristics).

**Comment by feamsr00** [comment]
OK. I had a chance to inspect my classes that were throwing this. (I'm trying to get code using pthreads ported to Parallel) The class it's self was not using internal objects, and did not violate the noted rules. However it did *consume* objects that ended up using (constructing) core\internals objects pre ::run(). What *exactly* is the concern with serializing internal objects? Is it that they might contain undetected resources? Whats worst case? Is it sane at all to "opt-in" to serialization?
