### ISSUE TITLE
Namespace and Errors naming

### ISSUE THREAD

**Issue by dotfry** [krakjoe/parallel#75]
Most namespaces in php are written with a capital letter, and for errors, the postfix `Exception` is used instead of `Error`.

I suggest changes:
 * namespace from `parallel` to `Parallel`
 * add postfix `Exception` to all errors
 * change the namespace path in some exceptions (eg: `parallel\Runtime\Error\Bootstrap` → `Parallel\Runtime\BootstrapException`)

I can make PR with that changes, if community accepts this changes.

**Comment by dktapps** [comment]
I sure don't want all my code to break just because some person wants a "conventional" namespace. I don't mean to be rude, but this extension has a stable release now and it has projects that depend on it.

**Comment by krakjoe** [comment]
The name of the extension is "parallel", the correct namespace is being used.

If that irks you, just refer to it in your own code with capital letters, php is case insensitive ....

When it comes to postfix/suffix, it seems unimportant to me. Again, you can refer to the exceptions however you wish in your own code, but the motivation to change their names is not sufficient.
