### ISSUE TITLE
Parallel in other contexts

### ISSUE THREAD

**Issue by feamsr00** [krakjoe/parallel#77]
Hi again! I have a feature request to allow Parallel to run in one other context, *namely* phpdbg.

After #76, I tried to drop into phpdbg and remained rather confused for a long time untill I realized Parallel wasn't even running!

https://github.com/krakjoe/parallel/blob/8564ddf8cacdc345047b2ab435d16c5651b59faa/src/parallel.c#L200-L202

What are the concerns to allowing phpdbg, if any?

Is this a sane request?

PS Might I also suggest allowing the "embed" context too?

**Comment by krakjoe** [comment]
That code does not restrict the SAPI, it's a work around specific to CLI.

phpdbg will not function properly with parallel, phpdbg does not support multithreaded debugging.
