### ISSUE TITLE
zend_mm_heap corrupted when protobuf extension loaded

### ISSUE THREAD

**Issue by prolic** [krakjoe/parallel#78]
Platform: Ubuntu 18.04 (64bit)
PHP: 7.3.7

Extensions: parallel + protobuf (both via pecl)

Test Script:

```
<?php

$callback = function () {
    for ($i = 0; $i < 100000000; $i++) {
        // do nothing
    }

    return '.';
};

$f = [];

for ($i = 0; $i < 4; $i++) {
    $parallel = new \parallel\Runtime();
    $f[$i] = $parallel->run($callback);
}

for ($i = 0; $i < 4; $i++) {
    echo $f[$i]->value();
}

echo 'OK';
```

Expected Output:
```
....OK
```

Given Output:
```
....OKzend_mm_heap corrupted
```

Note: I didn't do anything with protobuf, the extension is only loaded.

**Comment by krakjoe** [comment]
The protobuf extension is not thread-safe.

Sorry, nothing I can do about that, contributing to google stuff is more hassle than it's worth, also the code is a mess ...

**Comment by prolic** [comment]
Thanks @krakjoe
