### ISSUE TITLE
1.1.3 make error

### ISSUE THREAD

**Issue by tommiyxu** [krakjoe/parallel#81]
bin/sh /root/software/php/parallel-1.1.3/libtool --mode=compile cc -Wall -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1  -I. -I/root/software/php/parallel-1.1.3 -DPHP_ATOM_INC -I/root/software/php/parallel-1.1.3/include -I/root/software/php/parallel-1.1.3/main -I/root/software/php/parallel-1.1.3 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/root/software/php/parallel-1.1.3  -DHAVE_CONFIG_H  -g -O2   -c /root/software/php/parallel-1.1.3/php_parallel.c -o php_parallel.lo 
mkdir .libs
 cc -Wall -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/root/software/php/parallel-1.1.3 -DPHP_ATOM_INC -I/root/software/php/parallel-1.1.3/include -I/root/software/php/parallel-1.1.3/main -I/root/software/php/parallel-1.1.3 -I/usr/local/php/include/php -I/usr/local/php/include/php/main -I/usr/local/php/include/php/TSRM -I/usr/local/php/include/php/Zend -I/usr/local/php/include/php/ext -I/usr/local/php/include/php/ext/date/lib -I/root/software/php/parallel-1.1.3 -DHAVE_CONFIG_H -g -O2 -c /root/software/php/parallel-1.1.3/php_parallel.c  -fPIC -DPIC -o .libs/php_parallel.o
In file included from /root/software/php/parallel-1.1.3/php_parallel.c:27:
/root/software/php/parallel-1.1.3/src/parallel.h: In function ‘php_parallel_atomic_addref’:
/root/software/php/parallel-1.1.3/src/parallel.h:91: warning: implicit declaration of function ‘__atomic_add_fetch’
/root/software/php/parallel-1.1.3/src/parallel.h:91: error: ‘__ATOMIC_SEQ_CST’ undeclared (first use in this function)
/root/software/php/parallel-1.1.3/src/parallel.h:91: error: (Each undeclared identifier is reported only once
/root/software/php/parallel-1.1.3/src/parallel.h:91: error: for each function it appears in.)
/root/software/php/parallel-1.1.3/src/parallel.h: In function ‘php_parallel_atomic_delref’:
/root/software/php/parallel-1.1.3/src/parallel.h:101: warning: implicit declaration of function ‘__atomic_sub_fetch’
/root/software/php/parallel-1.1.3/src/parallel.h:101: error: ‘__ATOMIC_SEQ_CST’ undeclared (first use in this function)
make: *** [php_parallel.lo] Error 1

./configure checking support for __atomic_add_fetch...  no

**Comment by prolic** [comment]
I have a (maybe related) issue when installing latest 1.1.3 release with pecl:

```
Build complete.
Don't forget to run 'make test'.

running: make INSTALL_ROOT="/tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3" install
Installing shared extensions:     /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3/opt/php/7.3.7/lib/php/extensions/no-debug-zts-20180731/
running: find "/tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3" | xargs ls -dils
25298060   4 drwxr-xr-x 3 root root   4096 ago 15 18:22 /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3
25298121   4 drwxr-xr-x 3 root root   4096 ago 15 18:22 /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3/opt
25298122   4 drwxr-xr-x 3 root root   4096 ago 15 18:22 /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3/opt/php
25298123   4 drwxr-xr-x 3 root root   4096 ago 15 18:22 /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3/opt/php/7.3.7
25298124   4 drwxr-xr-x 3 root root   4096 ago 15 18:22 /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3/opt/php/7.3.7/lib
25298125   4 drwxr-xr-x 3 root root   4096 ago 15 18:22 /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3/opt/php/7.3.7/lib/php
25298126   4 drwxr-xr-x 3 root root   4096 ago 15 18:22 /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3/opt/php/7.3.7/lib/php/extensions
25298127   4 drwxr-xr-x 2 root root   4096 ago 15 18:22 /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3/opt/php/7.3.7/lib/php/extensions/no-debug-zts-20180731
25298120 804 -rwxr-xr-x 1 root root 820752 ago 15 18:22 /tmp/pear/temp/pear-build-root3ZP9QH/install-parallel-1.1.3/opt/php/7.3.7/lib/php/extensions/no-debug-zts-20180731/parallel.so

Build process completed successfully
Installing '/opt/php/7.3.7/lib/php/extensions/no-debug-zts-20180731/parallel.so'
[1]    12862 segmentation fault  sudo pecl install parallel
sudo pecl install parallel  6,21s user 1,27s system 51% cpu 14,547 total
```

**Comment by remicollet** [comment]
@prolic, build and install have worked, segfault happens during pecL registration, so is not related to this extension.

@0x00bin which platform ?

**Comment by remicollet** [comment]
@0x00bin please post config.log and config.h

**Comment by tommiyxu** [comment]
CentOS release 6.10 (Final)
PHP 7.2.21 (cli) (built: Aug 13 2019 15:17:23) ( ZTS )
[config.h.txt](https://github.com/krakjoe/parallel/files/3509168/config.h.txt)
[config.log](https://github.com/krakjoe/parallel/files/3509172/config.log)


@remicollet

**Comment by remicollet** [comment]
Is `HAVE_BUILTIN_ATOMIC` defined in `/usr/local/php/include/php/main/php_config.h` ?

Looks like PHP was build with a **different compiler** than the extension.

> CentOS release 6.10 (Final)

Perhaps you should try build available in [my repository](https://rpms.remirepo.net/wizard/) which includes all versions and near all extensions, including this one.

BTW, CentOS 6 is close to its End of Life, you should also consider updating to a more recent version.

**Comment by krakjoe** [comment]
Thanks for investigating @remicollet, this doesn't appear to be a problem here, so closing ...

**Comment by tommiyxu** [comment]
@remicollet Thank you！
