### ISSUE TITLE
illegal parameter (PDO) passed to task at argument 2

### ISSUE THREAD

**Issue by tommiyxu** [krakjoe/parallel#84]
$parallel = new parallel\Runtime();
try {
    $dsn = "mysql:dbname=test;host=127.0.0.1;port=3306";
    $pdo = new PDO($dsn, 'root', '');
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    $callback = function($pdo) {
         var_dump($pdo);
    };

    $parallel->run($callback, ['this is a test msg', $pdo]);
} catch (\parallel\Runtime\Error\IllegalParameter $ex) {
    var_dump($ex->getMessage());
}

run php code get result:
illegal parameter (PDO) passed to task at argument 2.

How to use database in parallel?

**Comment by dktapps** [comment]
You can't. Internal objects can't be passed as parameters or returned as results. It's a confusing inconsistency, but that's how it is.

**Comment by rask** [comment]
@dktapps so the correct "fix" would be to just pass the `$dsn` to the callback and initialize the connection inside the callback?

**Comment by dktapps** [comment]
Yes, I would imagine so.
