### ISSUE TITLE
Hi friend ,Why isn't it running in parallel

### ISSUE THREAD

**Issue by fengahan** [krakjoe/parallel#85]
`<?php

$socket = stream_socket_server("tcp://0.0.0.0:8000", $errno, $errstr, STREAM_SERVER_BIND | STREAM_SERVER_LISTEN);
stream_set_blocking($socket, 0);

$connections = [];
$read = [];
$write = null;
$except = null;

//view
$httpHandler=function()
{
    $data=file_get_contents('./index.html');
    $data= str_replace("{{time}}",date("Y-m-d H:i:s"),$data);
    return $data;

};

$runtime = new \parallel\Runtime();
while (true){
    $future = $runtime->run(function($socket,$connections,$httpHandler) {

            echo 'wirte_start'.time().'---';
            //  $work->run(function ($socket,$connections,$httpHandler){
            $socket = fopen("php://fd/{$socket}", "r+");
            if (is_bool($socket)){
                return;
            }
            $c = stream_socket_accept($socket, -1, $peer);
            $data=$httpHandler();

            $functions = array("addslashes", "chunk_split", "metaphone", "strip_tags", "md5", "sha1", "strtoupper", "strtolower", "strrev", "strlen", "soundex", "ord");
            $string = "the quick brown fox jumps over the lazy dog";
            for ($i = 0; $i < 400000; $i++) {
                foreach ($functions as $function) {
                    call_user_func_array($function, array($string));
                }
            }
            $http="HTTP/1.1 200 OK\r\n";
            $http.="Content-Type:text/html; charset=utf-8\r\n";
            $http.="Content-Length: ".strlen($data)."\r\n\r\n";
            $http.=$data;
            $connections[$peer] = $c;
            fwrite($c, $http);
            echo 'write_ok'.time().PHP_EOL;

    },[$socket,$connections,$httpHandler]);

}

//output
//    wirte_start1567000580---write_ok1567000587
//    wirte_start1567000587---write_ok1567000591
//    wirte_start1567000591---write_ok1567000595
//    wirte_start1567000595---write_ok1567000599
//    wirte_start1567000599---write_ok1567000603
`

**Comment by krakjoe** [comment]
Please don't use this tracker to ask for help with code.
