### ISSUE TITLE
PHP7.4RC1 undefined symbol: _tsrm_ls_cache

### ISSUE THREAD

**Issue by irisism4you** [krakjoe/parallel#87]
Hello. I've been trying to compile parallel on fresh PHP 7.4RC1 version. But something gone wring

PHP         : /etc/php74zts/bin/php 
PHP_SAPI    : 
Warning: PHP Startup: Unable to load dynamic library 'parallel.so' (tried: /etc/php74zts/php-src/ext/parallel/modules/parallel.so (/etc/php74zts/php-src/ext/parallel/modules/parallel.so: undefined symbol: _tsrm_ls_cache), /etc/php74zts/php-src/ext/parallel/modules/parallel.so.so (/etc/php74zts/php-src/ext/parallel/modules/parallel.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
cli
PHP_VERSION : 7.4.0RC1
ZEND_VERSION: 3.4.0-dev
PHP_OS      : Linux - Linux vds4173 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
INI actual  : /etc/php74zts/php-src/ext/parallel/tmp-php.ini

------------------

Building with
./configure --prefix=/etc/php74zts --with-bz2 --with-zlib --enable-zip --disable-cgi \
   --enable-soap --enable-intl --with-mcrypt --with-openssl --with-readline --with-curl \
   --enable-ftp --enable-mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd \
   --enable-sockets --enable-pcntl --with-pspell --with-enchant --with-gettext \
   --with-gd --enable-exif --with-jpeg-dir --with-png-dir --with-freetype-dir --with-xsl \
   --enable-bcmath --enable-mbstring --enable-calendar --enable-simplexml --enable-json \
   --enable-hash --enable-session --enable-xml --enable-wddx --enable-opcache \
   --with-pcre-regex --with-config-file-path=/etc/php74zts/cli \
   --with-config-file-scan-dir=/etc/php74zts/etc --enable-cli --enable-maintainer-zts \
   --with-tsrm-pthreads --enable-debug --enable-parallel --enable-fpm \
   --with-fpm-user=www-data --with-fpm-group=www-data

**Comment by krakjoe** [comment]
@remicollet any idea what's going on there ?

**Comment by remicollet** [comment]
I think the extension was build against ZTS and try to be used against NTS engine

**Comment by krakjoe** [comment]
Agree, but the paths and configure seem to be correct ... I don't know what else it could be.

I think this isn't a parallel issue ...
