### ISSUE TITLE
Php crashing 

### ISSUE THREAD

**Issue by ilantipov** [krakjoe/parallel#88]
Hello. I'm running your sample script 
 php /var/www/shared/testform.php
..............................**.......***.....****.........****...........**..*******.......**........*************...............****..********....***...*******..*****..................***..........**************......................*****..***********...**..............*******************....*****........**..................**.**************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************** Error in `php': corrupted size vs. prev_size: 0x000000000276aa50 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f87408417e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x7e913)[0x7f8740848913]
/lib/x86_64-linux-gnu/libc.so.6(+0x80678)[0x7f874084a678]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f874084e53c]
php[0x84b1a0]
php(php_module_shutdown+0x33)[0x7d73d3]
php[0x43de50]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f87407ea830]
php(_start+0x29)[0x43e039]
======= Memory map: ========
00400000-010de000 r-xp 00000000 08:01 9568664                            /usr/local/php-fpm/bin/php
012de000-01394000 r--p 00cde000 08:01 9568664                            /usr/local/php-fpm/bin/php
01394000-013be000 rw-p 00d94000 08:01 9568664                            /usr/local/php-fpm/bin/php
013be000-013dd000 rw-p 00000000 00:00 0
0256a000-02836000 rw-p 00000000 00:00 0                                  [heap]
7f8730000000-7f873008d000 rw-p 00000000 00:00 0
7f873008d000-7f8734000000 ---p 00000000 00:00 0
7f8734d23000-7f8734d24000 ---p 00000000 00:00 0
7f8734d24000-7f8735524000 rw-p 00000000 00:00 0
7f873916a000-7f8739171000 r-xp 00000000 08:01 12325555                   /lib/x86_64-linux-gnu/librt-2.23.so
7f8739171000-7f8739370000 ---p 00007000 08:01 12325555                   /lib/x86_64-linux-gnu/librt-2.23.so
7f8739370000-7f8739371000 r--p 00006000 08:01 12325555                   /lib/x86_64-linux-gnu/librt-2.23.so
7f8739371000-7f8739372000 rw-p 00007000 08:01 12325555                   /lib/x86_64-linux-gnu/librt-2.23.so
7f8739586000-7f87395ee000 r-xp 00000000 08:01 9568666                    /usr/local/php-fpm/lib/php/extensions/no-debug-zts-20170718/opcache.so
7f87395ee000-7f87397ed000 ---p 00068000 08:01 9568666                    /usr/local/php-fpm/lib/php/extensions/no-debug-zts-20170718/opcache.so
7f87397ed000-7f87397f4000 r--p 00067000 08:01 9568666                    /usr/local/php-fpm/lib/php/extensions/no-debug-zts-20170718/opcache.so
7f87397f4000-7f87397f5000 rw-p 0006e000 08:01 9568666                    /usr/local/php-fpm/lib/php/extensions/no-debug-zts-20170718/opcache.so
7f87397f5000-7f87397f6000 rw-p 00000000 00:00 0
7f87397f6000-7f8739c00000 r--p 00000000 08:01 7473093                    /usr/lib/locale/locale-archive
7f8739c00000-7f8739e00000 rw-p 00000000 00:00 0
7f8739fb6000-7f8739fbf000 r-xp 00000000 08:01 12325566                   /lib/x86_64-linux-gnu/libcrypt-2.23.so
7f8739fbf000-7f873a1be000 ---p 00009000 08:01 12325566                   /lib/x86_64-linux-gnu/libcrypt-2.23.so
7f873a1be000-7f873a1bf000 r--p 00008000 08:01 12325566                   /lib/x86_64-linux-gnu/libcrypt-2.23.so
7f873a1bf000-7f873a1c0000 rw-p 00009000 08:01 12325566                   /lib/x86_64-linux-gnu/libcrypt-2.23.so
7f873a1c0000-7f873a1ee000 rw-p 00000000 00:00 0
7f873a1ee000-7f873a2be000 r-xp 00000000 08:01 7471737                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f873a2be000-7f873a4bd000 ---p 000d0000 08:01 7471737                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f873a4bd000-7f873a4c0000 r--p 000cf000 08:01 7471737                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f873a4c0000-7f873a4c2000 rw-p 000d2000 08:01 7471737                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7f873a4c2000-7f873a4c3000 rw-p 00000000 00:00 0
7f873a4c3000-7f873a50a000 r-xp 00000000 08:01 7476883                    /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
7f873a50a000-7f873a709000 ---p 00047000 08:01 7476883                    /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
7f873a709000-7f873a70b000 r--p 00046000 08:01 7476883                    /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
7f873a70b000-7f873a70d000 rw-p 00048000 08:01 7476883                    /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
7f873a70d000-7f873a70e000 rw-p 00000000 00:00 0
7f873a70e000-7f873a71c000 r-xp 00000000 08:01 7476879                    /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
7f873a71c000-7f873a91b000 ---p 0000e000 08:01 7476879                    /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
7f873a91b000-7f873a91c000 r--p 0000d000 08:01 7476879                    /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
7f873a91c000-7f873a91d000 rw-p 0000e000 08:01 7476879                    /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
7f873a91d000-7f873a944000 r-xp 00000000 08:01 7476881                    /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
7f873a944000-7f873ab44000 ---p 00027000 08:01 7476881                    /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
7f873ab44000-7f873ab45000 r--p 00027000 08:01 7476881                    /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
7f873ab45000-7f873ab46000 rw-p 00028000 08:01 7476881                    /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
7f873ab46000-7f873ab5b000 r-xp 00000000 08:01 7476873                    /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
7f873ab5b000-7f873ad5a000 ---p 00015000 08:01 7476873                    /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
7f873ad5a000-7f873ad5b000 r--p 00014000 08:01 7476873                    /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
7f873ad5b000-7f873ad5c000 rw-p 00015000 08:01 7476873                    /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
7f873ad5c000-7f873ad8c000 r-xp 00000000 08:01 7476877                    /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
7f873ad8c000-7f873af8c000 ---p 00030000 08:01 7476877                    /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
7f873af8c000-7f873af8d000 r--p 00030000 08:01 7476877                    /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
7f873af8d000-7f873af8e000 rw-p 00031000 08:01 7476877                    /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
7f873af8e000-7f873af8f000 rw-p 00000000 00:00 0
7f873af8f000-7f873b02e000 r-xp 00000000 08:01 7476875                    /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
7f873b02e000-7f873b22d000 ---p 0009f000 08:01 7476875                    /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
7f873b22d000-7f873b22e000 r--p 0009e000 08:01 7476875                    /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
7f873b22e000-7f873b231000 rw-p 0009f000 08:01 7476875                    /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
7f873b231000-7f873b2b5000 r-xp 00000000 08:01 7476885                    /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
7f873b2b5000-7f873b4b4000 ---p 00084000 08:01 7476885                    /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
7f873b4b4000-7f873b4b7000 r--p 00083000 08:01 7476885                    /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
7f873b4b7000-7f873b4ba000 rw-p 00086000 08:01 7476885                    /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
7f873b4ba000-7f873b4bb000 rw-p 00000000 00:00 0
7f873b4bb000-7f873b4c3000 r-xp 00000000 08:01 7476887                    /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
7f873b4c3000-7f873b6c2000 ---p 00008000 08:01 7476887                    /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
7f873b6c2000-7f873b6c3000 r--p 00007000 08:01 7476887                    /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
7f873b6c3000-7f873b6c4000 rw-p 00008000 08:01 7476887                    /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
7f873b6c4000-7f873b6c7000 r-xp 00000000 08:01 12325404                   /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f873b6c7000-7f873b8c6000 ---p 00003000 08:01 12325404                   /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f873b8c6000-7f873b8c7000 r--p 00002000 08:01 12325404                   /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f873b8c7000-7f873b8c8000 rw-p 00003000 08:01 12325404                   /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f873b8c8000-7f873b8cf000 r-xp 00000000 08:01 7473453                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f873b8cf000-7f873bace000 ---p 00007000 08:01 7473453                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f873bace000-7f873bacf000 r--p 00006000 08:01 7473453                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f873bacf000-7f873bad0000 rw-p 00007000 08:01 7473453                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f873bad0000-7f873bb0d000 r-xp 00000000 08:01 7476889                    /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
7f873bb0d000-7f873bd0d000 ---p 0003d000 08:01 7476889                    /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
7f873bd0d000-7f873bd0e000 r--p 0003d000 08:01 7476889                    /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
7f873bd0e000-7f873bd10000 rw-p 0003e000 08:01 7476889                    /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
7f873bd10000-7f873bd11000 rw-p 00000000 00:00 0
7f873bd11000-7f873bd2a000 r-xp 00000000 08:01 7472798                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f873bd2a000-7f873bf2a000 ---p 00019000 08:01 7472798                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f873bf2a000-7f873bf2b000 r--p 00019000 08:01 7472798                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f873bf2b000-7f873bf2c000 rw-p 0001a000 08:01 7472798                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7f873bf2c000-7f873bf36000 r-xp 00000000 08:01 7472794                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f873bf36000-7f873c135000 ---p 0000a000 08:01 7472794                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f873c135000-7f873c136000 r--p 00009000 08:01 7472794                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f873c136000-7f873c137000 rw-p 0000a000 08:01 7472794                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f873c137000-7f873c13a000 r-xp 00000000 08:01 12321276                   /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f873c13a000-7f873c339000 ---p 00003000 08:01 12321276                   /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f873c339000-7f873c33a000 r--p 00002000 08:01 12321276                   /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f873c33a000-7f873c33b000 rw-p 00003000 08:01 12321276                   /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f873c33b000-7f873c367000 r-xp 00000000 08:01 7472796                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f873c367000-7f873c566000 ---p 0002c000 08:01 7472796                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f873c566000-7f873c568000 r--p 0002b000 08:01 7472796                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f873c568000-7f873c569000 rw-p 0002d000 08:01 7472796                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f873c569000-7f873c56a000 rw-p 00000000 00:00 0
7f873c56a000-7f873c62d000 r-xp 00000000 08:01 7472792                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f873c62d000-7f873c82d000 ---p 000c3000 08:01 7472792                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f873c82d000-7f873c83a000 r--p 000c3000 08:01 7472792                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f873c83a000-7f873c83c000 rw-p 000d0000 08:01 7472792                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f873c83c000-7f873c84d000 r-xp 00000000 08:01 7473497                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f873c84d000-7f873ca4d000 ---p 00011000 08:01 7473497                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f873ca4d000-7f873ca4e000 r--p 00011000 08:01 7473497                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f873ca4e000-7f873ca4f000 rw-p 00012000 08:01 7473497                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f873ca4f000-7f873caa8000 r-xp 00000000 08:01 7473483                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f873caa8000-7f873cca7000 ---p 00059000 08:01 7473483                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f873cca7000-7f873ccb1000 r--p 00058000 08:01 7473483                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f873ccb1000-7f873ccb3000 rw-p 00062000 08:01 7473483                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f873ccb3000-7f873cd32000 r-xp 00000000 08:01 7473461                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f873cd32000-7f873cf31000 ---p 0007f000 08:01 7473461                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f873cf31000-7f873cf32000 r--p 0007e000 08:01 7473461                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f873cf32000-7f873cf33000 rw-p 0007f000 08:01 7473461                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f873cf33000-7f873cf65000 r-xp 00000000 08:01 7473467                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f873cf65000-7f873d164000 ---p 00032000 08:01 7473467                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f873d164000-7f873d165000 r--p 00031000 08:01 7473467                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f873d165000-7f873d166000 rw-p 00032000 08:01 7473467                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f873d166000-7f873d17c000 r-xp 00000000 08:01 12321295                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f873d17c000-7f873d37b000 ---p 00016000 08:01 12321295                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f873d37b000-7f873d37c000 rw-p 00015000 08:01 12321295                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f873d37c000-7f873d4ee000 r-xp 00000000 08:01 7471224                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f873d4ee000-7f873d6ee000 ---p 00172000 08:01 7471224                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f873d6ee000-7f873d6f8000 r--p 00172000 08:01 7471224                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f873d6f8000-7f873d6fa000 rw-p 0017c000 08:01 7471224                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f873d6fa000-7f873d6fe000 rw-p 00000000 00:00 0
7f873d6fe000-7f873efb4000 r-xp 00000000 08:01 7476906                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f873efb4000-7f873f1b3000 ---p 018b6000 08:01 7476906                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f873f1b3000-7f873f1b4000 r--p 018b5000 08:01 7476906                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f873f1b4000-7f873f1b5000 rw-p 018b6000 08:01 7476906                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f873f1b5000-7f873f202000 r-xp 00000000 08:01 7472801                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
7f873f202000-7f873f401000 ---p 0004d000 08:01 7472801                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
7f873f401000-7f873f403000 r--p 0004c000 08:01 7472801                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
7f873f403000-7f873f404000 rw-p 0004e000 08:01 7472801                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
7f873f404000-7f873f406000 rw-p 00000000 00:00 0
7f873f406000-7f873f413000 r-xp 00000000 08:01 7472800                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
7f873f413000-7f873f613000 ---p 0000d000 08:01 7472800                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
7f873f613000-7f873f614000 r--p 0000d000 08:01 7472800                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
7f873f614000-7f873f615000 rw-p 0000e000 08:01 7472800                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
7f873f615000-7f873f65c000 r-xp 00000000 08:01 7471420                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f873f65c000-7f873f85b000 ---p 00047000 08:01 7471420                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f873f85b000-7f873f85d000 r--p 00046000 08:01 7471420                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f873f85d000-7f873f85f000 rw-p 00048000 08:01 7471420                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f873f85f000-7f873f982000 r-xp 00000000 08:01 7471870                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f873f982000-7f873fb81000 ---p 00123000 08:01 7471870                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f873fb81000-7f873fb8c000 r--p 00122000 08:01 7471870                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f873fb8c000-7f873fb8e000 rw-p 0012d000 08:01 7471870                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f873fb8e000-7f873fb8f000 rw-p 00000000 00:00 0
7f873fb8f000-7f873fbc3000 r-xp 00000000 08:01 7473481                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f873fbc3000-7f873fdc2000 ---p 00034000 08:01 7473481                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f873fdc2000-7f873fdc4000 r--p 00033000 08:01 7473481                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f873fdc4000-7f873fdc5000 rw-p 00035000 08:01 7473481                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f873fdc5000-7f873fde0000 r-xp 00000000 08:01 7476898                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f873fde0000-7f873ffdf000 ---p 0001b000 08:01 7476898                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f873ffdf000-7f873ffe0000 r--p 0001a000 08:01 7476898                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f873ffe0000-7f873ffe1000 rw-p 0001b000 08:01 7476898                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f873ffe1000-7f8740012000 r-xp 00000000 08:01 7473469                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f8740012000-7f8740212000 ---p 00031000 08:01 7473469                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f8740212000-7f8740213000 r--p 00031000 08:01 7473469                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f8740213000-7f8740214000 rw-p 00032000 08:01 7473469                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f8740214000-7f8740235000 r-xp 00000000 08:01 12321309                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f8740235000-7f8740434000 ---p 00021000 08:01 12321309                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f8740434000-7f8740435000 r--p 00020000 08:01 12321309                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f8740435000-7f8740436000 rw-p 00021000 08:01 12321309                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f8740436000-7f87405b5000 r-xp 00000000 08:01 7476910                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f87405b5000-7f87407b5000 ---p 0017f000 08:01 7476910                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f87407b5000-7f87407c5000 r--p 0017f000 08:01 7476910                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f87407c5000-7f87407c6000 rw-p 0018f000 08:01 7476910                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f87407c6000-7f87407ca000 rw-p 00000000 00:00 0
7f87407ca000-7f874098a000 r-xp 00000000 08:01 12325572                   /lib/x86_64-linux-gnu/libc-2.23.so
7f874098a000-7f8740b8a000 ---p 001c0000 08:01 12325572                   /lib/x86_64-linux-gnu/libc-2.23.so
7f8740b8a000-7f8740b8e000 r--p 001c0000 08:01 12325572                   /lib/x86_64-linux-gnu/libc-2.23.so
7f8740b8e000-7f8740b90000 rw-p 001c4000 08:01 12325572                   /lib/x86_64-linux-gnu/libc-2.23.so
7f8740b90000-7f8740b94000 rw-p 00000000 00:00 0
7f8740b94000-7f8740c38000 r-xp 00000000 08:01 7476026                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f8740c38000-7f8740e37000 ---p 000a4000 08:01 7476026                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f8740e37000-7f8740e3d000 r--p 000a3000 08:01 7476026                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f8740e3d000-7f8740e3e000 rw-p 000a9000 08:01 7476026                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f8740e3e000-7f8740ea8000 r-xp 00000000 08:01 7472803                    /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0
7f8740ea8000-7f87410a7000 ---p 0006a000 08:01 7472803                    /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0
7f87410a7000-7f87410aa000 r--p 00069000 08:01 7472803                    /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0
7f87410aa000-7f87410ab000 rw-p 0006c000 08:01 7472803                    /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.4.0
7f87410ab000-7f87412c6000 r-xp 00000000 08:01 12320797                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f87412c6000-7f87414c5000 ---p 0021b000 08:01 12320797                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f87414c5000-7f87414e1000 r--p 0021a000 08:01 12320797                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f87414e1000-7f87414ed000 rw-p 00236000 08:01 12320797                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f87414ed000-7f87414f0000 rw-p 00000000 00:00 0
7f87414f0000-7f874154e000 r-xp 00000000 08:01 12320798                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f874154e000-7f874174e000 ---p 0005e000 08:01 12320798                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f874174e000-7f8741752000 r--p 0005e000 08:01 12320798                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f8741752000-7f8741759000 rw-p 00062000 08:01 12320798                   /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f8741759000-7f874190a000 r-xp 00000000 08:01 7472814                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f874190a000-7f8741b09000 ---p 001b1000 08:01 7472814                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f8741b09000-7f8741b11000 r--p 001b0000 08:01 7472814                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f8741b11000-7f8741b13000 rw-p 001b8000 08:01 7472814                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f8741b13000-7f8741b14000 rw-p 00000000 00:00 0
7f8741b14000-7f8741b2c000 r-xp 00000000 08:01 12325559                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f8741b2c000-7f8741d2b000 ---p 00018000 08:01 12325559                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f8741d2b000-7f8741d2c000 r--p 00017000 08:01 12325559                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f8741d2c000-7f8741d2d000 rw-p 00018000 08:01 12325559                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f8741d2d000-7f8741d31000 rw-p 00000000 00:00 0
7f8741d31000-7f8741d34000 r-xp 00000000 08:01 12325557                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f8741d34000-7f8741f33000 ---p 00003000 08:01 12325557                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f8741f33000-7f8741f34000 r--p 00002000 08:01 12325557                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f8741f34000-7f8741f35000 rw-p 00003000 08:01 12325557                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f8741f35000-7f874203d000 r-xp 00000000 08:01 12325575                   /lib/x86_64-linux-gnu/libm-2.23.so
7f874203d000-7f874223c000 ---p 00108000 08:01 12325575                   /lib/x86_64-linux-gnu/libm-2.23.so
7f874223c000-7f874223d000 r--p 00107000 08:01 12325575                   /lib/x86_64-linux-gnu/libm-2.23.so
7f874223d000-7f874223e000 rw-p 00108000 08:01 12325575                   /lib/x86_64-linux-gnu/libm-2.23.so
7f874223e000-7f8742295000 r-xp 00000000 08:01 7477871                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f8742295000-7f8742495000 ---p 00057000 08:01 7477871                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f8742495000-7f8742496000 r--p 00057000 08:01 7477871                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f8742496000-7f8742497000 rw-p 00058000 08:01 7477871                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f8742497000-7f87424b2000 r-xp 00000000 08:01 7477988                    /usr/local/lib/libz.so.1.2.11
7f87424b2000-7f87426b1000 ---p 0001b000 08:01 7477988                    /usr/local/lib/libz.so.1.2.11
7f87426b1000-7f87426b2000 r--p 0001a000 08:01 7477988                    /usr/local/lib/libz.so.1.2.11
7f87426b2000-7f87426b3000 rw-p 0001b000 08:01 7477988                    /usr/local/lib/libz.so.1.2.11
7f87426b3000-7f87426d7000 r-xp 00000000 08:01 12321351                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f87426d7000-7f87428d6000 ---p 00024000 08:01 12321351                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f87428d6000-7f87428d7000 r--p 00023000 08:01 12321351                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f87428d7000-7f87428d8000 rw-p 00024000 08:01 12321351                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f87428d8000-7f87428ef000 r-xp 00000000 08:01 12325565                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f87428ef000-7f8742aef000 ---p 00017000 08:01 12325565                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f8742aef000-7f8742af0000 r--p 00017000 08:01 12325565                   /lib/x86_64-linux-gnu/libresolv-2.23.so
Аварийный останов (сделан дамп памяти)

Can you tell me what is the problem? Thanks in advance.
[phpinfo.txt](https://github.com/krakjoe/parallel/files/3610028/phpinfo.txt)

script is:
<?php

ini_set('display_errors', 1);
error_reporting(E_ALL);
$runtime = new \parallel\Runtime();

$future = $runtime->run(function(){
    for ($i = 0; $i < 500; $i++)
        echo "*";
    return "easy";
});
for ($i = 0; $i < 205; $i++) {

    echo ".";
}

**Comment by dotfry** [comment]
Works fine for me
```bash
php test.php
```
```
.................................***********************.......*************************.*..***.....*.**.*.*..........................*.***...............************.*..*.**.**********************************************.***..*.*.**************.**.***********************************************************.*.........*...*.*..*..*****.******************.*.......*.*............********............................................................******************************************************************************************************************************************************************************************************************************************************************
```

**Comment by krakjoe** [comment]
I'm a little confused, that code should not run at all with the latest version of parallel. Could you update your version and test again ...

**Comment by ilantipov** [comment]
Here I tried to install it via pecl and cloning git repo. Both "pecl install parallel" and "pecl install parallel-beta" with same result. Looks like I'd doing something wrong:)
[run.log](https://github.com/krakjoe/parallel/files/3621559/run.log)
[make.test.log](https://github.com/krakjoe/parallel/files/3621560/make.test.log)
[make.log](https://github.com/krakjoe/parallel/files/3621561/make.log)
[parallel-pecl.install.log](https://github.com/krakjoe/parallel/files/3621562/parallel-pecl.install.log)

**Comment by krakjoe** [comment]
Please try unloading other extensions, it's probably one of those.

**Comment by ilantipov** [comment]
Everything is ok if I disable propro.so, required by http.so. Is there any solution to make them work together?

**Comment by krakjoe** [comment]
Open an issue with the [tracker](http://github.com/m6w6/ext-propro) for that extension. It won't be a bug specific to the interaction between propro and parallel, it's far more likely just a general incompatibility with ZTS that the author has overlooked and parallel exhibits because it happens to use ZTS aparatus - if the extension were tested in a SAPI that used threads (at test time) it would exhibit the same behaviour.

/cc @m6w6
