### ISSUE TITLE
Wrote a wrapper for Parallel

### ISSUE THREAD

**Issue by merlinthemagic** [krakjoe/parallel#91]
Hi,

I found this project very interesting, but since it is pretty new the documentation is obviously lacking. That is to be expected.

I intend to use this project and in order for me to understand how it all ties together I wrote a wrapper. Its just how i learn :/

Threads are hard to envision if you have never dealt with concurrency before and i think the wrapper might lower the entry bar for some. 

Once someone has successfully spawned a thread and see the potential they can abandon the wrapper and make efficient use of parallel directly. 

Check it out [Here](https://github.com/merlinthemagic/MTM-Async/blob/master/Docs/Examples/Parallel/README.md), Please let me know where i might have misunderstood relationships between objects or any other advice.

**Comment by landall** [comment]
A good wrapper! I like it!
