### ISSUE TITLE
Bidirectionnal interprocess communication, Channel and Events : make it easy.

### ISSUE THREAD

**Issue by Tuckbros** [krakjoe/parallel#93]
To go on issues #38 and #59, with my current understanding of channels and event,
when a runtime sends a message on a channel, it can be either :
	received by any runtime waiting for it (Channel::recv()) or 
	polled as an event (Events::poll()).

channel::recv() is blocking and runtime will wait until a message is received.
event::poll() can be non-blocking and runtime can continue if nothing is happening on the channel. 

Event polling is good for processing a stack with multiple identical workers (runtimes).

My runtimes have almost always different purposes. 
What I need is bidirectionnal communication between runtimes (interprocess communication). 
I can achieve this by making a channel for each direction and add it to the event loop of the receiving runtime.

But I am lazy, it would be great if I could cut the number of channels to create by 2 (or more).
Is there any way to do a multidirectionnal channel by filtering the polled events ?
I can think of several ways to improve the current behavior to fit my needs :
	excluding the message received from myself (for example with a boolean passed to the poll method)
	polling only events received from a specified source (for example with the name of the source passed to the poll method)
	allowing custom event type and filtering on these types (for example with the event type passed to the poll method).

**Comment by dotfry** [comment]
I'll use this kind of message:
```php
class ChannelMessage
{
public string $messagePayload;

public Channel $replyTo;

/** ... more */
}
```

And use `$replyTo` to send response message.

**Comment by Tuckbros** [comment]
I would like to say yes, but no. I am looking for a way to simplify the communication between my runtimes. Your solution can be useful to reply on a specific channel which is not known in advance of the recipient. The sender tell the recipient where to reply. But, all the same, this channel to reply on has to exist, to be distinct of the one on which the message was send and also to be added in an event loop (it is everything I am trying to avoid).
I would still need 2 channels for 2 runtimes to communicate.
### **EDIT**
My bad. Now I get it. A single channel for each target runtime. Every source runtime which has to send something to a target runtime will send it to the target runtime channel. As per my problem description, the source has to sign the sign message so that the target is able to answer.

**Comment by Tuckbros** [comment]
maybe I don't need that much channels. A single channel for each runtime where every runtime having to communicate will send messages...

**Comment by krakjoe** [comment]
Sorry, this is outside of the scope of issues, this is a programming issue, not an implementation one.
