### ISSUE TITLE
class not found windows machine

### ISSUE THREAD

**Issue by itisjoby** [krakjoe/parallel#94]
i am getting a class not found error in a windows machine .the phpinfo() has parallel 1.1.3 and the error thrown is 
Fatal error: Uncaught Error: Class 'parallel\Runtime' not found in...

**Comment by Tuckbros** [comment]
make sure you are using it  by adding this prior to any use parallel stuff :
`use \parallel\{Runtime, Future, Channel, Events};`

**Comment by krakjoe** [comment]
This is not an extension issue.

**Comment by aungmindev** [comment]
Fatal error: Uncaught Error: Class 'parallel\Runtime' not found in /var/www/html/test/index.php:3 Stack trace: #0 {main} thrown in /var/www/html/test/index.php on line 3

I have this error even I install parallel on ubuntu. Please Help me

**Comment by Koetemp** [comment]
I have the same error.
