### ISSUE TITLE
Need an example to producer-consumer pattern

### ISSUE THREAD

**Issue by landall** [krakjoe/parallel#96]
I need a multi-worker thread pool to process some actions with producer-consumer pattern.
However the document about Event and Pool is too little.
Can you show me an example about this situation?

BTW, Can I use a Channel with many writers and many readers?

**Comment by Tuckbros** [comment]
There is a working example in [https://github.com/krakjoe/parallel/issues/34](https://github.com/krakjoe/parallel/issues/34) ( the example itself is [here](https://gist.github.com/krakjoe/0ee02b887288720d9b785c9f947f3a0a)) . To make it work out of the box, you just have to be aware that to use https you need a php with openssl enabled).
About Channels, many readers : Yes. many writers : I never tried.

**Comment by landall** [comment]
> There is a working example in #34 ( the example itself is [here](https://gist.github.com/krakjoe/0ee02b887288720d9b785c9f947f3a0a)) . To make it work out of the box, you just have to be aware that to use https you need a php with openssl enabled).
> About Channels, many readers : Yes. many writers : I never tried.

I have read #34 and still cannot understand how to use Channel and Event. and some functions seem to be out of document in php.net.

**Comment by Tuckbros** [comment]
To make it simple a channel is a "stack" provided with messages sent (`send()`) by runtimes (your "writers").
At the other end you find the "readers" to retrieve messages passed over channels. 
Messages are accessible by explicitly waiting to receive (`recv()`) the message on the channel (this is blocking and the reader will wait for an incoming message to go on). 
But you can also access messages thanks to events (which can be not blocking). For this you have to create an event loop (over the events). You have to specify what channel you are "monitoring" by adding it to the events. When a message is sent, it will be an event. You can retrieve it from the events by polling it. The attention is that the monitored channel is kind of attached to the event : by polling the event you are also removing the channel from the event loop so you will have to add the channel again if you want to process another event.

**Comment by landall** [comment]
> To make it simple a channel is a "stack" provided with messages sent (`send()`) by runtimes (your "writers").
> At the other end you find the "readers" to retrieve messages passed over channels.
> Messages are accessible by explicitly waiting to receive (`recv()`) the message on the channel (this is blocking and the reader will wait for an incoming message to go on).
> But you can also access messages thanks to events (which can be not blocking). For this you have to create an event loop (over the events). You have to specify what channel you are "monitoring" by adding it to the events. When a message is sent, it will be an event. You can retrieve it from the events by polling it. The attention is that the monitored channel is kind of attached to the event : by polling the event you are also removing the channel from the event loop so you will have to add the channel again if you want to process another event.

is every event in an event loop only triggered once before it is removed?
I think when a message is sent to a channel, a thread with a future is ended,  the event is triggered.

And what is the setInput() method used for?

**Comment by landall** [comment]
Multi writers, one reader is NOT OK.
I just perform a test. 5 writers write 40 pieces of data. The reader only get 9-39 every time.

**Comment by Tuckbros** [comment]
can you share the code ?

**Comment by Tuckbros** [comment]
> > To make it simple a channel is a "stack" provided with messages sent (`send()`) by runtimes (your "writers").
> > At the other end you find the "readers" to retrieve messages passed over channels.
> > Messages are accessible by explicitly waiting to receive (`recv()`) the message on the channel (this is blocking and the reader will wait for an incoming message to go on).
> > But you can also access messages thanks to events (which can be not blocking). For this you have to create an event loop (over the events). You have to specify what channel you are "monitoring" by adding it to the events. When a message is sent, it will be an event. You can retrieve it from the events by polling it. The attention is that the monitored channel is kind of attached to the event : by polling the event you are also removing the channel from the event loop so you will have to add the channel again if you want to process another event.
> 
> is every event in an event loop only triggered once before it is removed?
> I think when a message is sent to a channel, a thread with a future is ended, the event is triggered.
> 
> And what is the setInput() method used for?

This all is what I experienced playing with it. I am not into its developpment : so use it with care.
About setInput(), I haven't used it yet, I can't say. For the Event : I would say yes, "polling" it, is like unstacking it. It makes it unavailable to others. If an event occurs on the channel while it is not added to your event loop you could miss it.

**Comment by landall** [comment]
> can you share the code ?

ThreadPool.class.php
```
namespace PersonalCloudStorage;

use \parallel\{Runtime, Future, Channel, Events};

class ThreadPool
{
	public $workers;
	public $channel_go, $channel_return;

	public function __construct(callable $func, array $args, int $threadCount = 5)
	{
		$s = function($func, $args)
		{
			return call_user_func($func, $args);
		};

		$this->channel_go = new Channel(1000);
		$this->channel_return = new Channel(1000);

		$this->workers = array();
		for($i=1;$i<=$threadCount;$i++)
		{
			$a = new Runtime();
			$future = $a->run($s, array($func, array('command'=>$this->channel_go,'reply'=>$this->channel_return, 'args'=>$args, 'id'=>$i)));
			$this->workers[$i] = array('thread'=>$a,'future'=>$future);
		}
	}

	public function addTask($data)
	{
		$this->channel_go->send($data);
	}

	public function getReply()
	{
		return $this->$channel_return->recv();
	}       

	public function isAllDone() : bool
	{
		foreach($this->workers as $w)
			if (!$w['future']->done()) return false;
		return true;
	}
}
```
Main.php
```
<?php
require_once __DIR__ . '/../libs/autoload.php';

use PersonalCloudStorage\Debug;
use PersonalCloudStorage\ThreadPool;

$s = function(array $init)
{
	require_once __DIR__ . '/../libs/autoload.php';
	$ch_cmd = $init['command'];
	$ch_reply = $init['reply'];
	$args = $init['args'];
	$id = 'Thread_'.$init['id'];

	Debug::pr2($id, $args);

	$counter = 0;

	while(true)
	{
		$data=$ch_cmd->recv();
		if($data=='0') break;
		Debug::pr2($id, $data);
		$ch_reply->send(array($data,'>>>'.$data.'<<<'));
		usleep(5);
		$counter++;
	}
	
	Debug::pr2($id, '--Thread End--');
	return $counter;
};

$pool = new ThreadPool($s, array(1, '12', 'abc'));

for($i=1;$i<=40;$i++)
{
	$pool->addTask($i);
}

$pool->addTask('0');
$pool->addTask('0');
$pool->addTask('0');
$pool->addTask('0');
$pool->addTask('0');

while(!$pool->isAllDone())
{
	$a = $pool->getReply();
	Debug::pr2('Main', json_encode($a));
	sleep(1);
}

Debug::pr2('Main', $pool->getResults());

Debug::p('----END----');

```
Debug.class.php
```
class Debug
{
	public static function p($value)
	{
		echo $value;
		echo PHP_EOL;
	}

	public static function p2($value)
	{
		echo json_encode($value, JSON_PRETTY_PRINT + JSON_UNESCAPED_UNICODE + JSON_UNESCAPED_SLASHES);
		echo PHP_EOL;
	}

	public static function pr2($prefix, $value)
	{
		echo '['.$prefix.'] '.print_r($value, true);
		echo PHP_EOL;
	}
}

```
It should be like this. I have modified the code....

**Comment by krakjoe** [comment]
Sorry, this is outside the scope of issues.
