### ISSUE TITLE
How to work with autoload?

### ISSUE THREAD

**Issue by landall** [krakjoe/parallel#97]
I find in worker thread the php cannot find a autoload class.

What should i do with it?

**Comment by landall** [comment]
I find constant also do not make effect in a worker thread.

**Comment by Tuckbros** [comment]
It is kind of scope issue. You may have to "bootstrap" what your need in order to make it available to the worker.

**Comment by landall** [comment]
> It is kind of scope issue. You may have to "bootstrap" what your need in order to make it available to the worker.

it is hard to do in a large project.

**Comment by landall** [comment]
Is there any way to inherite/clone the setting of main thread to worker thread?

**Comment by landall** [comment]
i start to read the php-src now. i wonder why a new thread must reset its constant and autoload setting.

**Comment by ghost** [comment]
Because the architecture is share nothing. The engines are completely isolated from each other.

You need to use a bootstrap file to include the autoloader and define all necessary constants.

**Comment by krakjoe** [comment]
Sorry, this is outside of the scope of issues.
